### PR TITLE
Add support for Razer Huntsman V2 Analog

### LINKED ISSUE #1458: Support for Razer Huntsman V2 Analog
### Device Info

* Name: Razer Huntsman V2 Analog
* Product Number: RZ033610200-R301
* Model Number: RZ03-0361

### Device Information
```
Please post the output of
    lsusb -d 1532: -v


Bus 001 Device 003: ID 1532:0266 Razer USA, Ltd Razer Huntsman V2 Analog
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0266 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Huntsman V2 Analog
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0086
    bNumInterfaces          5
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     212
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0018  1x 24 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      79
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      22
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        4
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              2 Razer Huntsman V2 Analog
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     348
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0002  1x 2 bytes
        bInterval               1
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0000
  (Bus Powered)
```

```
Please post the output of
    ls -lah /dev/input/by-id/


lrwxrwxrwx 1 root root  10 Mar 13 15:02 usb-Razer_Razer_Huntsman_V2_Analog-event-if01 -> ../event17
lrwxrwxrwx 1 root root  10 Mar 13 15:02 usb-Razer_Razer_Huntsman_V2_Analog-event-if04 -> ../event25
lrwxrwxrwx 1 root root  10 Mar 13 15:02 usb-Razer_Razer_Huntsman_V2_Analog-event-kbd -> ../event20
lrwxrwxrwx 1 root root  10 Mar 13 15:02 usb-Razer_Razer_Huntsman_V2_Analog-if01-event-kbd -> ../event21
lrwxrwxrwx 1 root root  10 Mar 13 15:02 usb-Razer_Razer_Huntsman_V2_Analog-if02-event-mouse -> ../event24
lrwxrwxrwx 1 root root   9 Mar 13 15:02 usb-Razer_Razer_Huntsman_V2_Analog-if02-mouse -> ../mouse1
```
### Packet Captures
[Razer Huntsman v2 Packet Cap.tar.gz](https://github.com/openrazer/openrazer/files/6135506/Razer.Huntsman.v2.Packet.Cap.tar.gz)

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>
Attached

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>
Passed through all usb controllers to VM to get these:

Hv2 - Home Screen

Hv2 - Lighting Tab

Hv2 - Chroma Studio

Please let me know if there's any more information I can provide. 

Thanks!

### PR DESCRIPTION
**Pull request by z3ntu**
Without driver mode support for now, because that needs special handling
for even the normal key input to work (because of analog keys).

Fixes #1458

---

How to build and test: https://github.com/openrazer/openrazer/wiki/Building-a-package

CC @mhardeman

### CODE REVIEW

**Comment by mhardeman** [comment]
Quick note:

I was unable to get this working, albeit I was doing a ham-handed partial down streaming of this into librazermacos and trying it.

I made changes similar to yours to the razer_attr_write_mode_static_no_store version of the call and was finally able to get the keyboard to accept that.

**Comment by ronasuti** [comment]
I'm trying to get this to compile on Pop!_OS (basically Ubuntu under the hood) and I ran into issues:
```
dpkg-buildpackage: info: source package openrazer
dpkg-buildpackage: info: source version 2.2.2-1
dpkg-buildpackage: info: source distribution xenial
dpkg-buildpackage: info: source changed by Luca Weiss <luca@z3ntu.xyz>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
 fakeroot debian/rules clean
dh clean --with-python3
dh: warning: Compatibility levels before 10 are deprecated (level 9 in use)
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/tmp/tmp.dO8zYFrqmJ_deb_build_tmp/razer'
/usr/bin/make lp_driver_clean
make[2]: Entering directory '/tmp/tmp.dO8zYFrqmJ_deb_build_tmp/razer'
-e 
:: Cleaning OpenRazer kernel modules (Launchpad)
========================================
make -C "/lib/modules/5.11.0-7620-generic/build" SUBDIRS="/tmp/tmp.dO8zYFrqmJ_deb_build_tmp/razer/driver" clean
make[3]: Entering directory '/usr/src/linux-headers-5.11.0-7620-generic'
mkdir: cannot create directory ‘.tmp_40507’: Permission denied
mkdir: cannot create directory ‘.tmp_40509’: Permission denied
mkdir: cannot create directory ‘.tmp_40511’: Permission denied
mkdir: cannot create directory ‘.tmp_40513’: Permission denied
mkdir: cannot create directory ‘.tmp_40515’: Permission denied
mkdir: cannot create directory ‘.tmp_40517’: Permission denied
mkdir: cannot create directory ‘.tmp_40520’: Permission denied
mkdir: cannot create directory ‘.tmp_40522’: Permission denied
mkdir: cannot create directory ‘.tmp_40524’: Permission denied
mkdir: cannot create directory ‘.tmp_40526’: Permission denied
mkdir: cannot create directory ‘.tmp_40528’: Permission denied
mkdir: cannot create directory ‘.tmp_40530’: Permission denied
mkdir: cannot create directory ‘.tmp_40532’: Permission denied
mkdir: cannot create directory ‘.tmp_40534’: Permission denied
mkdir: cannot create directory ‘.tmp_40536’: Permission denied
mkdir: cannot create directory ‘.tmp_40538’: Permission denied
mkdir: cannot create directory ‘.tmp_40540’: Permission denied
mkdir: cannot create directory ‘.tmp_40542’: Permission denied
mkdir: cannot create directory ‘.tmp_40544’: Permission denied
mkdir: cannot create directory ‘.tmp_40546’: Permission denied
mkdir: cannot create directory ‘.tmp_40548’: Permission denied
mkdir: cannot create directory ‘.tmp_40550’: Permission denied
mkdir: cannot create directory ‘.tmp_40552’: Permission denied
mkdir: cannot create directory ‘.tmp_40554’: Permission denied
mkdir: cannot create directory ‘.tmp_40556’: Permission denied
mkdir: cannot create directory ‘.tmp_40558’: Permission denied
mkdir: cannot create directory ‘.tmp_40560’: Permission denied
mkdir: cannot create directory ‘.tmp_40562’: Permission denied
mkdir: cannot create directory ‘.tmp_40564’: Permission denied
mkdir: cannot create directory ‘.tmp_40567’: Permission denied
mkdir: cannot create directory ‘.tmp_40569’: Permission denied
mkdir: cannot create directory ‘.tmp_40571’: Permission denied
mkdir: cannot create directory ‘.tmp_40573’: Permission denied
mkdir: cannot create directory ‘.tmp_40575’: Permission denied
mkdir: cannot create directory ‘.tmp_40577’: Permission denied
mkdir: cannot create directory ‘.tmp_40579’: Permission denied
mkdir: cannot create directory ‘.tmp_40581’: Permission denied
mkdir: cannot create directory ‘.tmp_40583’: Permission denied
mkdir: cannot create directory ‘.tmp_40585’: Permission denied
mkdir: cannot create directory ‘.tmp_40587’: Permission denied
mkdir: cannot create directory ‘.tmp_40620’: Permission denied
mkdir: cannot create directory ‘.tmp_40728’: Permission denied
mkdir: cannot create directory ‘.tmp_40730’: Permission denied
mkdir: cannot create directory ‘.tmp_40732’: Permission denied
mkdir: cannot create directory ‘.tmp_40928’: Permission denied
mkdir: cannot create directory ‘.tmp_40930’: Permission denied
mkdir: cannot create directory ‘.tmp_40932’: Permission denied
mkdir: cannot create directory ‘.tmp_40934’: Permission denied
mkdir: cannot create directory ‘.tmp_40936’: Permission denied
mkdir: cannot create directory ‘.tmp_40977’: Permission denied
mkdir: cannot create directory ‘.tmp_40979’: Permission denied
mkdir: cannot create directory ‘.tmp_40981’: Permission denied
mkdir: cannot create directory ‘.tmp_40983’: Permission denied
mkdir: cannot create directory ‘.tmp_40985’: Permission denied
mkdir: cannot create directory ‘.tmp_40987’: Permission denied
mkdir: cannot create directory ‘.tmp_40989’: Permission denied
mkdir: cannot create directory ‘.tmp_40991’: Permission denied
mkdir: cannot create directory ‘.tmp_40993’: Permission denied
mkdir: cannot create directory ‘.tmp_41349’: Permission denied
fs/aufs/Makefile:3: fs/aufs/magic.mk: No such file or directory
make[5]: *** No rule to make target 'fs/aufs/magic.mk'.  Stop.
make[4]: *** [scripts/Makefile.clean:71: fs/aufs] Error 2
make[3]: *** [Makefile:1855: _clean_fs] Error 2
make[3]: Leaving directory '/usr/src/linux-headers-5.11.0-7620-generic'
make[2]: *** [Makefile:69: lp_driver_clean] Error 2
make[2]: Leaving directory '/tmp/tmp.dO8zYFrqmJ_deb_build_tmp/razer'
make[1]: *** [debian/rules:46: override_dh_auto_clean] Error 2
make[1]: Leaving directory '/tmp/tmp.dO8zYFrqmJ_deb_build_tmp/razer'
make: *** [debian/rules:49: clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
```

I saw the "permission denied" turning up so I tried running it with root permissions and I got this:

```
dpkg-buildpackage: info: source package openrazer
dpkg-buildpackage: info: source version 2.2.2-1
dpkg-buildpackage: info: source distribution xenial
dpkg-buildpackage: info: source changed by Luca Weiss <luca@z3ntu.xyz>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
 debian/rules clean
dh clean --with-python3
dh: warning: Compatibility levels before 10 are deprecated (level 9 in use)
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/tmp/tmp.rp7texIBo4_deb_build_tmp/razer'
/usr/bin/make lp_driver_clean
make[2]: Entering directory '/tmp/tmp.rp7texIBo4_deb_build_tmp/razer'
-e 
:: Cleaning OpenRazer kernel modules (Launchpad)
========================================
make -C "/lib/modules/5.11.0-7620-generic/build" SUBDIRS="/tmp/tmp.rp7texIBo4_deb_build_tmp/razer/driver" clean
make[3]: Entering directory '/usr/src/linux-headers-5.11.0-7620-generic'
fs/aufs/Makefile:3: fs/aufs/magic.mk: No such file or directory
make[5]: *** No rule to make target 'fs/aufs/magic.mk'.  Stop.
make[4]: *** [scripts/Makefile.clean:71: fs/aufs] Error 2
make[3]: *** [Makefile:1855: _clean_fs] Error 2
make[3]: Leaving directory '/usr/src/linux-headers-5.11.0-7620-generic'
make[2]: *** [Makefile:69: lp_driver_clean] Error 2
make[2]: Leaving directory '/tmp/tmp.rp7texIBo4_deb_build_tmp/razer'
make[1]: *** [debian/rules:46: override_dh_auto_clean] Error 2
make[1]: Leaving directory '/tmp/tmp.rp7texIBo4_deb_build_tmp/razer'
make: *** [debian/rules:49: clean] Error 2
dpkg-buildpackage: error: debian/rules clean subprocess returned exit status 2
```

Not really sure what to do here. I'm spoiled by Cargo, working around makefiles is completely foreign to me.

**Comment by z3ntu** [comment]
```
fs/aufs/Makefile:3: fs/aufs/magic.mk: No such file or directory
make[5]: *** No rule to make target 'fs/aufs/magic.mk'.  Stop.
```
This doesn't look related to openrazer. Maybe double check that you have the correct and latest kernel headers installed for your kernel.

**Comment by intellitour** [comment]
I was able to build and setup... but, any setting I change does not get applied.

**Comment by mhardeman** [comment]
Yes.  I had the same issue.

I added mods to the set static mode to use the NOSTORE instead of VARSTORE and that worked.

**Comment by intellitour** [comment]
After a kernel update, I can change Chroma  effects and that's it. I believe it's an embryo that must develop and grow in order to extract full funcionality from the keyboard.

**Comment by z3ntu** [comment]
@intellitour Can you please elaborate?

**Comment by ronasuti** [comment]
> ```
> fs/aufs/Makefile:3: fs/aufs/magic.mk: No such file or directory
> make[5]: *** No rule to make target 'fs/aufs/magic.mk'.  Stop.
> ```
> 
> This doesn't look related to openrazer. Maybe double check that you have the correct and latest kernel headers installed for your kernel.

I've tried getting my kernel setup fixed (I force-installed a newer kernel for better hardware support of my laptop, but I could live with the old one). It didn't work, and from what I've read, it doesn't work specifically because it's trying to compile the whole Linux kernel because the SUBDIRS parameter was deprecated back in 5.3 and is outright ignored on newer kernels like 5.11 which I use. I figure this probably compiles fine on Ubuntu 20.04 LTS which uses 5.4 but spits out the deprecation notice. 5.11, which is used by Ubuntu 21.04, won't compile period.

**Comment by intellitour** [comment]
> @intellitour Can you please elaborate?

@z3ntu 
My point is: at the current state, the version I built from this PR can only control basic Chroma effects. No other features are available. I completely understand the difficulties and I believe this PR should be accepted as a starting point and we (Huntsman V2 owners)  should collaborate to bring on more funcionality.

**Comment by ronasuti** [comment]
I concur with @intellitour, we should move forward with this for now, as even basic chroma effects would be greatly welcome for now. I'm quite rusty at C, but I'd like to lend a hand getting the analog features to work where I can.

**Comment by z3ntu** [comment]
@intellitour Just to clarify, you're talking about analog key input, hypershift and the things like that?

**Comment by intellitour** [comment]
> @intellitour Just to clarify, you're talking about analog key input, hypershift and the things like that?

Yep... the more funcionality the better. Don't you agree?

**Comment by z3ntu** [comment]
Merging the current version - and opened #1579 for the analog key input.

**Comment by ronasuti** [comment]
I just pulled down the update, works perfectly on Pop!_OS 21.04, kernel 5.11.0--7620. Oddly enough, I cannot compile the actual DEB files for the life of me on this system (something to do with newer linux versions not supporting SUBDIR), but compiled DEB binaries work like a charm.

Thanks!

**Pull request merged**
