### PR TITLE
Add support for Razer DeathStalker V2 Pro Wired/Wireless and for Basilisk V3 Pro Wired/Wireless

### LINKED ISSUE #1907: Support for Razer DeathStalker V2 Pro
### Device Info
* Manufacturer: Razer
* Name: [DEATHSTALKER V2 PRO](https://www.razer.com/gaming-keyboards/razer-deathstalker-v2-pro/RZ03-04360200-R3U1)
* Product Number: RZ03-04360200-R3U1
* Model Number: RZ03-0436

### Device Information
```    lsusb -d 1532:0292 -v
Bus 001 Device 011: ID 1532:0292 Razer USA, Ltd DSV2 Pro
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0292 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0086
    bNumInterfaces          5
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     177
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      75
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      22
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        4
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     348
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
```
Please post the output of
    ls -lah /dev/input/by-id/
```
lrwxrwxrwx 1 root root   11 Sep 11 13:01 usb-Razer_DSV2_Pro-event-if01 -> ../event262
lrwxrwxrwx 1 root root   11 Sep 11 13:01 usb-Razer_DSV2_Pro-event-if04 -> ../event264
lrwxrwxrwx 1 root root   11 Sep 11 13:01 usb-Razer_DSV2_Pro-event-kbd -> ../event260
lrwxrwxrwx 1 root root   11 Sep 11 13:01 usb-Razer_DSV2_Pro-if01-event-kbd -> ../event261
lrwxrwxrwx 1 root root   11 Sep 11 13:01 usb-Razer_DSV2_Pro-if02-event-mouse -> ../event263
lrwxrwxrwx 1 root root    9 Sep 11 13:01 usb-Razer_DSV2_Pro-if02-mouse -> ../mouse7
```
### Packet Captures
TODO:
<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
TODO:
<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>

### LINKED ISSUE #1926: Support for Basilisk V3 Pro
### Device Info

* Name: Razer Basilisk V3 Pro
* Product Number: RZ01-04620100-R3A1
* Model Number: RZ01-0462

### Device Information
```
lsusb -d 1532: -v

Bus 003 Device 006: ID 1532:00ab Razer USA, Ltd Razer Basilisk V3 Pro
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x00ab 
  bcdDevice            1.00
  iManufacturer           1 Razer
  iProduct                2 Razer Basilisk V3 Pro
  iSerial                 3 000000000000
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          4 Default configuration
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     314
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)
```

```
ls -lah /dev/input/by-id/

lrwxrwxrwx 1 root root  10 Oct 13 14:22 usb-04d9_USB_Keyboard-event-if01 -> ../event19
lrwxrwxrwx 1 root root   9 Oct 13 14:22 usb-04d9_USB_Keyboard-event-kbd -> ../event3
lrwxrwxrwx 1 root root  10 Oct 13 14:22 usb-Razer_Razer_Basilisk_V3_Pro_000000000000-event-if01 -> ../event23
lrwxrwxrwx 1 root root  10 Oct 13 14:22 usb-Razer_Razer_Basilisk_V3_Pro_000000000000-event-mouse -> ../event20
lrwxrwxrwx 1 root root  10 Oct 13 14:22 usb-Razer_Razer_Basilisk_V3_Pro_000000000000-if01-event-kbd -> ../event21
lrwxrwxrwx 1 root root  10 Oct 13 14:22 usb-Razer_Razer_Basilisk_V3_Pro_000000000000-if01-event-mouse -> ../event22
lrwxrwxrwx 1 root root   9 Oct 13 14:22 usb-Razer_Razer_Basilisk_V3_Pro_000000000000-if01-mouse -> ../mouse1
lrwxrwxrwx 1 root root  10 Oct 13 14:22 usb-Razer_Razer_Basilisk_V3_Pro_000000000000-if02-event-kbd -> ../event24
lrwxrwxrwx 1 root root   9 Oct 13 14:22 usb-Razer_Razer_Basilisk_V3_Pro_000000000000-mouse -> ../mouse0
```

### Packet Captures
[basiliskv3pro_1.zip](https://github.com/openrazer/openrazer/files/9804593/basiliskv3pro_1.zip)

### Synapse Screenshots
razer1
razer2
razer3
razer4
razer5

### PR DESCRIPTION
**Pull request by 6razz1**
I've implemented the changes for the DeathStalker V2 Pro Wired/Wireless and for the Basilisk V3 Pro Wired/Wireless.
Everything seems to be ok... except macro recording for DeathStalker V2 Pro.

Resolves #1907
Resolves #1926

### CODE REVIEW

**Comment by 0xADF** [comment]
Please set MATRIX_DIMS = [1, 13] for Basilisk V3 Pro, otherwise not all LEDs are addressed. Thank you!

**Comment by 6razz1** [comment]
@0xADF I have made changes.
thnx!

**Comment by amenokagaseo** [comment]
Are maintainers not seeing this? It builds and functions perfectly for all aspects of the two devices. I get that the DeathStalker V2 already has an existing implementation but at least pull the Basilisk V3 Pro.

**Comment by z3ntu** [comment]
@6razz1 Have you seen this comment regarding DeathStalker V2 Pro in wireless mode? https://github.com/openrazer/openrazer/issues/1907#issuecomment-1381244925

**Comment by 6razz1** [comment]
@z3ntu I don't know what to say... I've been using DeathStalker V2 Pro in wireless mode mostly (same as now) almost two months every day... without any issue.

**Comment by z3ntu** [comment]
I've cleaned up the commits and made sure no other devices have some changes added that they shouldn't. Could you please test again on the latest commit in this PR to make sure I haven't broken anything by accident?

**Comment by 6razz1** [comment]
@z3ntu I just tried (wireless and wired devices). Everything seems to be ok.

**Review by z3ntu — APPROVED** [review]
LGTM, thanks!

**Comment by devilsclaw** [comment]
When I compile and install all of this on Ubuntu 22.04 while running wireless, have not tried while wired yet. It makes the whole keyboard fail to work in any manner. I have to connect a second keyboard and uninstall the kernel driver to get it working again. I have never configured it in a windows environment due to a bug in my VM to where anything besides updating the firmware on the dongle and keyboard are black windows.

**Comment by devilsclaw** [comment]
Never mind I used a target in the Makefile instead of doing the debian build instructions and now that I did the build instructions it does not cause that problem. Thanks.

**Comment by devilsclaw** [comment]
So I guess the question I am wondering now that this is install what software do I use to configure this keyboard. I tried polychromatic but it just throws and error about a file not existing.

**Comment by devilsclaw** [comment]
The other problem I am having is a couple of the applications throw this error

razer-cli and polychromatic

Traceback (most recent call last):
  File ’/usr/local/bin/polychromatic-controller’, line 311, in _change_tab
    tab_objects[index].set_tab()
  File ’/usr/lib/python3/dist-packages/polychromatic/controller/devices.py’, line 89, in set_tab
    device_list = self.middleman.get_devices()
  File ’/usr/lib/python3/dist-packages/polychromatic/middleman.py’, line 151, in get_devices
    self._reload_device_cache_if_empty()
  File ’/usr/lib/python3/dist-packages/polychromatic/middleman.py’, line 122, in _reload_device_cache_if_empty
    device_list = backend.get_devices()
  File ’/usr/lib/python3/dist-packages/polychromatic/backends/openrazer.py’, line 149, in get_devices
    devices.append(self._get_device(rdevice))
  File ’/usr/lib/python3/dist-packages/polychromatic/backends/openrazer.py’, line 220, in _get_device
    device.battery = self._get_battery_object(rdevice)
  File ’/usr/lib/python3/dist-packages/polychromatic/backends/openrazer.py’, line 293, in _get_battery_object
    battery.refresh()
  File ’/usr/lib/python3/dist-packages/polychromatic/backends/openrazer.py’, line 289, in refresh
    self.is_charging = self._rdevice.is_charging
  File ’/usr/local/lib/python3.10/dist-packages/openrazer-3.5.1-py3.10.egg/openrazer/client/devices/__init__.py’, line 456, in is_charging
    return bool(self._dbus_interfaces[’power’].isCharging())
  File ’/usr/lib/python3/dist-packages/dbus/proxies.py’, line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File ’/usr/lib/python3/dist-packages/dbus/connection.py’, line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.FileNotFoundError: Traceback (most recent call last):
  File ’/usr/lib/python3/dist-packages/dbus/service.py’, line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File ’/usr/lib/python3/dist-packages/openrazer_daemon/dbus_services/dbus_methods/mamba.py’, line 35, in is_charging
    with open(driver_path, ’r’) as driver_file:
FileNotFoundError: [Errno 2] No such file or directory: ’/sys/devices/pci0000:00/0000:00:08.1/0000:0b:00.3/usb5/5-1/5-1:1.2/0003:1532:0290.000C/charge_status’



I commented out the code that is looking for the battery info and the programs run but none of the options I select actually change anything on the keyboard.

**Comment by devilsclaw** [comment]
Never mind to everything. I cleaned out the kernel modules and other places from my original botched install of openrazer and then reinstalled everything and it works as intended

**Pull request merged**
