### PR TITLE
Auto-detect python3 folder

### LINKED ISSUE #69: Issue with Daemon(+auto-detect for python)
Hi,
Btw fwiw before going on with this issue it should be noted that pythondir detection should be done automatically, getting real folder of python for exemple(for me it was /usr/lib/64/python3.4 instead of /usr/lib/python3) and using site-packages on not debian based distros(dist-packages is only used on debian based ones while site-packages is used if python was built from source, Gentoo-like)
Anyways on with the real issue

First of all driver works perfectly:  scripts to retrieve infos on my devices works perfectly, the issue is daemon related. If I try to launch any interface to the daemon(ie polychromatic) in normal user mode it won't detect the driver and if I do it in su mode it will just timeout
The log of all the instances of razer-service has always the same exact issue that I can't seem to understand the reason.

> ThinkPadW500 logs # cat razer.log 
> 2016-10-26 16:05:58 | razer                          | INFO     | Initialising Daemon (v1.0.17). Pid: 5279
> 2016-10-26 16:05:58 | razer.screensaver              | INFO     | Initialising DBus Screensaver Thread
> 2016-10-26 16:06:00 | razer.screensaver              | INFO     | Initialising DBus screensaver object
> 2016-10-26 16:06:00 | razer.screensaver              | WARNING  | Could not find screensaver DBus
> 2016-10-26 16:06:00 | razer.screensaver              | INFO     | Initialising DBus screensaver object
> 2016-10-26 16:06:00 | razer.screensaver              | WARNING  | Could not find screensaver DBus
> 2016-10-26 16:06:00 | razer.screensaver              | INFO     | Initialising DBus screensaver object
> 2016-10-26 16:06:00 | razer.screensaver              | WARNING  | Could not find screensaver DBus
> 2016-10-26 16:06:00 | razer.screensaver              | WARNING  | Giving up on screensaver
> 2016-10-26 17:10:39 | razer                          | INFO     | Initialising Daemon (v1.0.17). Pid: 8066
> 2016-10-26 17:10:39 | razer.screensaver              | INFO     | Initialising DBus Screensaver Thread
> 2016-10-26 17:10:41 | razer.screensaver              | INFO     | Initialising DBus screensaver object
> 2016-10-26 17:10:41 | razer.screensaver              | WARNING  | Could not find screensaver DBus
> 2016-10-26 17:10:41 | razer.screensaver              | INFO     | Initialising DBus screensaver object
> 2016-10-26 17:10:41 | razer.screensaver              | WARNING  | Could not find screensaver DBus
> 2016-10-26 17:10:41 | razer.screensaver              | INFO     | Initialising DBus screensaver object
> 2016-10-26 17:10:41 | razer.screensaver              | WARNING  | Could not find screensaver DBus
> 2016-10-26 17:10:41 | razer.screensaver              | WARNING  | Giving up on screensaver
> 2016-10-27 14:19:14 | razer                          | INFO     | Initialising Daemon (v1.0.17). Pid: 17998
> 2016-10-27 14:19:14 | razer.screensaver              | INFO     | Initialising DBus Screensaver Thread
> 2016-10-27 14:19:16 | razer.screensaver              | INFO     | Initialising DBus screensaver object
> 2016-10-27 14:19:16 | razer.screensaver              | WARNING  | Could not find screensaver DBus
> 2016-10-27 14:19:16 | razer.screensaver              | INFO     | Initialising DBus screensaver object
> 2016-10-27 14:19:16 | razer.screensaver              | WARNING  | Could not find screensaver DBus
> 2016-10-27 14:19:16 | razer.screensaver              | INFO     | Initialising DBus screensaver object
> 2016-10-27 14:19:16 | razer.screensaver              | WARNING  | Could not find screensaver DBus
> 2016-10-27 14:19:16 | razer.screensaver              | WARNING  | Giving up on screensaver
> 2016-10-27 14:49:56 | razer                          | INFO     | Initialising Daemon (v1.0.17). Pid: 6018
> 2016-10-27 14:49:56 | razer.screensaver              | INFO     | Initialising DBus Screensaver Thread
> 2016-10-27 14:49:58 | razer.screensaver              | INFO     | Initialising DBus screensaver object
> 2016-10-27 14:49:58 | razer.screensaver              | WARNING  | Could not find screensaver DBus
> 2016-10-27 14:49:58 | razer.screensaver              | INFO     | Initialising DBus screensaver object
> 2016-10-27 14:49:58 | razer.screensaver              | WARNING  | Could not find screensaver DBus
> 2016-10-27 14:49:58 | razer.screensaver              | INFO     | Initialising DBus screensaver object
> 2016-10-27 14:49:58 | razer.screensaver              | WARNING  | Could not find screensaver DBus
> 2016-10-27 14:49:58 | razer.screensaver              | WARNING  | Giving up on screensaver

Thanks in advance!

### PR DESCRIPTION
**Pull request by GovanifY**
Partly fix #69 , auto-detect python folder instead of hardcoding it

### CODE REVIEW

**Comment by lah7** [comment]
It's also possible to detect the Python path by extracting it like this:

```
$(python3 -c "import sys; print(sys.path[-1])")
```

On Ubuntu, this outputs `/usr/lib/python3/dist-packages`. With the command in this PR, it outputs `/usr/local/lib/python3.5/dist-packages`.

**Comment by GovanifY** [comment]
True enough, outputs the same to my Gentoo so did not bothered. Will change to it

**Comment by terricain** [comment]
Can you change it from backticks to `$(shell ...)` :smile: I'd to it but cba to pull down code and change

**Comment by terricain** [comment]
Purely for consistencies sake as the rest of things are `$(shell ...)`

**Comment by GovanifY** [comment]
Sure! I'll be back in a hour at most, will do as quick as I'm back!

**Comment by GovanifY** [comment]
Just pushed! Feel free to merge ;)

**Comment by terricain** [comment]
:-)

**Pull request merged**
