### PR TITLE
Feature: Add support for Razer Naga V2 Pro (Wired + Wireless)

### LINKED ISSUE #1952: Support for Razer Naga V2 Pro
### Device Info

* Name: Razer Naga V2 Pro
* Product Number: RZ01-0440100
* Model Number: RZ01-0440

### Device Information
```
Bus 001 Device 006: ID 1532:00a8 Razer USA, Ltd Razer Naga V2 Pro
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x00a8 
  bcdDevice            1.00
  iManufacturer           1 Razer
  iProduct                2 Razer Naga V2 Pro
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     100
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     314
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1

```

```
total 0
drwxr-xr-x 2 root root 260 Nov 16 19:23 .
drwxr-xr-x 4 root root 700 Nov 16 19:23 ..
lrwxrwxrwx 1 root root   9 Nov 16 19:23 usb-GeneralPlus_USB_Audio_Device-event-if03 -> ../event3
lrwxrwxrwx 1 root root   9 Nov 16 19:23 usb-KBDfans_KBD75RGB-event-if02 -> ../event6
lrwxrwxrwx 1 root root   9 Nov 16 19:23 usb-KBDfans_KBD75RGB-event-kbd -> ../event4
lrwxrwxrwx 1 root root   9 Nov 16 19:23 usb-KBDfans_KBD75RGB-if02-event-kbd -> ../event7
lrwxrwxrwx 1 root root  10 Nov 16 19:23 usb-Razer_Razer_Naga_V2_Pro-event-if01 -> ../event11
lrwxrwxrwx 1 root root   9 Nov 16 19:23 usb-Razer_Razer_Naga_V2_Pro-event-mouse -> ../event8
lrwxrwxrwx 1 root root   9 Nov 16 19:23 usb-Razer_Razer_Naga_V2_Pro-if01-event-kbd -> ../event9
lrwxrwxrwx 1 root root  10 Nov 16 19:23 usb-Razer_Razer_Naga_V2_Pro-if01-event-mouse -> ../event10
lrwxrwxrwx 1 root root   9 Nov 16 19:23 usb-Razer_Razer_Naga_V2_Pro-if01-mouse -> ../mouse1
lrwxrwxrwx 1 root root  10 Nov 16 19:23 usb-Razer_Razer_Naga_V2_Pro-if02-event-kbd -> ../event12
lrwxrwxrwx 1 root root   9 Nov 16 19:23 usb-Razer_Razer_Naga_V2_Pro-mouse -> ../mouse0

```

```
001:006:002:DESCRIPTOR         1668650887.140778
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

001:006:001:DESCRIPTOR         1668650887.141873
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 0E 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0 05 01 09
 02 A1 01 85 0A 09 01 A1 00 05 09 19 01 29 06 15
 00 25 01 75 01 95 06 81 02 75 01 95 02 81 03 06
 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05 01
 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09 31
 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 C0 05 0C
 09 01 A1 01 85 02 19 00 2A 3C 02 15 00 26 3C 02
 95 01 75 10 81 00 75 08 95 0D 81 01 C0 05 01 09
 80 A1 01 85 03 19 81 29 83 15 00 25 01 75 01 95
 03 81 02 95 05 81 01 75 08 95 0E 81 01 C0 05 01
 09 00 A1 01 85 04 09 03 15 00 26 FF 00 35 00 46
 FF 00 75 08 95 0F 81 00 C0 05 01 09 00 A1 01 85
 05 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95
 0F 81 00 C0 05 01 09 00 A1 01 85 08 09 03 15 00
 26 FF 00 35 00 46 FF 00 75 08 95 0F 81 00 C0 05
 01 09 00 A1 01 85 09 09 03 15 00 26 FF 00 35 00
 46 FF 00 75 08 95 0F 81 00 C0

001:006:000:DESCRIPTOR         1668650887.143008
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 75 01 95 08 81 03 05 0C 0A 38 02 15 81 25 7F 75
 08 95 01 81 06 05 01 09 38 15 81 25 7F 75 08 95
 01 81 06 09 30 09 31 16 00 80 26 FF 7F 75 10 95
 02 81 06 C0 06 00 FF 09 02 15 00 25 01 75 08 95
 5A B1 01 C0

```

</details>

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>
image

image

image

image

image

image

### PR DESCRIPTION
**Pull request by Caedis**
Closes #1952

~~I have not tested the daemon as I prefer reading directly from sysfs (i just wanted the charging status and level)~~
Daemon + sysfs OK

- [x] `charge_level` and `charge_status` (data from wireless both show as 0 when charging, wired shows status/level)
- [x] `dpi`
- [x] `matrix_brightness`
- [ ] `matrix_*` (but brightness) 
- [x] `logo_led_brightness`
- [ ] `charge_effect` - Error: `Command not supported. status: 05 transaction_id.id: 1f remaining_packets: 00 protocol_type: 00 data_size: 01, command_class: 03, command_id.id: 10 Params: 01000000000000000000000000000000`
- [ ] `charge_color` - Error: `Command timed out. status: 04 transaction_id.id: ff remaining_packets: 00 protocol_type: 00 data_size: 01, command_class: 03, command_id.id: 10 Params: 01000000000000000000000000000000. Command not supported. status: 05 transaction_id.id: 1f remaining_packets: 00 protocol_type: 00 data_size: 05, command_class: 03, command_id.id: 01 Params: 00030000000000000000000000000000 .`
- [ ] `charge_low_threshold` - Writing does not change value. Example: "\x10" should be 10, but stays at 12
- [x] `device_idle_time` 
- [x] `device_type`
- [x] `device_serial`
- [ ] Macros
- [ ] Custom scroll wheel haptics (will require a lot of work)

Anyone else is free to make changes as I do not have much experience with C++ or Linux drivers.

### CODE REVIEW

**Comment by z3ntu** [comment]
> I have not tested the daemon as I prefer reading directly from sysfs

Please at least briefly install a UI like polychromatic and RazerGenie and click through the options to see if they work correctly. I don't want to include broken stuff here, otherwise people will complain ;)

**Comment by Caedis** [comment]
Can do

**Comment by Caedis** [comment]
Couldnt get polychromatic to detect the backend with the daemon running for some reason.

Was able to read and write everything i have above via the dbus
image

**Comment by Caedis** [comment]
~~Issue: Dbus handles wired and wireless versions as separate devices. Is that expected?~~

**Comment by z3ntu** [comment]
Wired and wireless versions being detected separately is expected, there's no concept to group them together in OpenRazer.

Also please check the CI failure and fix it.

**Comment by Caedis** [comment]
Neat, it even checks the README.

**Comment by Caedis** [comment]
Still need to inspect the traffic for non-static colors, effects, charge color, and charge effect.

**Comment by Ruscios** [comment]
I attempted to build and install this version, and while successful, it did not recognize my Razer Naga V2 Pro. Mine shows up as 1532:00A4.

**Comment by Caedis** [comment]
@Ruscios Are you using the dock?

**Comment by Caedis** [comment]
and can you please post a screenshot of `lsusb`

**Comment by Ruscios** [comment]
I thought that might be the case, yes I am using the dock. Do we know if the dock gives a unique USB identifier by what mouse it acts as the connection for, or if it is always 00A4?

`Bus 008 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub`
`Bus 007 Device 002: ID 26ce:01a2 ASRock LED Controller`
`Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`
`Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub`
`Bus 005 Device 002: ID 1532:0555 Razer USA, Ltd Razer BlackShark V2 Pro 2.4`
`Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`
`Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub`
`Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`
`Bus 002 Device 003: ID 0781:55a3 SanDisk Corp.  SanDisk 3.2Gen1`
`Bus 002 Device 002: ID 0781:55ab SanDisk Corp.  SanDisk 3.2Gen1`
`Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub`
`Bus 001 Device 004: ID 3434:0150 Keychron Keychron Q5`
`Bus 001 Device 007: ID 1532:00a4 Razer USA, Ltd Razer Mouse Dock Pro`
`Bus 001 Device 002: ID 3434:0131 Keychron Keychron Q0 Plus`
`Bus 001 Device 005: ID 8087:0032 Intel Corp. AX210 Bluetooth`
`Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`

I'll try un-binding the mouse from the dock in Windows and then trying again with the dongle.

**Comment by Caedis** [comment]
I believe so since the dock takes the place of the usb dongle and has its own endpoints

Do not know how it handles different mice connected to it

**Comment by Ruscios** [comment]
Okay, tested with original dongle and PolyChromatic is able to configure the mouse. Only lighting effect I had trouble with was "Wave." Could be that what I saw was the intended behavior, but it seemed like the light was just doing some sort of strobe color rotation. Other than that, fully functional.

**Comment by Caedis** [comment]
Thanks for checking!

**Comment by z3ntu** [comment]
What's the status on this? Any progress on fixing the open issues?

**Comment by Caedis** [comment]
@z3ntu I am at my limit for c++ knowledge as most of it was copy paste from the v1 naga pro.

It already has all the features I was wanting (really only just reading battery status) and I have been running it since with no issues.

**Comment by DjSapsan** [comment]
hello. Just bought the Naga V2 Pro (wireless) and followed all the instructions. Also the keyboard Razer Ornata V3.
Currently nothing show up in the RazerGenie GUI, but I wanna start with the mouse. Also old profiles seems to be broken.
Here is what the daemon logs show when I re-connect it:
```
2023-11-03 22:15:17 | razer                          | DEBUG    | Device event [unbind]: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:05:00.1/usb1/1-6/1-6.2/1-6.2:1.0/0003:1532:00A8.000B
2023-11-03 22:15:17 | razer                          | DEBUG    | Device event [remove]: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:05:00.1/usb1/1-6/1-6.2/1-6.2:1.0/0003:1532:00A8.000B
2023-11-03 22:15:17 | razer                          | DEBUG    | Device event [unbind]: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:05:00.1/usb1/1-6/1-6.2/1-6.2:1.1/0003:1532:00A8.000C
2023-11-03 22:15:17 | razer                          | DEBUG    | Device event [remove]: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:05:00.1/usb1/1-6/1-6.2/1-6.2:1.1/0003:1532:00A8.000C
2023-11-03 22:15:17 | razer                          | DEBUG    | Device event [unbind]: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:05:00.1/usb1/1-6/1-6.2/1-6.2:1.2/0003:1532:00A8.000D
2023-11-03 22:15:17 | razer                          | DEBUG    | Device event [remove]: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:05:00.1/usb1/1-6/1-6.2/1-6.2:1.2/0003:1532:00A8.000D
2023-11-03 22:15:29 | razer                          | DEBUG    | Device event [add]: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:05:00.1/usb1/1-6/1-6.3/1-6.3:1.0/0003:1532:00A8.0011
2023-11-03 22:15:29 | razer                          | DEBUG    | Device event [add]: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:05:00.1/usb1/1-6/1-6.3/1-6.3:1.1/0003:1532:00A8.0012
2023-11-03 22:15:29 | razer                          | DEBUG    | Device event [add]: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:05:00.1/usb1/1-6/1-6.3/1-6.3:1.2/0003:1532:00A8.0013
2023-11-03 22:15:29 | razer                          | DEBUG    | Device event [bind]: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:05:00.1/usb1/1-6/1-6.3/1-6.3:1.2/0003:1532:00A8.0013
2023-11-03 22:15:29 | razer                          | DEBUG    | Device event [bind]: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:05:00.1/usb1/1-6/1-6.3/1-6.3:1.1/0003:1532:00A8.0012
2023-11-03 22:15:29 | razer                          | DEBUG    | Device event [bind]: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:05:00.1/usb1/1-6/1-6.3/1-6.3:1.0/0003:1532:00A8.0011

```

**Comment by DjSapsan** [comment]
hmm should I build from this src for myself now?

**Comment by z3ntu** [comment]
@DjSapsan Neither device is currently supported, for Ornata V3 it's likely #2053 (check `lsusb | grep 1532`) that it matches the device there. 

If you'd build from this pull request from source (https://github.com/openrazer/openrazer/wiki/Building-a-package) then at least the Naga V2 Pro should work to some extent - you can read more about the state of this pull request in earlier comments.

**Comment by DjSapsan** [comment]
@z3ntu , I'm trying to build it, but everything appears to be configured for a different OS. 
First, "/openrazer-driver-dkms.install/" targets files in the wrong location. I found files via search and fixed the path. But then I got a lot of errors with permissions/files not found/attr not found/file name too long etc.
I have Kubuntu 22.04. How can I reconfigure the build for my system?

**Comment by z3ntu** [comment]
Without you giving me more details, I can't help much. Maybe send the built .deb packages and build log? But it might be easier if you join the community chat to not spam this PR too much https://github.com/openrazer/openrazer/wiki/Community-chat

**Comment by gimmemabrewski** [comment]
I built from this repo and have the device (Naga Pro v2) showing up. The lighting options work. Did anyone figure out how to bind the mouse keys? I'm assuming this is something that has to be done at the kernel level? xinput does not detect the extra button input. Thanks

**Comment by z3ntu** [comment]
@gimmemabrewski Good that the lighting works fine. Do you also see the issues mentioned in the top-most post?

For the extra mouse keys, if they don't show up in e.g. `libinput debug-events` or with xinput then I'm assuming that either the device is currently in "device mode" where the mouse just doesn't emit the events; or it's in "driver mode" where the openrazer kernel driver would need some additions to handle the buttons correctly. As far as I can tell, we currently don't switch mice to driver mode at all in the daemon.

**Comment by gimmemabrewski** [comment]
> @gimmemabrewski Good that the lighting works fine. Do you also see the issues mentioned in the top-most post?
> 
> For the extra mouse keys, if they don't show up in e.g. `libinput debug-events` or with xinput then I'm assuming that either the device is currently in "device mode" where the mouse just doesn't emit the events; or it's in "driver mode" where the openrazer kernel driver would need some additions to handle the buttons correctly. As far as I can tell, we currently don't switch mice to driver mode at all in the daemon.

I actually haven't noticed any issues. I can look into some of this stuff after work if it could help. I used a VM to set the mouse up in windows and since then everything seems to work, although I haven't tried macros. I just set my buttons to keyboard shortcuts and use linux options (kde in my case) from there. As far as the lighting goes, I turn that off anyway but the little I messed with it seemed to work.

**Comment by ro-kue** [comment]
Whats the status on this? I might take over if @Caedis has no interest in taking this further

**Comment by Aemilivs** [comment]
@ro-kue  there is no reply for 4 days, I guess it's up for grabs
Please let me know if you need any assistance, I would love to finally get some sweet support for the v2 pro on my steamdeck 😀

**Comment by ro-kue** [comment]
@Aemilivs Currently stuck on another project but I'll try to get some captures on Windows and figure out how much work that is actually going to be. Can't promise anything though.

**Comment by Caedis** [comment]
Sorry. Yeah, someone else is free to take over. I have since moved on from the naga pro v2

**Comment by z3ntu** [comment]
For anyone wanting to work on this, please take the changes from this PR, work on it and open a new pull request with it once you have something. Thanks!

**Comment by z3ntu** [comment]
Any update on this?

**Comment by AnarQuay** [comment]
no clue... however would it be possible to adapt the naga v2 hyperspeed libraries to work for the naga v2 pro? especially as they have very similar hardware

**Comment by z3ntu** [comment]
All devices are quite similar to that extent, so sure but I believe this PR already covers a good chunk of what's required but I don't know the current status of this.

**Comment by marcelpallares** [comment]
I'm also interested in this... I just bought the mice without realising MacOS is not supported by Synapse software 🥹

**Comment by z3ntu** [comment]
@marcelpallares OpenRazer doesn't support macOS, so either install Linux or use something else.

**Comment by marcelpallares** [comment]
I know it doesn't, I was planning to use [razer-macos](https://github.com/stickoking/razer-macos) once the drivers are figured out.

**Comment by pjwriteserrors** [comment]
I'm trying to build from this PR but I can't seem to get this working.  No matter what way I build neither polychromatic nor razergenie is recognizing my mouse. the polychromatic troubleshoot says that everything is okay except that the mouse isn't being supported so the daemon is running. Mouse shows up as 1532:00a8 with dongle in lsusb.
I am on an Arch VM, does anyone have an idea what I'm doing wrong here or can give some guidance?

(i can provide more info on things if needed)

**Comment by AnarQuay** [comment]
I could never figure it out either... (fedora)

**Comment by pjwriteserrors** [comment]
If you are using a VM, make sure to pass through the mouse BEFORE you restart the daemon... everything works fine in this PR then

**Comment by z3ntu** [comment]
Closing in favor of #2348. Thanks for your contributions!

**Pull request closed without merging**
