### PR TITLE
Move pylib capabilities to generic class & fix incompatibility with BlackWidow V3 Mini Hyperspeed

### PR DESCRIPTION
**Pull request by z3ntu**
Fixes issue reported in https://github.com/openrazer/openrazer/pull/1617#issuecomment-949622314

@nachitox @IvanVojtko Please test this, especially if the "is the device currently charging" status is correct.

### CODE REVIEW

**Comment by nachitox** [comment]
@z3ntu, yes, no problem.
Can you tell me how? :)

**Comment by z3ntu** [comment]
@nachitox Does this help? https://github.com/openrazer/openrazer/wiki/Building-a-package

**Comment by nachitox** [comment]
I built it and ran:

> python3 -c "import openrazer.client; a = openrazer.client.DeviceManager(); print(a.devices[0].name, a.devices[0].has('battery'))"
Razer BlackWidow V3 Mini Hyperspeed (Wireless) True

which is better than before.

Polychromatic throws an error when trying to access the device so I would say something broke: Screenshot from 2021-10-22 16-28-26

Not sure how can I test it.

**Comment by z3ntu** [comment]
Can you expand the details? Also make sure you have rebuilt the kernel modules and rebooted to load the new ones.

**Comment by nachitox** [comment]
I restarted and it worked. The battery percentage is shown.
Screenshot from 2021-10-22 18-05-29

When I connect the cable, a new device is listed but is not recognized.
Screenshot from 2021-10-22 18-08-28

Not sure how to check "the device currently charging"

**Comment by z3ntu** [comment]
When your keyboard is connected wirelessly to your PC (the dongle or Bluetooth) then the device should show up as not charging (as it does in the screen) and when you plug it into e.g. a USB charger or power bank (not your PC) then it should show up as charging (polychromatic then has a lightning bolt in the battery icon iirc).

**Comment by nachitox** [comment]
Screenshot from 2021-10-22 18-33-47
Yes, looks charging when I connect it to a power outlet (not a USB on my PC)

**Comment by z3ntu** [comment]
Perfect, thanks!

**Pull request merged**
