### PR TITLE
Add support for Huntsman Tournament Edition

### PR DESCRIPTION
**Pull request by mnewswanger**
Add support for Razer Huntsman Tournement Edition (TE).  Implements #958

I don't know the link for the image for the doc, so it currently has the (incorrect) Razer Huntsman Elite image; if you someone can provide that, I can update (or can be modified when merged by maintainers).

### CODE REVIEW

**Comment by lah7** [comment]
Added the image for you - https://support.razer.com is a good place for URLs.

**Comment by mnewswanger** [comment]
I've been running this branch for a bit now, and everything seems to be working as intended (using polychromatic to control colors) except that the `fn` button isn't working for the media controls (play / pause / stop or volume), macro, game mode, or brightness.   When running the drivers, `fn` + `F6` (play/pause) is received as only a `F6` keypress.  Any ideas on where to look based on that?

**Comment by mnewswanger** [comment]
I saw #873 which looks similar for another 2019 keyboard, but pulling those changes into the driver doesn't seem to have the desired effect for this model either.

**Comment by z3ntu** [comment]
@mnewswanger Can you add debug prints like in https://github.com/openrazer/openrazer/pull/873#issuecomment-577804267 for your device? If it's a similar issue to what's fixed there, we should find out that way :)

**Comment by jfriar** [comment]
This fix, combined with #1049 has gotten (what seems to be) full support for my Huntsman TE (I've patched the 2.7.0 release) - the FN "alternate functions" seem to work now (I verified the volume control and the super key enable/disable function).

I should note - I'm running kernel 4.19.105

**Comment by z3ntu** [comment]
@jfriar Thanks for testing, much appreciated!

**Comment by mnewswanger** [comment]
Synced up with master, and looks like the driver's working :100: now - I'm able to get the macro functionality that was previously not working (same as @jfriar).  This one should be good to merge now.

**Review by z3ntu — APPROVED** [review]
LGTM, thank you very much!

**Pull request merged**
