### PR TITLE
[WIP] Add Razer Naga Pro Wireless Support

### LINKED ISSUE #1247: Support for Razer Naga Pro
### Device Info

* Name: Razer Naga Pro
* Product Number: RZ01-03420100
* Model Number: RZ01-0342

### Device Information

```
Bus 001 Device 011: ID 1532:0090 Razer USA, Ltd Razer Naga Pro
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0090 
  bcdDevice            1.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 3 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0086
    bNumInterfaces          5
    bConfigurationValue     1
    iConfiguration          4 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     179
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        4
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     325
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     348
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
```

```
lrwxrwxrwx 1 root root   10 Sep  9 12:36 usb-RAZER_Razer_Mouse_Dock-event-if01 -> ../event30
lrwxrwxrwx 1 root root   10 Sep  9 12:36 usb-RAZER_Razer_Mouse_Dock-event-mouse -> ../event26
lrwxrwxrwx 1 root root   10 Sep  9 12:36 usb-RAZER_Razer_Mouse_Dock-if01-event-kbd -> ../event27
lrwxrwxrwx 1 root root   10 Sep  9 12:36 usb-RAZER_Razer_Mouse_Dock-if02-event-kbd -> ../event31
lrwxrwxrwx 1 root root    9 Sep  9 12:36 usb-RAZER_Razer_Mouse_Dock-mouse -> ../mouse0
lrwxrwxrwx 1 root root   11 Sep  9 12:36 usb-Razer_Razer_Naga_Pro_000000000000-event-if01 -> ../event263
lrwxrwxrwx 1 root root   11 Sep  9 12:36 usb-Razer_Razer_Naga_Pro_000000000000-event-if03 -> ../event268
lrwxrwxrwx 1 root root   11 Sep  9 12:36 usb-Razer_Razer_Naga_Pro_000000000000-event-mouse -> ../event257
lrwxrwxrwx 1 root root   11 Sep  9 12:36 usb-Razer_Razer_Naga_Pro_000000000000-if01-event-kbd -> ../event258
lrwxrwxrwx 1 root root   11 Sep  9 12:36 usb-Razer_Razer_Naga_Pro_000000000000-if02-event-kbd -> ../event266
lrwxrwxrwx 1 root root    9 Sep  9 12:36 usb-Razer_Razer_Naga_Pro_000000000000-mouse -> ../mouse1
```

### PR DESCRIPTION
**Pull request by AliceGrey**
Fixes #1247 (once completed)

### CODE REVIEW

**Comment by prosrane** [comment]
Thank you AliceGrey!!!

**Comment by AliceGrey** [comment]
Should work now if someone with the mouse can give it a try

**Comment by geodox** [comment]
Will test when I get home, thanks Alice 👌

**Comment by AliceGrey** [comment]
Closing and combining with  #1692

**Pull request closed without merging**
