### PR TITLE
Delete excessive newlines

### PR DESCRIPTION
**Pull request by amyipdev**
Somehow there's this excess of newlines here. There's no need for them...

### CODE REVIEW

**Comment by amyipdev** [comment]
Does Alpine just fail randomly? I've been looking over other PRs and seen that Alpine failures are quite frequent but almost always accompanied with Ubuntu successes.

**Comment by z3ntu** [comment]
The Ubuntu CI is just a very simple build job that just builds the driver code on an old Ubuntu base to ensure it's still compatible. The Alpine CI does the majority of the validation so that's why that's the one that fails most often.

Regarding this specific failure I've fixed it in git master so as soon rebase your branch it should succeed.

**Comment by amyipdev** [comment]
@z3ntu Rebase completed and all checks are successful, should be okay to merge now.

**Comment by amyipdev** [comment]
@z3ntu just checking in on this MR again.

**Comment by z3ntu** [comment]
You didn't actually rebase (see https://git-rebase.io/ for how to do that), but I also added some more newlines I found to the commit and rebased it for you.

Thanks!

**Pull request merged**
