### PR TITLE
WIP: Add initial support for Razer DeathAdder V2

### PR DESCRIPTION
**Pull request by 0x726f62**
WIP

- I based changes on previous PR for Razer DeathAdder Essential
- the links in DEVICE_IMAGE and RAZER_URLS need to be updated

- Currently when i try to test changes i get follwoing error
```
● openrazer-daemon.service - Daemon to manage razer devices in userspace
     Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Mon 2020-02-10 21:55:48 CET; 55ms ago
       Docs: man:openrazer-daemon(8)
    Process: 17659 ExecStart=/usr/bin/openrazer-daemon -Fv (code=exited, status=0/SUCCESS)
   Main PID: 17659 (code=exited, status=0/SUCCESS)

Feb 10 21:55:47 arch-main openrazer-daemon[17659]:     DBusService.__init__(self, self.BUS_PATH, object_path)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:   File "/usr/lib/python3.8/site-packages/openrazer_daemon/dbus_services/service.py", line 87, in __init__
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:     super(DBusService, self).__init__(bus_object, object_path)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:   File "/usr/lib/python3.8/site-packages/dbus/service.py", line 489, in __init__
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:     self.add_to_connection(conn, object_path)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:   File "/usr/lib/python3.8/site-packages/dbus/service.py", line 578, in add_to_connection
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:     connection._register_object_path(path, self._message_cb,
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: KeyError: "Can't register the object-path handler for '/org/razer/device/PM1951H14416221': there is already a handler"
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: Stopping daemon.
Feb 10 21:55:48 arch-main systemd[779]: openrazer-daemon.service: Succeeded.
```
logs
```
Feb 10 21:55:47 arch-main dbus-daemon[795]: [session uid=1000 pid=795] Activating via systemd: service name='org.razer' unit='openrazer-daemon.service' requested by ':1.44' (uid=1000 pid=17655 comm="razergenie ")
Feb 10 21:55:47 arch-main systemd[779]: Starting Daemon to manage razer devices in userspace...
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: Starting daemon.
Feb 10 21:55:47 arch-main dbus-daemon[795]: [session uid=1000 pid=795] Successfully activated service 'org.razer'
Feb 10 21:55:47 arch-main systemd[779]: Started Daemon to manage razer devices in userspace.
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | INFO     | Initialising Daemon (v2.7.0). Pid: 17659
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus1800 ------------------------ (1532:0020)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus2000 ------------------------ (1532:005E)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerAbyssusV2 -------------------------- (1532:005B)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerAnansi ----------------------------- (1532:010F)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2019 --------------------- (1532:0241)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChroma ------------------- (1532:0203)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaOverwatch ---------- (1532:0211)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaTournamentEdition -- (1532:0209)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaV2 ----------------- (1532:0221)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowElite -------------------- (1532:0228)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowLite --------------------- (1532:0235)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowStealth ------------------ (1532:011B)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowStealthEdition ----------- (1532:010E)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2012 ------------- (1532:010D)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2013 ------------- (1532:011A)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2016 ------------- (1532:0214)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChroma ------------------ (1532:0216)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXTournamentEditionChroma - (1532:021A)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXUltimate ---------------- (1532:0217)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlade2018 -------------------------- (1532:0233)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlade2018Base ---------------------- (1532:023B)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlade2018Mercury ------------------- (1532:0240)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlade2019Adv ----------------------- (1532:023A)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlade2019Base ---------------------- (1532:0246)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBlade2019StudioEdition ------------- (1532:024D)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBladeLate2016 ---------------------- (1532:0224)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBladeMid2019Mercury ---------------- (1532:0245)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2017 ----------------------- (1532:0225)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2017FullHD ----------------- (1532:022F)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBladeProLate2016 ------------------- (1532:0210)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBladeQHD --------------------------- (1532:020F)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth ----------------------- (1532:0205)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth2019 ------------------- (1532:0239)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2016 --------------- (1532:0220)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2017 --------------- (1532:0232)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2019 --------------- (1532:024A)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthMid2017 ---------------- (1532:022D)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerChromaMugHolder -------------------- (1532:0F07)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerCore ------------------------------- (1532:0215)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerCynosaChroma ----------------------- (1532:022A)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdder1800 --------------------- (1532:0038)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdder2013 --------------------- (1532:0037)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdder3500 --------------------- (1532:0054)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdder3_5G --------------------- (1532:0016)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderChroma ------------------- (1532:0043)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderElite -------------------- (1532:005C)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderEssential ---------------- (1532:006E)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderV2 ----------------------- (1532:0084)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerChroma ----------------- (1532:0204)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerExpert ----------------- (1532:0202)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerDiamondbackChroma ------------------ (1532:004C)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerFirefly ---------------------------- (1532:0C00)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerFirefly_Hyperflux ------------------ (1532:0068)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerGoliathus -------------------------- (1532:0C01)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerGoliathusExtended ------------------ (1532:0C02)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerHuntsman --------------------------- (1532:0227)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerHuntsmanElite ---------------------- (1532:0226)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerImperator -------------------------- (1532:002F)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerKraken71 --------------------------- (1532:0501)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerKraken71Alternate ------------------ (1532:0506)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerKraken71Chroma --------------------- (1532:0504)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerKraken71V2 ------------------------- (1532:0510)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerLanceheadTE ------------------------ (1532:0060)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wired --------------------- (1532:0024)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wireless ------------------ (1532:0025)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWired ------------------- (1532:0044)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWireless ---------------- (1532:0045)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerMambaTE ---------------------------- (1532:0046)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerNaga2012 --------------------------- (1532:002E)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerNaga2014 --------------------------- (1532:0040)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerNagaChroma ------------------------- (1532:0053)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerNagaHex ---------------------------- (1532:0041)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexRed ------------------------- (1532:0036)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexV2 -------------------------- (1532:0050)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerNagaTrinity ------------------------ (1532:0067)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerNostromo --------------------------- (1532:0111)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaver -------------------------- (1532:0113)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaverChroma -------------------- (1532:0207)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerOrnata ----------------------------- (1532:021F)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerOrnataChroma ----------------------- (1532:021E)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2011 ------------------------- (1532:0013)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2013 ------------------------- (1532:0039)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerOrochiWired ------------------------ (1532:0048)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerOuroboros -------------------------- (1532:0032)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerTaipan ----------------------------- (1532:0034)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerTartarus --------------------------- (1532:0201)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | DEBUG    | Loaded device specification: RazerTartarusChroma --------------------- (1532:0208)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | INFO     | Found device.0: 0003:1532:0084.0002
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | INFO     | Initialising device.0 RazerDeathAdderV2
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.resumeDevice method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.suspendDevice method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceMode method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.getSerial method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasDedicatedMacroKeys method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.setDeviceMode method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDriverVersion method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.getRazerUrls method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.getVidPid method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.getFirmware method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.getMatrixDimensions method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasMatrix method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceName method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceType method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.dpi.maxDPI method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.dpi.getDPI method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.dpi.setDPI method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.getPollRate method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.misc.setPollRate method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.getLogoBrightness method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoBrightness method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoStatic method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoNone method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoBreathSingle method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.getScrollBrightness method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollBrightness method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollStatic method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollNone method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollBreathSingle method to DBus
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer                          | INFO     | Found device.1: 0003:1532:0084.0005
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: 2020-02-10 21:55:47 | razer.device1                  | INFO     | Initialising device.1 RazerDeathAdderV2
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: Traceback (most recent call last):
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:   File "/usr/lib/python3.8/site-packages/daemonize.py", line 248, in start
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:     self.action(*privileged_action_result)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:   File "/usr/bin/openrazer-daemon", line 121, in run_daemon
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:     daemon = RazerDaemon(verbose=args.verbose,
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:   File "/usr/lib/python3.8/site-packages/openrazer_daemon/daemon.py", line 106, in __init__
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:     self._load_devices(first_run=True)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:   File "/usr/lib/python3.8/site-packages/openrazer_daemon/daemon.py", line 400, in _load_devices
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:     razer_device = device_class(sys_path, device_number, self._config, testing=self._test_dir is not None, additional_interfaces=sorted(additional_interfaces))
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:   File "/usr/lib/python3.8/site-packages/openrazer_daemon/hardware/device_base.py", line 445, in __init__
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:     super().__init__(device_path, device_number, config, testing, additional_interfaces, additional_methods)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:   File "/usr/lib/python3.8/site-packages/openrazer_daemon/hardware/device_base.py", line 88, in __init__
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:     DBusService.__init__(self, self.BUS_PATH, object_path)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:   File "/usr/lib/python3.8/site-packages/openrazer_daemon/dbus_services/service.py", line 87, in __init__
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:     super(DBusService, self).__init__(bus_object, object_path)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:   File "/usr/lib/python3.8/site-packages/dbus/service.py", line 489, in __init__
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:     self.add_to_connection(conn, object_path)
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:   File "/usr/lib/python3.8/site-packages/dbus/service.py", line 578, in add_to_connection
Feb 10 21:55:47 arch-main openrazer-daemon[17659]:     connection._register_object_path(path, self._message_cb,
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: KeyError: "Can't register the object-path handler for '/org/razer/device/PM1951H14416221': there is already a handler"
Feb 10 21:55:47 arch-main openrazer-daemon[17659]: Stopping daemon.
Feb 10 21:55:48 arch-main systemd[779]: openrazer-daemon.service: Succeeded.
```
As you can see the mouse is initialized twice - as razer.device0 and razer.device1
Could anybody help me what's the issue here? Thanks

### CODE REVIEW

**Comment by z3ntu** [comment]
@Pr0b That's weird. Do you have multiple Razer devices connected to your PC? It looks like the daemon is trying to register your mouse twice, so it's using the same serial number twice as well. Are you sure you tested with the files in this PR and not with an older version?

**Comment by 0x726f62** [comment]
> Do you have multiple Razer devices connected to your PC?

No, just 1 mouse - Razer DeathAdder V2

>Are you sure you tested with the files in this PR and not with an older version?

I thinks so. During daemon init you can see in logs  
```
Loaded device specification: RazerDeathAdderV2 ----------------------- (1532:0084)
```
which i added in this PR.

The mouse is listed twice in the system 

ls -la /sys/bus/hid/drivers/razermouse/0*
```
lrwxrwxrwx 1 root root 0 Feb 24 16:05 /sys/bus/hid/drivers/razermouse/0003:1532:0084.0002 -> ../../../../devices/pci0000:00/0000:00:14.0/usb1/1-13/1-13:1.0/0003:1532:0084.0002
lrwxrwxrwx 1 root root 0 Feb 24 16:05 /sys/bus/hid/drivers/razermouse/0003:1532:0084.0003 -> ../../../../devices/pci0000:00/0000:00:14.0/usb1/1-13/1-13:1.1/0003:1532:0084.0003
lrwxrwxrwx 1 root root 0 Feb 24 16:05 /sys/bus/hid/drivers/razermouse/0003:1532:0084.0004 -> ../../../../devices/pci0000:00/0000:00:14.0/usb1/1-13/1-13:1.2/0003:1532:0084.0004
lrwxrwxrwx 1 root root 0 Feb 24 16:05 /sys/bus/hid/drivers/razermouse/0003:1532:0084.0005 -> ../../../../devices/pci0000:00/0000:00:14.0/usb1/1-13/1-13:1.3/0003:1532:0084.0005
```

cat /sys/bus/hid/drivers/razermouse/0*/device_serial 
```
PM1951H14416221
PM1951H14416221
```
That's from 0002 and 0005 - which are identical

0003 and 0004 are also identical but contains 'less stuff'

I was also looking at the fake drivers directory (pylib/openrazer/_fake_driver). Maybe in this case i 
need to add a file there.

Like that
```
[device]
dir_name = 0003:1532:0084.0001
name = Razer DeathAdder V2
event = Razer_DeathAdder_V2-if01-event-kbd
        Razer_DeathAdder_V2-if02-event-kbd
files = r,version,1.0.0
        r,device_type,%(name)s
        r,firmware_version,v1.0
        r,device_serial,XX0000000014
        rw,logo_led_brightness,0
        rw,scroll_led_brightness,0
        w,logo_matrix_effect_spectrum
        w,logo_matrix_effect_reactive
        w,logo_matrix_effect_breath
        w,logo_matrix_effect_static
        w,logo_matrix_effect_none
        w,scroll_matrix_effect_spectrum
        w,scroll_matrix_effect_reactive
        w,scroll_matrix_effect_breath
        w,scroll_matrix_effect_static
        w,scroll_matrix_effect_none
        w,matrix_effect_custom
        w,matrix_custom_frame
        rw,poll_rate,500
        rw,dpi,800:800
```

**Comment by z3ntu** [comment]
No the fake driver doesn't matter here.

It looks like your device has 4 usb interfaces instead of the usual 3 (according to the lsusb output at https://github.com/openrazer/openrazer/issues/1012) - and two of that are `bInterfaceProtocol      2 Mouse` which is the interface openrazer uses to communicate with the device (`    if(dev->usb_interface_protocol == USB_INTERFACE_PROTOCOL_MOUSE) {` in `razer_mouse_probe`)

@terrycain any idea?

**Comment by redlet** [comment]
I have a V2 but won't use it until I can set DPI -- what is the status of this?

**Comment by lsiudut** [comment]
Hey, I just made my v2 work. I'll put up a PR later today, need to finish few things, but all the things seems to work.

**Comment by 0x726f62** [comment]
closed in favour of #1093

**Pull request closed without merging**
