### PR TITLE
Add support for Ornata V3 Tenkeyless (02A3)

### LINKED ISSUE #2140: Support for Razer Ornata V3 Tenkeyless
### Device Info

* Name: Razer Ornata V3 TKL
* Product Number: RZ03-04880200-R3U1
* Model Number: RZ03-0488

### Device Information
```
Bus 001 Device 013: ID 1532:02a3 Razer USA, Ltd Razer Ornata V3 Tenkeyless
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x02a3 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Ornata V3 Tenkeyless
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     179
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0016  1x 22 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)
```
```
total 0
drwxr-xr-x 2 root root 420 Oct  1 21:11 .
drwxr-xr-x 4 root root 840 Oct  1 21:11 ..
lrwxrwxrwx 1 root root  10 Oct  1 21:11 usb-046d_Logitech_Webcam_C930e_D7153C0E-event-if00 -> ../event22
lrwxrwxrwx 1 root root   9 Oct  1 21:11 usb-Azurewave_Integrated_Camera_200901010001-event-if00 -> ../event3
lrwxrwxrwx 1 root root   9 Oct  1 21:11 usb-Azurewave_Integrated_Camera_200901010001-event-if02 -> ../event5
lrwxrwxrwx 1 root root   9 Oct  1 21:11 usb-Logitech_USB_Receiver-if02-event-mouse -> ../event9
lrwxrwxrwx 1 root root   9 Oct  1 21:11 usb-Logitech_USB_Receiver-if02-mouse -> ../mouse3
lrwxrwxrwx 1 root root  10 Oct  1 21:11 usb-Razer_Razer_Blade-event-if01 -> ../event19
lrwxrwxrwx 1 root root  10 Oct  1 21:11 usb-Razer_Razer_Blade-event-kbd -> ../event15
lrwxrwxrwx 1 root root  10 Oct  1 21:11 usb-Razer_Razer_Blade-if01-event-kbd -> ../event18
lrwxrwxrwx 1 root root  10 Oct  1 21:11 usb-Razer_Razer_Blade-if02-event-mouse -> ../event20
lrwxrwxrwx 1 root root   9 Oct  1 21:11 usb-Razer_Razer_Blade-if02-mouse -> ../mouse5
lrwxrwxrwx 1 root root   9 Oct  1 21:11 usb-Razer_Razer_Laptop_Stand_Chroma-event-mouse -> ../event4
lrwxrwxrwx 1 root root  10 Oct  1 21:11 usb-Razer_Razer_Laptop_Stand_Chroma-if01-event-kbd -> ../event25
lrwxrwxrwx 1 root root  10 Oct  1 21:11 usb-Razer_Razer_Laptop_Stand_Chroma-if02-event-kbd -> ../event23
lrwxrwxrwx 1 root root   9 Oct  1 21:11 usb-Razer_Razer_Laptop_Stand_Chroma-mouse -> ../mouse0
lrwxrwxrwx 1 root root  10 Oct  1 21:11 usb-Razer_Razer_Ornata_V3_Tenkeyless-event-if01 -> ../event16
lrwxrwxrwx 1 root root  10 Oct  1 21:11 usb-Razer_Razer_Ornata_V3_Tenkeyless-event-kbd -> ../event12
lrwxrwxrwx 1 root root  10 Oct  1 21:11 usb-Razer_Razer_Ornata_V3_Tenkeyless-if01-event-kbd -> ../event14
lrwxrwxrwx 1 root root  10 Oct  1 21:11 usb-Razer_Razer_Ornata_V3_Tenkeyless-if02-event-mouse -> ../event17
lrwxrwxrwx 1 root root   9 Oct  1 21:11 usb-Razer_Razer_Ornata_V3_Tenkeyless-if02-mouse -> ../mouse4
```
```
001:012:002:DESCRIPTOR         1696209784.254085
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05
 01 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09
 31 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 06 00
 FF 09 02 15 00 25 01 75 08 95 5A B1 01 C0

001:012:001:DESCRIPTOR         1696209784.254704
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 0E 81 00 C0 05 0C 09 01 A1 01 85
 02 19 00 2A 3C 02 15 00 26 3C 02 95 01 75 10 81
 00 75 08 95 0D 81 01 C0 05 01 09 80 A1 01 85 03
 19 81 29 83 15 00 25 01 75 01 95 03 81 02 95 05
 81 01 75 08 95 0E 81 01 C0 05 01 09 00 A1 01 85
 04 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95
 0F 81 00 C0 05 01 09 00 A1 01 85 05 09 03 15 00
 26 FF 00 35 00 46 FF 00 75 08 95 0F 81 00 C0

001:012:000:DESCRIPTOR         1696209784.255226
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

001:013:002:DESCRIPTOR         1696209784.255613
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05
 01 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09
 31 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 06 00
 FF 09 02 15 00 25 01 75 08 95 5A B1 01 C0

001:013:001:DESCRIPTOR         1696209784.256222
 05 01 09 06 A1 01 85 01 05 07 05 07 19 E0 29 E7
 15 00 25 01 75 01 95 08 81 02 19 00 29 A0 15 00
 25 01 75 01 95 A0 81 02 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0 05 0C 09
 01 A1 01 85 02 19 00 2A 3C 02 15 00 26 3C 02 95
 01 75 10 81 00 75 08 95 13 81 01 C0 05 01 09 80
 A1 01 85 03 19 81 29 83 15 00 25 01 75 01 95 03
 81 02 95 05 81 01 75 08 95 14 81 01 C0 05 01 09
 00 A1 01 85 04 09 03 15 00 26 FF 00 35 00 46 FF
 00 75 08 95 15 81 00 C0 05 01 09 00 A1 01 85 05
 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95 15
 81 00 C0

001:013:000:DESCRIPTOR         1696209784.256799
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

001:009:002:DESCRIPTOR         1696209784.257138
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

001:009:001:DESCRIPTOR         1696209784.257675
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 0E 81 00 C0 05 0C 09 01 A1 01 85
 02 19 00 2A 3C 02 15 00 26 3C 02 95 01 75 10 81
 00 75 08 95 0D 81 01 C0 05 01 09 80 A1 01 85 03
 19 81 29 83 15 00 25 01 75 01 95 03 81 02 95 05
 81 01 75 08 95 0E 81 01 C0 05 01 09 00 A1 01 85
 04 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95
 0F 81 00 C0 05 01 09 00 A1 01 85 05 09 03 15 00
 26 FF 00 35 00 46 FF 00 75 08 95 0F 81 00 C0

001:009:000:DESCRIPTOR         1696209784.258305
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05
 01 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09
 31 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 06 00
 FF 09 02 15 00 25 01 75 08 95 5A B1 01 C0
```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>
stepping through this

### Synapse Screenshots
I'm on ubuntu. I'm not sure how to get these screenshots
<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>

### PR DESCRIPTION
**Pull request by AndersKlint**
Fixes #2140.
 
Tested in Polychromatic and everything works fine, however there are some minor issues:

* Polychromatic is a bit sluggish and freezes for ~5s when changing effects. Also very laggy when dragging the brightness slider, but clicking it works fine. Some errors seen in dmesg after playing around a bit in Polychromatic:
  
```
[ 1988.212506] razerkbd 0003:1532:02A3.0011: input,hidraw1: USB HID v1.11 Keyboard [Razer Razer Ornata V3 Tenkeyless] on usb-0000:02:00.0-3.2/input0
[ 1988.225826] input: Razer Razer Ornata V3 Tenkeyless as /devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-3/1-3.2/1-3.2:1.1/0003:1532:02A3.0012/input/input34
[ 1988.284582] razerkbd 0003:1532:02A3.0012: input,hidraw2: USB HID v1.11 Keyboard [Razer Razer Ornata V3 Tenkeyless] on usb-0000:02:00.0-3.2/input1
[ 1988.311672] input: Razer Razer Ornata V3 Tenkeyless as /devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-3/1-3.2/1-3.2:1.2/0003:1532:02A3.0013/input/input35
[ 1988.311822] razerkbd 0003:1532:02A3.0013: input,hidraw3: USB HID v1.11 Mouse [Razer Razer Ornata V3 Tenkeyless] on usb-0000:02:00.0-3.2/input2
[ 1995.409289] razer driver: Device data transfer failed.
[ 1995.417245] razerkbd: Response doesn't match request. status: 02 transaction_id.id: 1f remaining_packets: 00 protocol_type: 00 data_size: 03, command_class: 0f, command_id.id: 04 Params: 01054c00000000000000000000000000 .
[ 2038.561171] razer driver: Invalid USB response. USB Report length: 26
[ 2038.561175] razerkbd: Invalid Report Length. status: 00 transaction_id.id: 00 remaining_packets: 00 protocol_type: 00 data_size: 00, command_class: 00, command_id.id: 00 Params: 00000000000000000000000000000000 .
[ 2048.912788] razer driver: Device data transfer failed.
[ 2048.920677] razerkbd: Response doesn't match request. status: 02 transaction_id.id: 1f remaining_packets: 00 protocol_type: 00 data_size: 06, command_class: 0f, command_id.id: 02 Params: 01050402280000000000000000000000 .
[ 2058.640811] razer driver: Device data transfer failed.
[ 2058.648213] razerkbd: Response doesn't match request. status: 02 transaction_id.id: 1f remaining_packets: 00 protocol_type: 00 data_size: 09, command_class: 0f, command_id.id: 02 Params: 01050201000100ff0000000000000000 .
```

* Another error is that the keyboard remains lit after the computer has been turned off.

* After boot I get this error which disappears after replugging the usb:
image

Not sure if these problems are expected, otherwise I will make an issue and troubleshoot some more.
(on kernel 6.6.6-76060606-generic, keyboard is connected via a usb hub)

### CODE REVIEW

**Comment by alichtman** [comment]
I tested this PR, and all of the modes except for Breath seem to work for me! 
I just wanted static white, so I am happy.

image

**Comment by AndersKlint** [comment]
> I tested this PR, and all of the modes except for Breath seem to work for me! I just wanted static white, so I am happy.

Thanks @alichtman! Good to know it works for others too. No errors after restarting the computer in dmesg?

If you just want static white, do you need this driver though? I can press "fn + ctrl + 2" to cycle between static colours (built into the keyboard firmware). There are two different shades of white/gray in the built in colours, so maybe you don't need the driver after all?

**Comment by alichtman** [comment]
I didn't notice anything in dmesg but I didn't look too closely. 

And I like having the extra configurability if I want to use it.
Edit: I just tested it and couldn't get it to work.

**Comment by alichtman** [comment]
No `dmesg` errors, and it's been pretty stable (aside from a little keyboard flickering every now and again)

```
$ sudo dmesg | grep razer                                                                                                                       
[sudo] password for alichtman: 
[    3.161760] razerkbd: loading out-of-tree module taints kernel.
[    3.161782] razerkbd: module verification failed: signature and/or required key missing - tainting kernel
[    3.776147] razerkbd 0003:1532:02A3.0003: input,hidraw2: USB HID v1.11 Keyboard [Razer Razer Ornata V3 Tenkeyless] on usb-0000:07:00.3-6.3/input0
[    3.938862] razerkbd 0003:1532:02A3.0005: input,hidraw3: USB HID v1.11 Mouse [Razer Razer Ornata V3 Tenkeyless] on usb-0000:07:00.3-6.3/input2
[    4.428269] razerkbd 0003:1532:02A3.0004: input,hidraw4: USB HID v1.11 Keyboard [Razer Razer Ornata V3 Tenkeyless] on usb-0000:07:00.3-6.3/input1
```

**Comment by AndersKlint** [comment]
> No `dmesg` errors, and it's been pretty stable (aside from a little keyboard flickering every now and again)
> 
> ```
> $ sudo dmesg | grep razer                                                                                                                       
> [sudo] password for alichtman: 
> [    3.161760] razerkbd: loading out-of-tree module taints kernel.
> [    3.161782] razerkbd: module verification failed: signature and/or required key missing - tainting kernel
> [    3.776147] razerkbd 0003:1532:02A3.0003: input,hidraw2: USB HID v1.11 Keyboard [Razer Razer Ornata V3 Tenkeyless] on usb-0000:07:00.3-6.3/input0
> [    3.938862] razerkbd 0003:1532:02A3.0005: input,hidraw3: USB HID v1.11 Mouse [Razer Razer Ornata V3 Tenkeyless] on usb-0000:07:00.3-6.3/input2
> [    4.428269] razerkbd 0003:1532:02A3.0004: input,hidraw4: USB HID v1.11 Keyboard [Razer Razer Ornata V3 Tenkeyless] on usb-0000:07:00.3-6.3/input1
> ```

Looks good, thanks for providing the logs!

**Comment by alichtman** [comment]
Is there anything blocking merging this PR?

**Comment by AndersKlint** [comment]
> Is there anything blocking merging this PR?

Yes, we're waiting for a maintainer to review it. I don't have merge permission.

**Comment by z3ntu** [comment]
I don't see any stylistic problems in the PR, so from that front it looks good!

@AndersKlint Do you still experience the issues you listed in the PR description? Based on @alichtman 's comments it works fine for them so I'm questioning if it's a general problem with this PR or somehow just on your PC.

**Comment by AndersKlint** [comment]
> @AndersKlint Do you still experience the issues you listed in the PR description? Based on @alichtman 's comments it works fine for them so I'm questioning if it's a general problem with this PR or somehow just on your PC.

I've since moved to Fedora 39 and everything seems to work fine except the media keys who now all print "bcd". Actually while I still was on Pop OS a couple of months back, the media keys just suddenly stopped working (probably after a system upgrade). I'm pretty sure they used to work at some point with the Daemon running.

Seems I have exactly this issue:
https://github.com/openrazer/openrazer/issues/1398#issuecomment-1819252540
Using fn+f2 etc. seems to work, but not the dedicated volume buttons on the keyboard unfortunately.

I will see if I get some time to troubleshoot this. Do you have any idea?

**Comment by alichtman** [comment]
I can repro the dedicated volume buttons not working on my Ubuntu 23.10 system. They used to, though!

**Comment by z3ntu** [comment]
@AndersKlint Thanks for the update. For the volume buttons sounds like you need something like https://github.com/openrazer/openrazer/commit/af1e2b0d921c25be24834b8970ba52b5c8a712d3 or https://github.com/openrazer/openrazer/pull/1834?

**Review by bakankaya — APPROVED** [review]

**Comment by z3ntu** [comment]
Closing in favor of #2260, thanks for the contribution!

**Pull request closed without merging**
