### PR TITLE
Support for Razer DeathAdder V3 Pro #1889

### LINKED ISSUE #1889: Support for Razer DeathAdder V3 Pro
### Device Info

* Name: DeathAdder V3 PRO
* Product Number: RZ01-04630100
* Model Number: RZ01-0463

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
In Wired mode:

Bus 001 Device 007: ID 1532:00b6 Razer USA, Ltd Razer DeathAdder V3 Pro
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x00b6 
  bcdDevice            1.00
  iManufacturer           1 Razer
  iProduct                2 Razer DeathAdder V3 Pro
  iSerial                 3 000000000000
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)


In Wireless mode:

Bus 001 Device 011: ID 1532:00b7 Razer USA, Ltd Razer DeathAdder V3 Pro
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x00b7 
  bcdDevice            1.00
  iManufacturer           1 Razer
  iProduct                2 Razer DeathAdder V3 Pro
  iSerial                 3 000000000000
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          4 Default configuration
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     314
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)

```

```
Please post the output of
    ls -lah /dev/input/by-id/

In Wired mode:
lrwxrwxrwx 1 root root  10 Aug 20 05:09 usb-Razer_Razer_DeathAdder_V3_Pro_000000000000-event-if01 -> ../event11
lrwxrwxrwx 1 root root   9 Aug 20 05:09 usb-Razer_Razer_DeathAdder_V3_Pro_000000000000-event-mouse -> ../event9
lrwxrwxrwx 1 root root  10 Aug 20 05:09 usb-Razer_Razer_DeathAdder_V3_Pro_000000000000-if01-event-kbd -> ../event10
lrwxrwxrwx 1 root root  10 Aug 20 05:09 usb-Razer_Razer_DeathAdder_V3_Pro_000000000000-if02-event-kbd -> ../event12
lrwxrwxrwx 1 root root   9 Aug 20 05:09 usb-Razer_Razer_DeathAdder_V3_Pro_000000000000-mouse -> ../mouse2

In Wireless mode:

lrwxrwxrwx 1 root root  10 Aug 20 05:14 usb-Razer_Razer_DeathAdder_V3_Pro_000000000000-event-if01 -> ../event12
lrwxrwxrwx 1 root root   9 Aug 20 05:14 usb-Razer_Razer_DeathAdder_V3_Pro_000000000000-event-mouse -> ../event9
lrwxrwxrwx 1 root root  10 Aug 20 05:14 usb-Razer_Razer_DeathAdder_V3_Pro_000000000000-if01-event-kbd -> ../event10
lrwxrwxrwx 1 root root  10 Aug 20 05:14 usb-Razer_Razer_DeathAdder_V3_Pro_000000000000-if01-event-mouse -> ../event11
lrwxrwxrwx 1 root root   9 Aug 20 05:14 usb-Razer_Razer_DeathAdder_V3_Pro_000000000000-if01-mouse -> ../mouse3
lrwxrwxrwx 1 root root  10 Aug 20 05:14 usb-Razer_Razer_DeathAdder_V3_Pro_000000000000-if02-event-kbd -> ../event30
lrwxrwxrwx 1 root root   9 Aug 20 05:14 usb-Razer_Razer_DeathAdder_V3_Pro_000000000000-mouse -> ../mouse2
```

### Packet Captures

Can provide if necessary

### Synapse Screenshots

DeathAdder_V3_Pro_Customize

DeathAdder_V3_Pro_Performance

DeathAdder_V3_Pro_Calibration

DeathAdder_V3_Pro_Power

Suspect the driver will be very similar to the recent V2 Pro @ https://github.com/openrazer/openrazer/pull/1849/commits/a3fb25963fff4a0cd458abbaa4cd21a196accd6e since the mice are very similar.

### PR DESCRIPTION
**Pull request by BLooD-DoG**
Resolves openrazer/openrazer#1889

### CODE REVIEW

**Comment by z3ntu** [comment]
Diff looks sane. Did you test all the functionality that shows up in e.g. polychromatic and does it all work?

**Comment by BLooD-DoG** [comment]
Yup, everything works fine.

Technically the DPI is clamped to 26000 even though the mouse (and frontend) supports up to 30000, but that's due to another issue which affects various mice and is resolved along with the HyperPolling Wireless Dongle PR.

**Comment by z3ntu** [comment]
Please try changing the 26000 values here to 30000
```
daemon/openrazer_daemon/hardware/mouse.py:    DPI_MAX = 26000
driver/razerchromacommon.c:    dpi_x = clamp_u16(dpi_x, 100, 26000);
driver/razerchromacommon.c:    dpi_y = clamp_u16(dpi_y, 100, 26000);
scripts/razer_mouse/driver/set_mouse_dpi.py:    parser.add_argument('--dpi_x', required=True, type=int, help="DPI on the X axis (100, 26000)")
scripts/razer_mouse/driver/set_mouse_dpi.py:    parser.add_argument('--dpi_y', type=int, help="DPI on the Y axis (if omitted, dpi_x is used), (100, 26000)")
scripts/razer_mouse/driver/set_mouse_dpi.py:    dpi_x = clamp_to_min_max(args.dpi_x, 100, 26000)
scripts/razer_mouse/driver/set_mouse_dpi.py:        dpi_y = clamp_to_min_max(args.dpi_y, 100, 26000)
```

**Comment by BLooD-DoG** [comment]
> Please try changing the 26000 values here to 30000

Yes, those changes are already part of https://github.com/openrazer/openrazer/pull/1921 and resolve the 26000 -> 30000 DPI issue. Note that this limitation/bug is not strictly related to just the DeathAdder V3 Pro, it also affects the Viper V2 Pro, the HyperPolling Wireless Dongle, and any other mouse that supports DPI > 26000 (e.g. Basilisk V3 Pro which I'm not sure is supported yet). That's why it doesn't really matter if this specific DPI fix is included in this PR or another one.

Also note that PR #1921 includes this PR #1889, plus support for the HyperPolling Wireless Dongle, plus the 30000 DPI fix (since it's relevant to both the DA V3 Pro and the HyperPolling Wireless Dongle support).

Since I use my DeathAdder V3 Pro exclusively with the HyperPolling Wireless Dongle, I really only care about PR #1921 being accepted, and then this PR becomes irrelevant :)

**Review by z3ntu — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
