### PR TITLE
Fixes Effect Sync on Mice

### PR DESCRIPTION
**Pull request by nightsky30**
Fixes Effect Sync on Mice

- [x] Adds Ignored Left / Right Mouse Lighting Zones (When notifications are received from other devices)
- [x] Fixes Flakiness With Sync'ed Brightness Settings for Mice

Not Fixed

- [ ] Apply Effect to All Mouse Zones (When the notification comes from one of the mouse's zones and effect sync is enabled)
  - Was trying to find a way to determine when Sync Effects was enabled, and only run effect from parent device then, but haven't found a working solution yet
  - #1489

### CODE REVIEW

**Comment by z3ntu** [comment]
Is this WIP?

**Comment by nightsky30** [comment]
> Is this WIP?

The first two issues are fully fixed. If you want, you can merge this PR as is and I can open an issue for the remaining bug.

I've tried adding a check for the last issue without success. With other changes I've tried, either the daemon crashes or the effects are sync'ed on all mouse zones even when effect sync is disabled. I don't believe I'm grabbing the proper effect sync value. I think I've tried getting it from the parent device and the device manager(?). My python skill is not great :D

**Review by z3ntu — APPROVED** [review]
LGTM, thanks!
Btw I've also fixed the `if brightness > 100` in `charging_pad_chroma.py`

**Comment by nightsky30** [comment]
> LGTM, thanks!
> Btw I've also fixed the `if brightness > 100` in `charging_pad_chroma.py`

Oh cool! Thanks :smile:

**Pull request merged**
