### PR TITLE
Rename device types

### PR DESCRIPTION
**Pull request by z3ntu**
- [x] Rename device type of Firefly to 'mousemat'
- [x] Rename device type from tartarus to 'keypad'
- [x] Rename device type from orbweaver to 'keypad'
- [x] Change capability `macro_tartarus_mode_modifier` ?

### CODE REVIEW

**Review by lah7 — APPROVED** [review]
Looks good to me. :+1:

[One of the capabilities for Tartarus](https://github.com/lah7/polychromatic/blob/master/docs/known_capabilities/tartarus.json#L49) outputs `macro_tartarus_mode_modifier`, will that string change too or be kept the same?

**Review by terricain — APPROVED** [review]
Skim read it, looks good to me

**Comment by z3ntu** [comment]
@lah7 I saw it and thought that I can change it but it would break maybe some applications? Do you use it? Otherwise I can change it too in this PR.

**Comment by lah7** [comment]
Polychromatic doesn't read `macro_tartarus_mode_modifier` yet, and from a grep in razerCommander, it doesn't look like it's used there either, so it _should_ be safe to change it for consistency.

**Comment by terricain** [comment]
Just change it :smile:, we're suffer any fallout if there is any.

**Comment by z3ntu** [comment]
Please **do not** squash and merge 😉

**Pull request merged**
