### PR TITLE
Adds support for the Tartarus Pro

### LINKED ISSUE #1039: Support for Tartarus Pro (1532:0244)
### Device Info

* Name: Razer Tartarus Pro
* Product Number: RZ07-03110100
* Model Number: RZ07-0311

### Device Information
```
Bus 001 Device 004: ID 1532:0244 Razer USA, Ltd 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0244 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     186
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0018  1x 24 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
```

```
lrwxrwxrwx 1 root root  10 Mar  3 14:54 usb-Razer_Razer_Tartarus_Pro-event-if01 -> ../event28
lrwxrwxrwx 1 root root  10 Mar  3 14:54 usb-Razer_Razer_Tartarus_Pro-event-kbd -> ../event25
lrwxrwxrwx 1 root root  10 Mar  3 14:54 usb-Razer_Razer_Tartarus_Pro-if01-event-kbd -> ../event26
lrwxrwxrwx 1 root root  10 Mar  3 14:54 usb-Razer_Razer_Tartarus_Pro-if02-event-mouse -> ../event30
lrwxrwxrwx 1 root root   9 Mar  3 14:54 usb-Razer_Razer_Tartarus_Pro-if02-mouse -> ../mouse1
```
### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>
Setup is the same as the Tartarus Chroma, I don't have a screenshot but it is the exact same layout so I suspect that a copy pasta of the Chroma code would be a good place to start. 100% willing to run some tests. will start reading up on the above capture packets.

### PR DESCRIPTION
**Pull request by notsebtho**
Picking up where #1577 left off. Have started by regenerating all of the fake device drivers. PR is meant to address #1039

### CODE REVIEW

**Comment by z3ntu** [comment]
Does the device work with this PR? I think from what I saw in #1577 it didn't work yet.

**Comment by justinkb** [comment]
I tried this PR, got those -110 errors too

**Comment by z3ntu** [comment]
@SebastianLloret Would be great if you could continue working on this PR so we can get the functionality integrated into OpenRazer!

**Comment by latenitefilms** [comment]
The Tartarus Pro works slightly differently from the Tartarus V2. This should point you in the right direction:

https://github.com/CommandPost/CommandPost-App/blob/master/extensions/razer/HSRazerTartarusProDevice.m

**Comment by z3ntu** [comment]
Any update on this?

**Comment by deB4rro5** [comment]
Hello, new to the project, just wanted to say thank you so much for all you've done so to support the community.  I have a Tartarus Pro and would love to help get this over the finish line.  I'm not a developer but if there is anything I can do to test, grab files/ screenshots etc I'm more than happy to contribute in any way possible.

**Comment by masterz666** [comment]
Same here, would love to contribute by testing, helping in troubleshooting, etc...

**Comment by z3ntu** [comment]
@deB4rro5 @masterz666 For testing: https://github.com/openrazer/openrazer/wiki/Building-a-package

For fixing issues, a basic guide is https://github.com/openrazer/openrazer/blob/master/DEVELOPMENT.md

**Comment by jerrygb** [comment]
@SebastianLloret 

Thank you for your support in putting together this PR.

Would you have some time to be able look into this and wrap the support?

**Comment by z3ntu** [comment]
Closing in favor of #2336, thanks for your contributions!

**Pull request closed without merging**
