### PR TITLE
Offload daemonize to python3-daemonize

### PR DESCRIPTION
**Pull request by whot**
A bit of rework so that instead of having to handle the daemon bits, we can just punt that job off to the daemonize python package. If that's not acceptable, consider the first patch though, it separates things a bit cleaner than the current daemonize() method.

Builds on top of #385, first real commit is  "daemon: replace daemonize with a DaemonContext class"

### CODE REVIEW

**Comment by terricain** [comment]
Once #385 is merged the diff should be cleaner on this, then I'll have a proper look but it seems ok atm

**Comment by terricain** [comment]
More conflicts :D, sorry am too lazy to fix them myself

**Comment by terricain** [comment]
ahh I still squashed it, sigh, but too late, I cba to revert and remerge.

**Comment by whot** [comment]
*please* do. It's not that hard and having this squashed in makes the history useless.

```
git revert 435509d # with a comment why...
git remote add whot https//github.com/whot/openrazer
git pull whot wip/dbus-daemonize
# check everything is hunky-dory
git push origin master
```

**Comment by z3ntu** [comment]
I have force-pushed (sorry^^) master with a clean history. Please base off of that.

**Comment by z3ntu** [comment]
@whot You haven't tested this on Ubuntu/Debian, right? 
Because you use a python-daemonize parameter (`chdir`) that's not supported in the version available on Debian and Ubuntu. It was added in https://github.com/thesharp/daemonize/commit/21ba701e3a5c642582db20d986aa0da1b3da8f9c (included in version 2.4+) but Debian and Ubuntu only include version 2.3.1. Can you PR a workaround please?

**Comment by whot** [comment]
@z3ntu see #421

**Pull request merged**
