### PR TITLE
driver: add support for Razer Viper V2 Pro

### LINKED ISSUE #1820: Support for Razer Viper V2 Pro
### Device Info

* Name: Razer Viper V2 Pro
* Product Number: RZ01-04390200
* Model Number: RZ01-0439

### Device Information
```
Bus 007 Device 005: ID 1532:00a6 Razer USA, Ltd Razer Viper V2 Pro
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x00a6 
  bcdDevice            1.00
  iManufacturer           1 Razer
  iProduct                2 Razer Viper V2 Pro
  iSerial                 3 000000000000
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0086
    bNumInterfaces          5
    bConfigurationValue     1
    iConfiguration          4 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     314
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        4
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     325
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     348
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
```

```
9 May 23 12:35 usb-Razer_Razer_Viper_V2_Pro_000000000000-event-if01 -> ../event5
10 May 23 12:35 usb-Razer_Razer_Viper_V2_Pro_000000000000-event-if03 -> ../event23
9 May 23 12:35 usb-Razer_Razer_Viper_V2_Pro_000000000000-event-mouse -> ../event2
9 May 23 12:35 usb-Razer_Razer_Viper_V2_Pro_000000000000-if01-event-kbd -> ../event3
9 May 23 12:35 usb-Razer_Razer_Viper_V2_Pro_000000000000-if01-event-mouse -> ../event4
9 May 23 12:35 usb-Razer_Razer_Viper_V2_Pro_000000000000-if01-mouse -> ../mouse2
10 May 23 12:35 usb-Razer_Razer_Viper_V2_Pro_000000000000-if02-event-kbd -> ../event22
9 May 23 12:35 usb-Razer_Razer_Viper_V2_Pro_000000000000-mouse -> ../mouse0
```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
I will update this later when I am on my Windows machine.

### LINKED ISSUE #1841: Support for Razer Viper V2 Pro mouse
### Device Info

* Name: Razer Viper V2 Pro
* Product Number: R201-04390100
* Model Number: R201-0439

### Device Information
```
Bus 003 Device 002: ID 1532:00a6 Razer USA, Ltd Razer Viper V2 Pro
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x00a6 
  bcdDevice            1.00
  iManufacturer           1 Razer
  iProduct                2 Razer Viper V2 Pro
  iSerial                 3 000000000000
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0086
    bNumInterfaces          5
    bConfigurationValue     1
    iConfiguration          4 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     314
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        4
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     325
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     348
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1

```

```
Please post the output of
total 0
drwxr-xr-x 2 root root 360 Jun 19 10:54 .
drwxr-xr-x 4 root root 740 Jun 19 10:54 ..
lrwxrwxrwx 1 root root   9 Jun 19 10:54 usb-ACTIONS_Pebble_V3-event-if03 -> ../event9
lrwxrwxrwx 1 root root  10 Jun 19 10:54 usb-ASRock_LED_Controller_A02019100900-event-joystick -> ../event28
lrwxrwxrwx 1 root root   6 Jun 19 10:54 usb-ASRock_LED_Controller_A02019100900-joystick -> ../js0
lrwxrwxrwx 1 root root  10 Jun 19 10:54 usb-Razer_Razer_Huntsman_V2_Analog-event-if04 -> ../event26
lrwxrwxrwx 1 root root  10 Jun 19 10:54 usb-Razer_Razer_Huntsman_V2_Analog-event-kbd -> ../event23
lrwxrwxrwx 1 root root  10 Jun 19 10:54 usb-Razer_Razer_Huntsman_V2_Analog-if01-event-kbd -> ../event24
lrwxrwxrwx 1 root root  10 Jun 19 10:54 usb-Razer_Razer_Huntsman_V2_Analog-if02-event-mouse -> ../event25
lrwxrwxrwx 1 root root   9 Jun 19 10:54 usb-Razer_Razer_Huntsman_V2_Analog-if02-mouse -> ../mouse2
lrwxrwxrwx 1 root root   9 Jun 19 10:54 usb-Razer_Razer_Viper_V2_Pro_000000000000-event-if01 -> ../event6
lrwxrwxrwx 1 root root   9 Jun 19 10:54 usb-Razer_Razer_Viper_V2_Pro_000000000000-event-if03 -> ../event8
lrwxrwxrwx 1 root root   9 Jun 19 10:54 usb-Razer_Razer_Viper_V2_Pro_000000000000-event-mouse -> ../event2
lrwxrwxrwx 1 root root   9 Jun 19 10:54 usb-Razer_Razer_Viper_V2_Pro_000000000000-if01-event-kbd -> ../event4
lrwxrwxrwx 1 root root   9 Jun 19 10:54 usb-Razer_Razer_Viper_V2_Pro_000000000000-if01-event-mouse -> ../event5
lrwxrwxrwx 1 root root   9 Jun 19 10:54 usb-Razer_Razer_Viper_V2_Pro_000000000000-if01-mouse -> ../mouse1
lrwxrwxrwx 1 root root   9 Jun 19 10:54 usb-Razer_Razer_Viper_V2_Pro_000000000000-if02-event-kbd -> ../event7
lrwxrwxrwx 1 root root   9 Jun 19 10:54 usb-Razer_Razer_Viper_V2_Pro_000000000000-mouse -> ../mouse0

```

### Packet Captures

Not sure if this is needed and looks complicated but will do the work if required.

### Synapse Screenshots
https://imgur.com/a/HcDtC9X

### PR DESCRIPTION
**Pull request by blacha**
Tested both wired and wireless with polychromatic and looks like everything is working.

Some wireshark captures for this device https://gist.github.com/blacha/d4bee6ea474a86258a39028c6ba1679d

Fixes #1841 Fixes #1820

### CODE REVIEW

**Comment by levouh** [comment]
Being a nuisance and bumping this @z3ntu (mentioning you as you seem to have a decent chunk of activity on `master`). Support for the V2 Pro would be awesome.

Anything I can do to help get this merged? E.g. testing, etc.

**Comment by blacha** [comment]
> Anything I can do to help get this merged? E.g. testing, etc.

@levouh More testing would be super!

I have been running this now almost a week as my main mouse (WIrelessly) and haven't had any real issues.

The only slight annoyance I've found is that sometimes when my computer wakes up from sleep the mouse reports 0% battery  but then quickly fixes itself.

**Comment by levouh** [comment]
What operating system do you run @blacha? Sorry to clog up your PR with questions like this, but on Fedora I am doing the following:

<details>

```sh
#!/bin/bash

tmp_dir=$(mktemp -d -t "openrazer-XXXXXXXX")
cleanup() {
    if [ -d ~/rpmbuild ]; then
        rm -rf ~/rpmbuild
    fi

    if [ -d "$tmp_dir" ]; then
        rm -rf "$tmp_dir"
    fi
}

trap cleanup HUP INT TERM ERR EXIT

# Create tarball of source from 'blacha/openrazer'
setup_tarball() {
    local version="$1"

    builtin cd "$tmp_dir" || return
    git clone -b driver/support-viper-2-pro git@github.com:blacha/openrazer.git ./openrazer >/dev/null
    builtin cd ./openrazer || return

    git archive --prefix="openrazer-${version}/" -o "openrazer-${version}.tar.gz" HEAD
    readlink -f "openrazer-${version}.tar.gz"
}

# Setup rpmbuild spec. (based on Github, but replace source with custom tarball)
setup_spec() {
    local version=""
    local tarball=""

    cd ~/rpmbuild/SPECS || return

    curl -O https://raw.githubusercontent.com/openrazer/OBS-packaging/master/openrazer.spec
    sed -i 's#URL: .*#URL: https://github.com/blacha/openrazer#' ./openrazer.spec

    version=$(grep -E "^Version:" ./openrazer.spec | awk '{ print $2 }')
    tarball=$(setup_tarball "$version")
    cp "$tarball" ~/rpmbuild/SOURCES
    tarball=$(basename "$tarball")
    sed -i "s/Source0: .*/Source0: ${tarball}/" ./openrazer.spec

    echo "###############################################################"
    grep "URL:" ./openrazer.spec
    grep "Source0" ./openrazer.spec
    echo "###############################################################"
}

# Main wrapper to remove, build, install, and restart daemon
install_openrazer() {
    sudo dnf remove -y 'openrazer*'
    sudo dnf install -y rpm-build rpmdevtools

    rpmdev-setuptree

    setup_spec

    spectool -g -R openrazer.spec
    sudo dnf -y builddep openrazer.spec
    rpmbuild -bb openrazer.spec
    sudo dnf install -y ../RPMS/noarch/*.rpm
    
    systemctl --user daemon-reload
    systemctl --user enable --now openrazer-daemon
}

install_openrazer
```

</details>

following what is enumerated [here](https://github.com/openrazer/openrazer/wiki/Building-a-package). Then looking for the device via:

```python
from openrazer.client import DeviceManager

dm = DeviceManager()

for d in dm.devices:
    print(d)
```

but get nothing printed out despite:

```sh
$ lsusb | grep Razer
Bus 003 Device 002: ID 1532:00a6 Razer USA, Ltd Razer Viper V2 Pro
```

Any ideas? Will remove this comment if it is not relevant here or just serves to clog up the PR. Thanks.

---

Edit: Fix `git clone` command to use correct branch.

**Comment by blacha** [comment]
I am on ubuntu, so have just been using the `build_debs.sh` script and then `dpkg -i`  to install them all.

What do you have inside of  `/sys/bus/hid/drivers/` ?

I generally use `cat /sys/bus/hid/drivers/razermouse/*:*/device_*` to validate that device has loaded correctly.

**Comment by levouh** [comment]
I am just dumb and was using the default branch of your fork rather than:

```
git clone -b driver/support-viper-2-pro git@github.com:blacha/openrazer.git
```

---

It works now as expected. Will continue with testing and let you know if I find anything. Thanks for the PR @blacha.

**Comment by Karagra** [comment]
I may be an idiot, but how would I use this on arch linux before it is fully implemented?

**Comment by z3ntu** [comment]
@Karagra https://github.com/openrazer/openrazer/wiki/Building-a-package#arch-linux

**Review by z3ntu — APPROVED** [review]
Resolved a very minor style issue, LGTM! Thanks a lot for the pull request!

**Pull request merged**
