### PR TITLE
Add support for Razer Blade Stealth Late 2019

### PR DESCRIPTION
**Pull request by echap1**
Just a copy from the previous blade stealth

I have the 1650 model with the 1080p screen and this works for me.

### CODE REVIEW

**Comment by soren121** [comment]
This PR works great on my machine, the Iris Plus model. All five lighting modes work correctly.

**Comment by Nepharius88** [comment]
Works great for me too! Thank you a lot!

**Comment by stvnksslr** [comment]
works great for me as well with the iris plus model :+1:

**Comment by z3ntu** [comment]
Hi, thanks for the PR. It generally looks fine, but could you test adding Starlight support, like #978 ?

**Comment by rustysec** [comment]
the late 2019 stealth is single zone rgb, starlight isn't supported.

**Review by z3ntu — APPROVED** [review]
I did some final touches (removing unnecessary changes)

LGTM, thank you for the contribution!

**Pull request merged**
