### PR TITLE
Add Razer 15 mid 2019 base model.

### PR DESCRIPTION
**Pull request by creslinux**
Adds support for 2019 15" Base 
[https://support.razer.com/gaming-laptops/razer-blade-15-mid-2019-base/](https://support.razer.com/gaming-laptops/razer-blade-15-mid-2019-base/)

This laptop has a single colour zone on the keyboard

Tested the build on Ubuntu 19.10 and seems to be working, can control the colour / brightness  / effect in polychromatic-controller

### CODE REVIEW

**Comment by godbyk** [comment]
This worked for my on my 2019 15" Blade.

**Comment by z3ntu** [comment]
Hi, the PR generally looks fine but you're missing some `device_remove_file` calls. 

Also did you test all features and do they work properly?

**Comment by creslinux** [comment]
> Hi, the PR generally looks fine but you're missing some `device_remove_file` calls.
> 
> Also did you test all features and do they work properly?

All effects, setting colour, brightness work. 
I've only tested these via Polychromatic Controller, which I've been using daily for a couple months without issue. 

Will take a look for `device_remove_file` entries.  I'm not a c programmer, any hints would be appreciated.

**Comment by creslinux** [comment]
For the  `USB_DEVICE_ID_RAZER_BLADE_2019_BASE`  I only included the files used on the 2018 Base Model, as reference; as this model also only supports a single colour at a time across the whole keyboard.   

My assumption was the other effects may need more than 1 colour on different keys at the same moment, or different brightness on individual keys etc.

```

 case USB_DEVICE_ID_RAZER_BLADE_2018_MERCURY:
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_wave);            // Wave effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_starlight);       // Starlight effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_spectrum);        // Spectrum effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_none);            // No effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_reactive);        // Reactive effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_breath);          // Breathing effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_static);          // Static effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_custom);          // Custom effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_custom_frame);           // Set LED matrix
            break;

        case USB_DEVICE_ID_RAZER_BLADE_2018_BASE:
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_spectrum);        // Spectrum effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_none);            // No effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_reactive);        // Reactive effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_breath);          // Breathing effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_static);          // Static effect
            break;

        case USB_DEVICE_ID_RAZER_BLADE_2019_ADV:
        case USB_DEVICE_ID_RAZER_BLADE_MID_2019_MERCURY:
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_wave);            // Wave effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_starlight);       // Starlight effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_spectrum);        // Spectrum effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_none);            // No effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_reactive);        // Reactive effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_breath);          // Breathing effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_static);          // Static effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_custom);          // Custom effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_custom_frame);           // Set LED matrix
            break;

        case USB_DEVICE_ID_RAZER_BLADE_2019_BASE:
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_spectrum);        // Spectrum effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_none);            // No effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_reactive);        // Reactive effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_breath);          // Breathing effect
            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_static);          // Static effect
            break;
```

**Comment by z3ntu** [comment]
No problem, I've added it myself. Here's the diff:
```diff
diff --git a/driver/razerkbd_driver.c b/driver/razerkbd_driver.c
index 5909fbb..a93cdd8 100644
--- a/driver/razerkbd_driver.c
+++ b/driver/razerkbd_driver.c
@@ -2431,6 +2431,14 @@ static void razer_kbd_disconnect(struct hid_device *hdev)
             device_remove_file(&hdev->dev, &dev_attr_matrix_custom_frame);           // Set LED matrix
             break;
 
+        case USB_DEVICE_ID_RAZER_BLADE_2019_BASE:
+            device_remove_file(&hdev->dev, &dev_attr_matrix_effect_spectrum);        // Spectrum effect
+            device_remove_file(&hdev->dev, &dev_attr_matrix_effect_none);            // No effect
+            device_remove_file(&hdev->dev, &dev_attr_matrix_effect_reactive);        // Reactive effect
+            device_remove_file(&hdev->dev, &dev_attr_matrix_effect_breath);          // Breathing effect
+            device_remove_file(&hdev->dev, &dev_attr_matrix_effect_static);          // Static effect
+            break;
+
         case USB_DEVICE_ID_RAZER_BLADE_LATE_2016:
             device_remove_file(&hdev->dev, &dev_attr_matrix_effect_wave);            // Wave effect
             device_remove_file(&hdev->dev, &dev_attr_matrix_effect_starlight);       // Starlight effect

```

**Review by z3ntu — APPROVED** [review]
LGTM, I've also removed additional changes (related to the custom frame/matrix) that aren't required on this device.

**Comment by creslinux** [comment]
Boom boom, thanks @z3ntu for the help and the merge.

**Comment by z3ntu** [comment]
Thank YOU for the contribution! :)

**Pull request merged**
