### PR TITLE
Implementing some missing set breath triple code

### PR DESCRIPTION
**Pull request by kevchu3**
This fixes some missing and inconsistent set breath triple functions.

### CODE REVIEW

**Comment by kevchu3** [comment]
Was trying to debug issue #1266 but wasn't able to fix it.  Meanwhile, I stumbled upon some other inconsistent code with how set breath triple is implemented, so this is a fix for that.

**Comment by z3ntu** [comment]
The diff looks a bit weird but I'm guessing the line with `self.send_effect_event('setBreathTriple',` was the actual change and the rest in that file is just a change in the order of the methods?

**Comment by kevchu3** [comment]
@z3ntu Yes, that was the actual change and I flipped the code for triple and dual so that it would logically list in order: single, dual, triple.

**Comment by z3ntu** [comment]
Thanks!

**Pull request merged**
