### PR TITLE
Ornata v3 (02A1) Support

### LINKED ISSUE #2053: Support for Razer Ornata V3 [02A1]
### Device Info

* Name: Razer Ornata V3
* Product Number: RZ03-0446
* Model Number: RZ03-04461200-R3L1

### Device Information
```
 Bus 001 Device 004: ID 1532:02a1 Razer USA, Ltd Razer Ornata V3
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x02a1 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Ornata V3
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     179
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0016  1x 22 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)
```
```
total 0
drwxr-xr-x 2 root root 280 Apr 24 16:49 .
drwxr-xr-x 4 root root 700 Apr 24 16:49 ..
lrwxrwxrwx 1 root root  10 Apr 24 16:48 usb-Razer_Razer_Ornata_V3-event-if01 -> ../event14
lrwxrwxrwx 1 root root  10 Apr 24 16:48 usb-Razer_Razer_Ornata_V3-event-kbd -> ../event10
lrwxrwxrwx 1 root root  10 Apr 24 16:48 usb-Razer_Razer_Ornata_V3-if01-event-kbd -> ../event12
lrwxrwxrwx 1 root root  10 Apr 24 16:48 usb-Razer_Razer_Ornata_V3-if02-event-mouse -> ../event17
lrwxrwxrwx 1 root root   9 Apr 24 16:48 usb-Razer_Razer_Ornata_V3-if02-mouse -> ../mouse3
lrwxrwxrwx 1 root root  10 Apr 24 16:48 usb-Razer_Razer_Viper_Mini-event-mouse -> ../event11
lrwxrwxrwx 1 root root  10 Apr 24 16:48 usb-Razer_Razer_Viper_Mini-if01-event-kbd -> ../event13
lrwxrwxrwx 1 root root  10 Apr 24 16:48 usb-Razer_Razer_Viper_Mini-if02-event-kbd -> ../event21
lrwxrwxrwx 1 root root   9 Apr 24 16:48 usb-Razer_Razer_Viper_Mini-mouse -> ../mouse2
lrwxrwxrwx 1 root root   9 Apr 24 16:48 usb-Valve_Software_Steam_Controller_123456789ABCDEF-event-mouse -> ../event8
lrwxrwxrwx 1 root root   9 Apr 24 16:48 usb-Valve_Software_Steam_Controller_123456789ABCDEF-if01-event-kbd -> ../event9
lrwxrwxrwx 1 root root   9 Apr 24 16:48 usb-Valve_Software_Steam_Controller_123456789ABCDEF-mouse -> ../mouse4
```

<details>

```
001:004:002:DESCRIPTOR         1682354721.962718
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05
 01 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09
 31 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 06 00
 FF 09 02 15 00 25 01 75 08 95 5A B1 01 C0

001:004:001:DESCRIPTOR         1682354721.965704
 05 01 09 06 A1 01 85 01 05 07 05 07 19 E0 29 E7
 15 00 25 01 75 01 95 08 81 02 19 00 29 A0 15 00
 25 01 75 01 95 A0 81 02 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0 05 0C 09
 01 A1 01 85 02 19 00 2A 3C 02 15 00 26 3C 02 95
 01 75 10 81 00 75 08 95 13 81 01 C0 05 01 09 80
 A1 01 85 03 19 81 29 83 15 00 25 01 75 01 95 03
 81 02 95 05 81 01 75 08 95 14 81 01 C0 05 01 09
 00 A1 01 85 04 09 03 15 00 26 FF 00 35 00 46 FF
 00 75 08 95 15 81 00 C0 05 01 09 00 A1 01 85 05
 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95 15
 81 00 C0

001:004:000:DESCRIPTOR         1682354721.968762
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

001:003:002:DESCRIPTOR         1682354721.970765
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

001:003:001:DESCRIPTOR         1682354721.973713
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 0E 81 00 C0 05 0C 09 01 A1 01 85
 02 19 00 2A 3C 02 15 00 26 3C 02 95 01 75 10 81
 00 75 08 95 0D 81 01 C0 05 01 09 80 A1 01 85 03
 19 81 29 83 15 00 25 01 75 01 95 03 81 02 95 05
 81 01 75 08 95 0E 81 01 C0 05 01 09 00 A1 01 85
 04 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95
 0F 81 00 C0 05 01 09 00 A1 01 85 05 09 03 15 00
 26 FF 00 35 00 46 FF 00 75 08 95 0F 81 00 C0

001:003:000:DESCRIPTOR         1682354721.976687
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05
 01 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09
 31 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 06 00
 FF 09 02 15 00 25 01 75 08 95 5A B1 01 C0
```

</details>

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>

### PR DESCRIPTION
**Pull request by greasydeal**
Adding support for Ornata V3 (02A1). 

I have None, Static, Wave, Breathe, Ripple, Reactive, and Custom effects working and tested personally. I also have game mode working.I haven't figured out starlight yet. It is available in windows but the pcaps I gathered do not seem to be helpful.

I see there are a few Ornata V3 PRs out there with different PIDs. I could change the define to be more specific if needed to avoid conflicts. What would be the perfered naming convention is so?

Fixes #2053

### CODE REVIEW

**Comment by Aakodal** [comment]
Is there a reason you closed this PR?

**Comment by z3ntu** [comment]
@greasydeal ^ ?

**Comment by PapaBones** [comment]
Any chance for this PR to be pushed? I got this keyboard and no support is just saw when new ones got added "recently".

**Comment by z3ntu** [comment]
@PapaBones Feel free to take this code, fix if something needs to be fixed and open a new pull request with it.
Somebody with access to this device model needs to do that :)

**Pull request closed without merging**
