### PR TITLE
Add support for Razer Blade 14 (2023)

### LINKED ISSUE #2087: Support for Razer Blade 14 2023
## Maintainer edit:

This is the device support issue for Razer Blade 14 2023:
```
ID 1532:029d Razer USA, Ltd Razer Blade
```

See also https://github.com/openrazer/openrazer/issues/2087#issuecomment-1784972959

---

**Original text:**

### Distribution

Ubuntu 20.04 5.15.0-75-generic
### Support

Speakers are not working/ detected. I have tried pulseaudio solution with no success. 
OpenRazer doesn't support the model.
Multiple ACPI BIOS error on boot screen. 

ACPI Errors:
```

ACPI Error: No handler for Region [VRTC] (000000000e212572) [SystemCMOS] (20210730/evregion-130)
[    0.240143] ACPI Error: Region SystemCMOS (ID=5) has no handler (20210730/exfldio-261)
[    0.240148] ACPI Error: Aborting method \_SB.PCI0.SBRG.EC0.RTEC due to previous error (AE_NOT_EXIST) (20210730/psparse-529)
[    0.240150] ACPI Error: Aborting method \_SB.PCI0.SBRG.EC0._REG due to previous error (AE_NOT_EXIST) (20210730/psparse-529)
```

### PR DESCRIPTION
**Pull request by zac-freeman**
Changes based on https://github.com/openrazer/openrazer/pull/2092. I mainly replaced instances of `029E` with `029D` and grabbed an image from the support website.

```bash
$ lsusb | grep '1532:'
Bus 001 Device 002: ID 1532:029d Razer USA, Ltd Razer Blade
```

I've signed and installed the driver on my own Razer Blade 14 2023 running Fedora. I've been able to change my keyboard and logo backlight behavior with RazerGenie, and the changes have persisted through multiple reboots.

Fixes #2087

### CODE REVIEW

**Comment by zac-freeman** [comment]
This pull request addresses this issue: https://github.com/openrazer/openrazer/issues/2087

**Comment by pramodhrachuri** [comment]
I have compared the changes with the commit https://github.com/openrazer/openrazer/commit/988668ecf55613e0818c9d539d4aea30bc30737e and it looks good. Exact same number and types of changes. 

I do not have a 2023 Blade 14 to verify though. As long as VID and PID matches, it should work.

**Review by z3ntu — APPROVED** [review]
Diff looks good, thanks!

Just to confirm all the functionality shown in the UI works correctly and as expected?

**Comment by zac-freeman** [comment]
Yes! I can confirm that all of the lighting options presented in the RazerGenie UI work as expected.

**Pull request merged**
