### PR TITLE
Added support for Huntsman Elite

### PR DESCRIPTION
**Pull request by sumpster**
The following effects were tested to be working:
none, wave, spectrum, static, starlight, breath, custom, reactive
set/get brightness

The keyboard seems to be compatible with Ornata / Cynosa.

### CODE REVIEW

**Comment by raptor2101** [comment]
Thanks and Kudos :+1:

**Comment by tildearrow** [comment]
I thought Huntsman didn't have hardware effects?

**Comment by sumpster** [comment]
@tildearrow I think that was a wrong impression created by usb captures from Synapse. Synapse will only use software based lighting on this keyboard as this is the new target architecture for Razer.

But I found plenty of hardware lightings still working on my keyboard with firmware v1.3.

Please see https://github.com/openrazer/openrazer/issues/617 for more details.

**Comment by BobbyBabes** [comment]
>The following effects were tested to be working:
none, wave, spectrum, static, starlight, breath, custom, reactive
set/get brightness

Are none, and static + set/get brightness configurable per key?
That's all I need. If so, I might still buy a Huntsman Elite.

**Comment by sumpster** [comment]
@BobbyBabes:
> Are none, and static + set/get brightness configurable per key?
> That's all I need. If so, I might still buy a Huntsman Elite.

I think what you are actually looking for is custom. Custom means that the color settings can be made for each key individually. This is working for me in the two examples provided: custom_zones.py and custom_starlight.py. (Brightness might only be adjustable per key by simply setting a darker color.)

Not sure though if there are easy to use high level tools supporting custom or if you have to set your keys via python. Got into this whole keyboard lighting thing by accident two days ago. :)

**Comment by BobbyBabes** [comment]
Yes, be able to configure each key with it's own unique RGB colour value.

So set/get brightness is only possible for all keys, not per key?
Python is okay to configure custom. As long as there are some examples or if it's clear from the source code.

**Comment by sumpster** [comment]
The way I understood things, brightness is global. 

But if your buying decision depends on this working, you should be aware that Razer might remove support for hardware lighting with a firmware update. (Again, their Synapse software is not using those functions and they are talking about freeing up resources on the keyboard controller.)  If you plan to also use the keyboard with Synapse, the keyboard might get updated/broken at a later point. I cannot tell you how likely or unlikely this is.

**Comment by BobbyBabes** [comment]
My buying decision doesn’t depend on global or custom per key brightness. I was just trying to get confirmation for my comprehension of what I read. No Synapse software necessary, nor wanted. I only need static per key RGB lighting. Once I setup 3 or so of these profiles they won’t change again.

**Comment by z3ntu** [comment]
@sumpster I built a "custom editor" into RazerGenie and polychromatic also has a similar feature but hidden under "profiles" iirc

Thanks for the PR! You should also try to fix your git config so the author name / email is correct.
If you say everything is working, I'll trust you :)

EDIT: Do wave work correctly in both directions?

**Review by terricain — APPROVED** [review]

**Comment by wavetyler** [comment]
@z3ntu I can confirm that wave works in both directions using @sumpster 's branch.

**Comment by sumpster** [comment]
> You should also try to fix your git config so the author name / email is correct.
@z3ntu Good point, didn't even see this.

And thank you guys for all the work you are doing in this project. Made getting this keyboard to work quite easy.

**Comment by raptor2101** [comment]
Works perfect on my side.

Positiv side effect: As soon as openrazor_driver sets a "simple" LightningMode, this mode is persisted over a powercycle.

No more psycodelic colering till Synapse3 start ....

**Comment by raptor2101** [comment]
Using the razerkbd-driver maps the media-keys to send other KeyEvents than with default driver.

XEV output Backward = keycode 106 (keysym 0xffaf, KP_Divide
XEV output Play/Pause = keycode 63 (keysym 0xffaa, KP_Multiply
XEV output Forward =  keycode 77 (keysym 0xff7f, Num_Lock
XEV output Mute = keycode 111 (keysym 0xff52, Up)

The wheel appears as button 4 and button 5 in XEV

**Comment by sumpster** [comment]
@raptor2101 Please try again.

**Comment by raptor2101** [comment]
@sumpster perfect!

**Comment by wavetyler** [comment]
@sumpster @z3ntu Any thoughts on being able to custom control the wrist pad lighting that comes with the huntsman?  Some of the presets in Polychromatic or RazerGenie will affect it, but no custom settings.

**Comment by sumpster** [comment]
@wavetyler It was mentioned by @edualm that the lights around the keyboard and rest are represented as additional key rows. I quickly checked and set the number of rows from 6 to 9 in keyboards.py (line 642) of openrazer_daemon. After this change the example program custom_startlight.py will happily light the sides of keyboard and rest. 

But this is just a hack. I can't seem to find any proper way to do it. Are there any existing keyboards in openrazer which support this?

**Comment by z3ntu** [comment]
Could one of you try setting the row count from 6 to 9 (as was written) and then follow https://github.com/z3ntu/RazerGenie/blob/master/README.md#how-to-compile and before running the `ninja` command, run `meson configure builddir -Dinclude_matrix_discovery=true` and then the `ninja` command, opening that freshly compiled version of RazerGenie, select your device, click the "open matrix discovery" button and then find which button triggers that LED you're searching for and telling me which one it is?

**Comment by sumpster** [comment]
> find which button triggers that LED

@z3ntu There is no such LED. It would seem two entire rows are dedicated to the lighting on the sides, because it is made up of many LEDs, each of which can be controlled independently.

The question is if anyone would want to manually control it on this level, or if it should be combined into a single setting for custom mode.

**Comment by sumpster** [comment]
@z3ntu Couldn't help it and played around some more. Seems all three rows are actually used. They are aligned as follows:
([row, col] each starting with 0, "..." is always col increments)

Keyboard top (left to right): [7, 0], [6, 0], ..., [6, 14]
Keyboard right: (top to bottom): [6, 14], ..., [6, 18]
Keyboard bottom: (left to right): [7, 4], ..., [7, 18], [6, 18]
Keyboard left: (top to bottom): [7, 0], ..., [7, 4]
Rest left (top to bottom): [8, 0], ..., [8, 2]
Rest bottom (left to right): [8, 2], ..., [8, 16], [8, 19]
Rest right (top to bottom): [8, 17], ..., [8, 19]

Additional notes:
When the wrist rest is attached, the bottom keyboard leds are not visible (but still lid). ([7, 5], ..., [7, 18])
Corner leds are always visible on both sides of the corner and therefore listed twice. (for example [7, 0] from top left corner is clearly visible on left side as well as top side. might even be two physical leds internally.)

You think it would be a good idea to just pass these rows through to client apps?

**Comment by raptor2101** [comment]
@z3ntu: something in the "pipeline" remaps the Mediakeys. (I syspect the openrazer_daemon/razor_mount)

iv downloaded and installed (via /scripts/build_debs.sh) the driver including this PR.

if i load the razorkbd packet manually (modprobe) all works fine. After starting the daemon the keys sends wrong Ids

**Comment by z3ntu** [comment]
1. It's Razer, not razor
2. The razer_mount script just rebinds the driver and changes the permissions, which is necessary.
3. The daemon is a separate thing and it probably sets the device into "driver mode" when the daemon is started.

**Comment by sumpster** [comment]
@raptor2101 Are the media keys wrong in in the same way as they were before my fix in the driver?

After I read your post I tried the media keys again on my machine and they were also not working for me. (Driver & daemon are loaded automatically on start here) The error was exactly as before. For me the keys started working again correctly after I restarted the daemon. (killall openrazer-daemon && openrazer-daemon)

Edit: I restarted my computer again and this time the daemon restart (attempted multiple times) did not solve the problem. Only killing it does. So perhaps in my first attempt it didn't actually restart for some reason.

@z3ntu What do you mean by switching the device in driver mode? How does this affect the data flow in the driver?

**Comment by raptor2101** [comment]
@z3ntu: razor vs razer... i always miss this thing :D

@sumpster: nope regarding to XEV they don't send signals at all, except the wheel, wich sends scroll signals.

you can fix this by rmmod raz**e**rkbd && modprobe raz**e**rkbd

**Comment by ryanphjohnson** [comment]
About when would this be released in a stable PPA? I have the huntsman elite and love it, but have a crap history at trying to get this stuff to work outside of a PPA. I'm running Linux Mint and have Polychromatic, so I'm super excited for this, but have no clue how long it'll be til I can use it. Huge thank you for getting this working!

**Comment by raptor2101** [comment]
@ryanphjohnson if you are interested, i can upload my generated dpkgs. not as good as ppa but you can omit the whole "build the sources yourself" stuff....

**Comment by ryanphjohnson** [comment]
@raptor2101 Yes, that would be awesome thanks!

**Comment by raptor2101** [comment]
@ryanphjohnson unzip and run dpkg -i *




[dist.zip](https://github.com/openrazer/openrazer/files/2780545/dist.zip)

**Comment by ryanphjohnson** [comment]
I think I'm still missing a piece of the puzzle, and I'm trying to figure out what it is. I see in the razer.logs file that the huntsman elite is listed:

 2019-01-21 21:02:49 | razer                          | DEBUG    | Loaded device specification: RazerHuntsmanElite ---------------------- (1532:0226)

but polychromatic isn't seeing it yet. To be more specific its saying 'A razer product is connected to your computer, but the daemon didn't detect it. It is possible your Razer product is not bound to the driver properly or it is not yet supported'. I'm wondering if I need to update polychromatic also so it can 'see' the huntsman elite too. I appreciate your time and effort so I don't want to abuse your time, but if you have any advice of what I might try next, I'd be extra appreciative :D

**Comment by ryanphjohnson** [comment]
Success! I had to reboot the whole machine, not just the daemon, but now it works PERFECTLY! Thank you for your awesome work! Cheers!

**Comment by sumpster** [comment]
> you can fix this by rmmod razerkbd && modprobe razerkbd

@raptor2101 Yes, this works for me too. Did some debugging and it turns out this is a nice trick to run openrazer-daemon without having the keyboard in driver mode. :) It seems the daemon misses the module reload and therefore does not switch it into driver mode again. But this also means there is no evident reason why the keyboard should be switched to driver mode to begin with.

Why is driver mode used? It appears openrazer-daemon & polychromatic work just fine without. Also all media keys are working nicely without it.

In default mode the media key event data looks like this:
Prev 02b60000000000000000000000000000
Play 02cd0000000000000000000000000000
Next 02b50000000000000000000000000000
Mute 02e20000000000000000000000000000
Vol+ 02ea0000000000000000000000000000
Vol- 02e90000000000000000000000000000

In driver mode it changes to this:
Prev 04540000000000000000000000000000
Play 04550000000000000000000000000000
Next 04530000000000000000000000000000
Mute 04520000000000000000000000000000

For prev, play, next and mute this is easy to fix as the data can be corrected in raw event handling.

The volume knob is the problem. It no longer generates any keyboard events, but instead reports as mouse wheel via a different usb endpoint. I am not sure if there is a sane way of correcting this. Anyone has any ideas?

**Comment by wavetyler** [comment]
So, if all changes are approved here, when do you feel like this will get merged in? @z3ntu

**Comment by z3ntu** [comment]
@sumpster You might want to associate your email address used by git (sump at sump dot org) with your github account so the commits get linked to your account.

**Review by z3ntu — APPROVED** [review]
LGTM

**Comment by sumpster** [comment]
@z3ntu I added the email address. 

What about the media key issue? This still isn't fixed for driver mode. (Because the volume events cannot be converted using the existing approach. See my comment above.)

**Comment by crispyreddis** [comment]
Does this fix will work with huntsman simple keyboard, not elite?

**Comment by sumpster** [comment]
@crispyreddis I only have the elite keyboard, so I cannot test it. Most likely it has a different device id which needs to be added to the driver. Not sure how much else needs to be changed for this model.

**Comment by vldfr** [comment]
Thank you! Good work! When will openrazer accept this pull request and add the Huntsman Elite to the official list?
P.S.: For anyone having trouble with polychromatic or other apps, just do a reboot.

**Comment by krsfx** [comment]
@sumpster played around with your PR, seems also to work for the BlackWidow Elite (1532:0228)

**Comment by IONKnight** [comment]
Thank you for the hard work this means alot to us all. Was about to return the keyboard when I saw this pull request, means I don't have to deal with the rainbow effect.

**Comment by abhishek376** [comment]
@sumpster Thanks for the drivers. I'm on Redhat 7/Python2 so rewrote all the phyton 3 stuff to python 2. I was able to load the driver but in megs I see

[ 3634.225603] input: Razer Razer Huntsman Elite as /devices/pci0000:00/0000:00:14.0/usb3/3-10/3-10:1.1/input/input55
[ 3629.247167] razer driver: Device data transfer failed.
[ 3634.225678] razerkbd: Response doesn't match request. Start Marker: 00 id: 00 Num Params: 00 Reserved: 00 Command: 00 Params: 00000000000000000000000000000000 

I checked the razer_mount and daemon logs but nothing useful. The keyboard doesn't work with the open_razer driver. Not sure where to go from here :(

**Comment by z3ntu** [comment]
Please rebase on master as another PR was merged in the meantime.

**Review by z3ntu — APPROVED** [review]
Rebased it for you. LGTM

**Pull request merged**
