### PR TITLE
Add support for Razer Chroma Addressable RGB Controller

### PR DESCRIPTION
**Pull request by hobeone**
Also reworks the API to have code duplication based on the request from @z3ntu 

Tested on Debian Testing with Polychromatic.

Builds on #1762, synced to current master

### CODE REVIEW

**Comment by z3ntu** [comment]
Thanks for the changes! I made some additional changes, mostly cleanup and pushed them to this branch. Please test again.

I've also noticed that all the `razer.device.lighting.channel` methods didn't actually work on daemon side so I've fixed that. Please explicitly test `getChannelBrightness`, `setChannelBrightness`, `getChannelSize` and `setChannelSize` from e.g. d-feet application or from command line e.g. qdbus

Also I believe the effect sync feature is not working with this device, mostly because the API is a bit different. Please check that and maybe fix in a followup PR (I won't block this PR because of this)

**Comment by hobeone** [comment]
synced your changes, rebuilt and reinstalled.

Polychromatic still works.

Ran d-feet and tested the get* and set* methods.  It all seems to work as it should.  The channels are not zero indexed though so getChannelSize(0) returns an error.  Is that expected?

Also there's no getNumChannels() or equivalent so you wouldn't know how many channels to query without iterating until you get an error.

Otherwise I think this is good to go.

**Comment by z3ntu** [comment]
> The channels are not zero indexed though so getChannelSize(0) returns an error. Is that expected?

From the current code, yes. But I don't really see an immediate reason why we shouldn't use 0-index here. @CalcProgrammer1 @brett-smith do you have any insights here why they were made 1-indexed?

> Also there's no getNumChannels() or equivalent so you wouldn't know how many channels to query without iterating until you get an error.

Great point, this should be fixed! I'd say adding an attribute in the device class in the daemon and making a dbus API that returns that should be good. Like DPI_MAX (or MAX_DPI?) or MATRIX_DIMS

**Comment by brett-smith** [comment]
It's been a while since I looked, but I seem to remember that's how they were numbered in the hardware, i.e. what was sent in the USB packets.  To set the first channel, you send a `1`.  No reason to prevent openrazer presenting it as channel zero though. 

Also, apologies for being silent on this PR's predecessor. It's been a crazy year and have had too much else on for the fun stuff :( .   So thanks for pushing this to completion.

**Comment by hobeone** [comment]
If that's how it shows up in the usb packets I think we should keep it 1 indexed.

Is the number of channels already captured as the first element of MATRIX_DIMS?

**Comment by brett-smith** [comment]
> Is the number of channels already captured as the first element of MATRIX_DIMS?

Good point, yes it is!

**Comment by hobeone** [comment]
Great.  Added a get_num_channels method and exposed through dbus

**Comment by z3ntu** [comment]
> Is the number of channels already captured as the first element of MATRIX_DIMS?

I've modified it to use a new variable (`NUM_CHANNELS`), just to be a bit more flexible in the future.

Thanks for testing again, I think this is ready to go!

**Pull request merged**
