### PR TITLE
Preliminary support for BlackWidow Classic under PID 0x010e

### PR DESCRIPTION
**Pull request by simcop2387**
Preliminary support for BW classic with a PID of 0x10e.

I can't figure out how to get the macro keys working but suspect this might be because I'm just not that familiar with the driver yet.  If I figure it out, I'll add it to this PR or make a new one if this is merged.

### CODE REVIEW

**Comment by terricain** [comment]
Bind the device to driver, then do `echo -ne '\x03\x00' > device_mode`, then run `xev` and see if the macro keys emit any key codes

**Comment by simcop2387** [comment]
Yep that makes them work, after that they generate XF86Tools, and XF86Launch5 through XF86Launch8

**Comment by terricain** [comment]
Deal with merge conflicts and ill commit, I cba ha

**Comment by simcop2387** [comment]
Done, did it with the github editor here so I hope I actually commited that correctly.  It was a duplicated def for the STEALTH from my branch so I just removed that.

**Comment by terricain** [comment]
You tested everything? add entry to readme.

**Comment by terricain** [comment]
Bump, I'm being impatient today

**Comment by z3ntu** [comment]
@simcop2387 Do you know if the Mac edition has a different usb id?

**Pull request merged**
