### PR TITLE
Add support for Razer Blade Stealth (Early 2020)

### PR DESCRIPTION
**Pull request by j4nk3e**
Added support for the Blade Stealth Early 2020. This is essentially the same as the late 2019.

Not 100% sure about the `device_serial` in _fake_driver. Just added it in the end. I noticed there are also missing some models.

### CODE REVIEW

**Comment by TheButlah** [comment]
Does this work with the Advanced model or the Base model? Does it matter?

**Comment by j4nk3e** [comment]
I tested it on the base model. Don't know if there's a difference to the touch screen variant.

**Review by z3ntu — APPROVED** [review]
LGTM, can you confirm that all functionality works as expected?

**Comment by j4nk3e** [comment]
I tested it on the 2020 base model and everything works fine. Can't say anything about other devices due to a lack of hardware (=

**Comment by User-TRON** [comment]
New here so not sure if this is the appropriate place to comment or if this is helpful, but just tested this on my 2020 4k-touch 1650ti Razer Stealth and it worked great!

**Comment by z3ntu** [comment]
Thanks a lot!

**Comment by SealedJoy** [comment]
I notice there are only a 3 effects shown for the Razer Blade Stealth 13" early 2020, which are all single zoned control. Eg Spectrum which cycles the spectrum (all leds one color at a time)

I have tried a few other open source razer blade chroma control projects (and the propriety nvidia control stuff) and know that the keyboard is definitely not the single-zoned-rgb that openrazer currently presents it as.

In polychromatic, razergenie, razercommander it all shows as a single zone rgb keyboard.
I believe this is because the keyboard hardware doesn't actually support individual key rgb, however i know the hardware is still capable of many more complicated effects requiring multiple led zones - ones i have ran on this keyboard are:  wave effect, and color gradients, audio reactive, screen continuation.

Therefore I think openrazer is missing out on many more possible effects for this keyboard

**Comment by z3ntu** [comment]
@SealedJoy If you won't or cannot work on fixing this, please file a new issue detailing your observations.

**Pull request merged**
