### PR TITLE
Add support for Razer Blade 2018 Base Model

### PR DESCRIPTION
**Pull request by KrisHedges**
Changes to be committed:
	modified:   README.md
	modified:   daemon/openrazer_daemon/hardware/keyboards.py
	modified:   driver/razerkbd_driver.h
	modified:   install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
	modified:   install_files/udev/99-razer.rules

### CODE REVIEW

**Comment by KrisHedges** [comment]
A little help here...
CI says...
```
[!] ./daemon/openrazer_daemon/hardware/keyboards.py does not respect the agreed coding style.
```
But I don't see any problems with my additions. Following the automated ci suggestion...and running 
```
autopep8 --max-line-length 500 --ignore E402 daemon/openrazer_daemon/hardware/keyboards.py
```
Yielded no changes to the file.

**Comment by z3ntu** [comment]
I've committed the auto formatting change for you. 
With autopep8 you have to also use the "-i" flag to make changes "in place". I should probably improve the CI scripts to say that^^

**Comment by KrisHedges** [comment]
Awesome thank you. Yeah that’d be great. I’m pretty unfamiliar with python and it’s tooling but the build scripts here were pretty intuitive. Maybe add the autopep as a dev dependency in the wiki and possibly the local build scripts?

**Comment by gaborpapp** [comment]
It works well. Thank you!

**Comment by z3ntu** [comment]
Please fix the CI failure(s) so this can get ready.

**Comment by KrisHedges** [comment]
There we go. Done.

**Review by z3ntu — APPROVED** [review]
I've changed the ordering of a few lines, LGTM

**Pull request merged**
