### PR TITLE
Initial Support for Naga Lefthanded edition 2020.

### PR DESCRIPTION
**Pull request by hendy643**
Adds Initial support for Naga Left-Handed Edition 2020. Partial fix for #1232.

**Working**:
Logo lighting - Spectrum, Wave, Reactive, Static.
Wheel lighting - Spectrum, Wave, Reactive, Static, Breath.
Logo and Wheel - brightness
DPI upto 20000
Polling Rate upto 1000Hz

**Not Working**:
Side button mapping or lighting.

**Warning**:
BUG: Device 0003:1532:008D.000C has already been found with interface 0003:1532:008D.0009. Skipping

Edited 17-Dec:
Only tested on Ubuntu 20.04.

### CODE REVIEW

**Comment by filipagh** [comment]
hello im 1. time using openrazer, and after build and install openrazer from your repo, i do not see my mouse in client,
i have `1532:008d Razer USA, Ltd Razer Naga Left Handed Edition`

what client do you use i have `snake` `RazerGenie`
also i use arch linux (manjaro)
thanks for info

**Comment by hendy643** [comment]
Hi. I'm using [polychromatic](https://polychromatic.app/) daily builds.

**Comment by filipagh** [comment]
same result :/ 
i do not see any problem in logs 
and base on [trubleshooting wiki](https://github.com/openrazer/openrazer/wiki/Troubleshooting) all parts are ok (builded form your fork)

any idea ?

**Comment by hendy643** [comment]
If you could try running polychromatic-git from the AUR, I'll dig deeper tonight after work. (UK Time).

**Comment by filipagh** [comment]
git version did not help
does mouse have some driver like `razerkbd`?

**Comment by cylgalad** [comment]
I used the wiki entry [Building a package](https://github.com/openrazer/openrazer/wiki/Building-a-package#arch-linux) to build and install it and rebooted.
For arch users struggling to properly build the packages, in `PKGBUILD` change the `source` line to:
 `source=("git+https://github.com/hendy643/openrazer.git#branch=feature_naga_letfhanded_2020_0x008d")`

The mouse is detected, but I can't change any settings in polychromatic (or others), while `examples/custom_zones.py` works, including the keypad. I changed that script to have some static colors to my liking, better than nothing!

**Comment by hendy643** [comment]
> git version did not help
> does mouse have some driver like `razerkbd`?

I image it does, and that is what the warning I identified in the commit message is about. I've not looked at that yet.

**Comment by filipagh** [comment]
after rebuild and reinstall it found mice, any hope for side button mapping ?

**Comment by cylgalad** [comment]
I found why I couldn't change anything: in-mouse profiles! I used a non-default profile, switching to the main profile worked.
I've done some changes, here's the patch [openrazer_naga2020lhe.patch.zip](https://github.com/openrazer/openrazer/files/5719802/openrazer_naga2020lhe.patch.zip)
The most useful change is in `mouse.py`: `MATRIX_DIMS = [1, 3]`
The "thumb grid" lighting does work, you need to use next-gen polychromatic (dev-1.0.0-pyqt5 branch).
Now I have a bug: I can't set dpi higher than 16000 for some reason, no big deal since it's way too high for my setup.

**Comment by z3ntu** [comment]
Please fix the diff, e.g. `daemon/openrazer_daemon/hardware/mouse.py` has something done to it - maybe line endings?

Also you can rebase on git master so DPI values above 16000 work.

**Comment by hendy643** [comment]
@z3ntu It was the line endings.

**Comment by hendy643** [comment]
Closed to reopen after rebasing off master

**Pull request closed without merging**
