### PR TITLE
Add Razerblade 2018 support

### PR DESCRIPTION
**Pull request by codabrink**
Add 2018 model support.

### CODE REVIEW

**Comment by codabrink** [comment]
I am not sure what it's referring to when it ambiguously errors out with "Does not respect the agreed coding style." in `keyboards.py`. The added class looks identical in formatting to the other classes.

**Comment by terricain** [comment]
Tested every one of the features?

**Comment by codabrink** [comment]
Yes, I found the "formatting error", each class needs two newlines between them.

**Comment by z3ntu** [comment]
You can just run `autopep8 --recursive --in-place --max-line-length 500 .` to format everything.

**Comment by codabrink** [comment]
Hm. Travis is reporting a pass - Github isn't reflecting that update.

**Comment by codabrink** [comment]
@terrycain This is good and functioning. Tested on my own laptop. Are we okay to merge?

**Review by z3ntu — APPROVED** [review]
LGTM

**Comment by terricain** [comment]
:+1:

**Pull request merged**
