### PR TITLE
Add support for Razer DeathStalker V2 PRO TKL #1990

### LINKED ISSUE #1990: Support for Deathstalker V2 PRO TKL
### Device Info

* Name: Deathstalker V2 PRO TKL
* Product Number: RZ03-04370100-R3M1
* Model Number: RZ03-0437
* 
### Device Information
```

Bus 001 Device 028: ID 1532:0298 Razer USA, Ltd DSV2Pro TKL
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0298 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 DSV2Pro TKL
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x006d
    bNumInterfaces          4
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     177
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      75
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      22
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)
```

```
lrwxrwxrwx 1 root root  10 Dec 28 00:07 usb-Razer_DSV2Pro_TKL-event-if01 -> ../event26
lrwxrwxrwx 1 root root  10 Dec 28 00:07 usb-Razer_DSV2Pro_TKL-event-kbd -> ../event12
lrwxrwxrwx 1 root root  10 Dec 28 00:07 usb-Razer_DSV2Pro_TKL-if01-event-kbd -> ../event13
lrwxrwxrwx 1 root root  10 Dec 28 00:07 usb-Razer_DSV2Pro_TKL-if02-event-mouse -> ../event27
lrwxrwxrwx 1 root root   9 Dec 28 00:07 usb-Razer_DSV2Pro_TKL-if02-mouse -> ../mouse5

```

<details>

```
001:028:003:DESCRIPTOR         1672183378.174976
 05 0C 09 01 A1 01 06 00 FF 09 02 15 00 25 01 75
 08 95 5A B1 01 C0

001:028:002:DESCRIPTOR         1672183378.176019
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05
 01 09 38 75 08 95 01 81 06 09 30 09 31 16 00 80
 26 FF 7F 75 10 95 02 81 06 C0 C0

001:028:001:DESCRIPTOR         1672183378.177592
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 19 00 29 A0 15 00 25 01
 75 01 95 A0 81 02 05 08 19 01 29 03 15 00 25 01
 75 01 95 03 91 02 95 05 91 01 C0 05 0C 09 01 A1
 01 85 02 19 00 2A 3C 02 15 00 26 3C 02 95 01 75
 10 81 00 75 08 95 13 81 01 C0 05 01 09 80 A1 01
 85 03 19 81 29 83 15 00 25 01 75 01 95 03 81 02
 95 05 81 01 75 08 95 14 81 01 C0 05 01 09 00 A1
 01 85 04 09 03 15 00 26 FF 00 35 00 46 FF 00 75
 08 95 15 81 00 C0 05 01 09 00 A1 01 85 05 09 03
 15 00 26 FF 00 35 00 46 FF 00 75 08 95 15 81 00
 C0

001:028:000:DESCRIPTOR         1672183378.178794
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

```

</details>

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
deathstalker_v2_pro_tkl_1
deathstalker_v2_pro_tkl_2
deathstalker_v2_pro_tkl_3

### PR DESCRIPTION
**Pull request by stlhrt**
Fixes #1990

### CODE REVIEW

**Comment by stlhrt** [comment]
Wireless version doesn't work very well ...
Chroma changes have no effect, firmware version etc. are not properly read and battery level is not available.

**Comment by z3ntu** [comment]
Perhaps for wireless you can try the `case` with `RAZER_BLACKWIDOW_V3_WIRELESS_WAIT_MIN_US` as that uses a longer sleep before asking for response command which is required on some wireless devices.

For the wired version everything works well?

**Comment by stlhrt** [comment]
Wait times didn't help.
As for wired version all basics work apart from:

   - Ripple effect
   - Game mode toggle
   - Lower brightness toggles microphone
   - Increase brightness has no effect
   - Media button

**Review by digitwolf — APPROVED** [review]

**Comment by z3ntu** [comment]
Maybe try even longer sleeps? I just know that various devices need insane waiting times until they have a response back

**Comment by nightsky30** [comment]
> Wait times didn't help. As for wired version all basics work apart from:
> - Game mode toggle

I know the Deathstalker V2 is listed above these fallthrough statements, and it is common to use other devices as a sort of template when adding openrazer support. But, there have been some razer devices which have Pro/Non-Pro variants that should behave similarly and don't. An example that applies here is the BlackWidow V3 and BlackWidow V3 Pro. Game Mode Toggle is implemented differently with these two seemingly similar models. The same might be happening here with the Deathstalker V2 and Deathstalker V2 Pro TKL. You might try moving the Deathstalker V2 Pro TKL case statements below the `fallthrough` statements in these two sections to see if that fixes Game Mode Toggle on this device.

https://github.com/openrazer/openrazer/blob/2927953f802e3a12163248518c3b4539979f3acb/driver/razerkbd_driver.c#L3451-L3461

https://github.com/openrazer/openrazer/blob/2927953f802e3a12163248518c3b4539979f3acb/driver/razerkbd_driver.c#L3848-L3858

**Pull request closed without merging**
