### PR TITLE
Add Diamondback Chroma and DeathStalker Chroma

### PR DESCRIPTION
**Pull request by CalcProgrammer1**
I have tested the Diamondback and the DeathStalker Chroma.

The Diamondback works just like the Mamba TE except with a 21 LED matrix rather than a 16 LED matrix.  The LED array column 0 is the top right LED and continues down and around and up the left side to LED array column 18.  Column 19 is the logo LED and column 20 is the scroll wheel LED.

The DeathStalker does not have per-key backlighting and functions more like the mice and Firefly than the other keyboards.  I discovered that despite only having 6 zones exposed in the official Chroma SDK, it really has 12 controllable LEDs with every two LEDs blended together to light one zone.  If you set them to two very different colors, you will get a mess.  It can be used to make smoother gradients though.  Treat it like a Firefly with 12 columns when using custom effects, otherwise it works like the other keyboards.

IMPLEMENTED:  Addition of these two devices to driver, changes to get custom effects working with these devices

TESTED:  All lighting modes except Reactive including custom effects, serial number, device type, firmware version requests, actual usage as keyboard/mouse, game mode LED, macro mode LED and macro mode LED effect

NOT TESTED:  Macros, key remaps, game mode, reactive effects, DPI changes, any other special non-lighting related stuff

NOT IMPLEMENTED:  Daemon/application layer stuff

### CODE REVIEW

**Comment by terricain** [comment]
You haven't added lines to create and remove device files for the deathstalker. You mind joining the telegram chat? I could do with someone testing the daemon.

**Comment by CalcProgrammer1** [comment]
The default cases work for the Deathstalker (looks like they are used for BW Chroma as well?).  I added the DeathStalker Chroma explicitly though.

**Comment by CalcProgrammer1** [comment]
Also, where is this Telegram chat?  I've never used Telegram before.  I'd be happy to test and experiment but my programming expertise is mainly in C/C++ and low level stuff.  My application does not use the daemon, it talks directly to the kernel driver using the /sys/bus/hid/... interface files, hence why I haven't tested the daemon with my fork.  I haven't looked in to how to use the daemon at all.

**Comment by terricain** [comment]
Go onto telegram, make an account and add `@terrycain` and i'll add you to the group. Daemon `shouldn't` be too much work, now its mainly copy and paste as most of the functionality already exists there.

**Comment by terricain** [comment]
Will look at the driver properly in early Jan should be good though

**Comment by terricain** [comment]
Closed as merged to a branch, have created an issue here - https://github.com/terrycain/razer-drivers/issues/137

**Pull request closed without merging**
