### PR TITLE
Add support for Razer Naga Epic

### LINKED ISSUE #197: Razer Naga Epic support
Linux device identifier: 1532:001F
Product ID: RZ01-005101
12 Macros

### PR DESCRIPTION
**Pull request by z3ntu**
Fixes #197

For installation instructions see https://github.com/openrazer/openrazer/wiki/Building-a-package

### CODE REVIEW

**Comment by z3ntu** [comment]
@SeanHubs (continuing from #1409) You have tested all the functionality available for the mouse? DPI, poll rate, lighting, battery level? Can you please also provide a screenshot of e.g. polychromatic with your mouse?

**Comment by SeanCreations15** [comment]
I have tested all available functionality:
1. Under lighting Effects with Polychromatic
- Mouse lighting effects, has two options:
'Static' or 'Spectrum'

Static does not work, I cannot manually set a colour for the mouse.
Spectrum works, although I have a feeling as Spectrum is the default of the mouse ootb, this may just be expected functionality.


2. The brightness slider:
- This does nothing, from 0 to 100, nothing changes.

3. DPI Slider:
- This DOES work, however after I've move the slider to the number I want, the graphics bounce back to '1800' (Which is the default). However this does not change the dpi, it stays at the chosen DPI, just displays as 1800 once again.

4. Polling Rate:
- Does not work, setting to 1000:
Average polling rate of 915
- Setting to 125:
Average polling rate of 915

In the overview, it is currently displaying the Correct Serial Number which is good.

Screenies:
1. Polychromatic Main Display:
https://imgur.com/a/cwicrzY

2. Polychromatic Lighting Effects:
https://imgur.com/a/ZwbYSjP

3. Polychromatic Overview:
https://imgur.com/a/so8SqVX

4. Polychromatic Preferences, Daemon:
https://imgur.com/a/v8XTBQa

**Comment by z3ntu** [comment]
Interesting that it doesn't work for you because this branch worked for someone previously:

> Lighting (both Spectrum/Static), Brightness, DPI, and Polling Rate are all working and configurable

**Comment by z3ntu** [comment]
Feedback I have gotten on this:

Wireless doesn't work, "Bus 001 Device 004: ID 1532:0021 Razer USA, Ltd Razer Naga Epic Dock"

"All of the listed options worked, there was no section to make macros."

**Comment by ChaoticAce** [comment]
Can also confirm that this branch works for both wired and wireless mode. In order to get it running I had to remove the following packages:
```
razergenie-git
polychromatic-git
openrazer-meta-git
openrazer-driver-dkms-git 
openrazer-daemon-git 
python-openrazer-git 
```

Once removed I reinstalled the following packages with a modified PKGBUILD file:
```
openrazer-meta-git
openrazer-driver-dkms-git 
openrazer-daemon-git 
python-openrazer-git 
```

`PKGBUILD` File modifications: 
```
# source=("git+https://github.com/openrazer/openrazer.git")
source=("git+https://github.com/openrazer/openrazer.git#branch=feature_nagaepicchroma_0x003e")
```

Then I reinstalled the packages below and rebooted my machine:
```
razergenie-git
polychromatic-git
```
Both `polychromatic` and `razergenie` recognized my mouse after a reboot. I was able to modify Mouse: Brightness, Pollrate, sleep mode, lower power mode and DPI. Scroll Wheel: Brightness, Spectrum/static. Backlight, and all color zones. Glad to finally be able to modify my mouse. I haven't tried keymapping yet

**Comment by catalli** [comment]
Note for people for whom this isn't working (maybe @SeanHubs ?), is your version of Polychromatic looking for effects in the right place? Because the working lighting effects for the Naga Epic (at least in my install of this branch) are under `device.fx.misc.scroll_wheel`, where `device` is the object corresponding the mouse gotten from `device_manager.devices`, not directly under `device.fx`.

**Comment by catalli** [comment]
Since I was told to comment this, the value for `brightness` and the functions `static(R,G,B)` and `spectrum()` belonging to `device.fx.misc.scroll_wheel`, where `device` corresponds to the Razer Naga Epic in wired mode (with ID `1532:001f`) gotten from the openrazer device manager object, all work as expected (control lighting for the entire mouse). I have not tested this in wireless mode as my battery is dead. No other effects are implemented that I can see (and the Naga’s definition in `mouse.py` seems to imply no others are). As a side note, I can’t seem to use the side keypad with the switch on the underside set to NUM, only to 123.

**Comment by z3ntu** [comment]
@catalli So it doesn't work with polychromatic but it works directly via Python API?

**Comment by catalli** [comment]
@z3ntu I’ve never used Polychromatic so I couldn’t say for certain, but calling the two methods I described directly through a python script does work as expected. Though, as an additional note, openrazer doesn’t seem to “save” the Naga Epic’s effect status like it seems to with other devices. My Kraken lights up with the same effect I last set it to whenever I plug it in to my laptop (though plugging it directly into a power source just sets the lighting back to green), but my Naga always initially sets itself to the static blue color I think I may have set it to when I last used synapse ~5 years ago, until I run a command to change its state. I don’t know if this is expected behavior.

**Comment by z3ntu** [comment]
Could you please try either polychromatic or RazerGenie? Since that's the way most people control their devices it would be nice if you could confirm it works with that.

If that works fine I think we can merge this.

**Comment by francisco-polaco** [comment]
Hey!

I'm using my old Razer naga epic on my linux laptop. This PR would be really cool to be merged. What do we need to make it happen?

**Comment by francisco-polaco** [comment]
Bump

**Comment by z3ntu** [comment]
@francisco-polaco Please test it, see https://github.com/openrazer/openrazer/wiki/Building-a-package

Otherwise we don't know if it actually works correctly.

**Comment by w-j-r** [comment]
https://github.com/openrazer/openrazer/issues/197#issuecomment-2171871356

My comment about this above and with screenshot of RazerGenie. I had issue getting Polychromatic to work/detect mouse, I will probably revisit this in future.

I have two of these mice, both are `1532:001f Razer USA, Ltd Naga Epic (Wired)`. Changing DPI, poll rate, and brightness settings works for both of them without any issue.

**Comment by z3ntu** [comment]
@w-j-r Could you let me know what exact error you're getting when changing effects? If you launch razergenie from the terminal you should see the messages in the terminal there.

**Comment by w-j-r** [comment]
> @w-j-r Could you let me know what exact error you're getting when changing effects? If you launch razergenie from the terminal you should see the messages in the terminal there.

When setting the option to "Spectrum"
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Translation loaded: false
Invalid backend value. Using openrazer backend.
libopenrazer: There was an error checking if the daemon is enabled. Unit state is: not-found
. Error message: 
Device image for "Razer Naga Epic" is missing.
libopenrazer: There was an error in virtual void libopenrazer::openrazer::Led::setSpectrum()
libopenrazer: org.freedesktop.DBus.Python.OSError
libopenrazer: OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/openrazer_daemon/dbus_services/dbus_methods/nagahexv2.py", line 300, in set_scroll_spectrum
    with open(effect_driver_path, 'w') as effect_driver_file:
OSError: [Errno 22] Invalid argument

Failed to change effect
```

Setting to "static" mode
```
libopenrazer: There was an error in virtual void libopenrazer::openrazer::Led::setStatic(openrazer::RGB)
libopenrazer: org.freedesktop.DBus.Python.OSError
libopenrazer: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/openrazer_daemon/dbus_services/dbus_methods/nagahexv2.py", line 282, in set_scroll_static
    with open(rgb_driver_path, 'wb') as rgb_driver_file:
OSError: [Errno 22] Invalid argument

Failed to change effect

```

When trying to set static color
```
libopenrazer: There was an error in virtual void libopenrazer::openrazer::Led::setStatic(openrazer::RGB)
libopenrazer: org.freedesktop.DBus.Python.OSError
libopenrazer: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/openrazer_daemon/dbus_services/dbus_methods/nagahexv2.py", line 282, in set_scroll_static
    with open(rgb_driver_path, 'wb') as rgb_driver_file:
OSError: [Errno 22] Invalid argument

Failed to change effect
```

**Comment by z3ntu** [comment]
@w-j-r My bad, that's fixed now.

Also if you build RazerGenie from git master branch ("How to compile" https://github.com/z3ntu/RazerGenie/?tab=readme-ov-file#how-to-compile) then you get some extra tabs with e.g. low battery threshold.

But if you also have polychromatic installed, that should be able to change it the same way.

**Comment by w-j-r** [comment]
> @w-j-r My bad, that's fixed now.
> 
> Also if you build RazerGenie from git master branch ("How to compile" https://github.com/z3ntu/RazerGenie/?tab=readme-ov-file#how-to-compile) then you get some extra tabs with e.g. low battery threshold.
> 
> But if you also have polychromatic installed, that should be able to change it the same way.

Can confirm, the light settings work now.

**Comment by z3ntu** [comment]
@w-j-r Thanks for testing!

I did another small fix now, could you check if e.g. in polychromatic the "Sleep mode after" and "Enter low power at" sliders work well? (In RazerGenie you'd need to build an unreleased version, as written in my last comment)

If so, I think this PR is finally ready!

**Comment by w-j-r** [comment]
> @w-j-r Thanks for testing!
> 
> I did another small fix now, could you check if e.g. in polychromatic the "Sleep mode after" and "Enter low power at" sliders work well? (In RazerGenie you'd need to build an unreleased version, as written in my last comment)
> 
> If so, I think this PR is finally ready!

Yes I should have plenty of time tomorrow to try it all out. Btw I did try compiling razergenie today from github and from the AUR and the compilation kept failing. I don't know if this info is any use right now since I am not at my PC and can't send you the error output.

**Comment by z3ntu** [comment]
When building on Arch I'm guessing you need the latest libopenrazer package also so build and install libopenrazer-git, then build and install razergenie-git

**Comment by z3ntu** [comment]
Great you got the new RazerGenie version working!

> One thing to note here is that in the RazerGenie UI it allows me to set the percentage all the way up to 100%, however if I close and open the program again it will default back to 25%. If I set the setting lower than 25% it will stay, so that makes me think the device won't allow a value higher than 25%?

Can you check `dmesg` if there's any message from it? If not I'd say the device silently discards higher values than 25%. If there's some messages in dmesg from razermouse then (depending on the message I guess) the device rejects the values with error but since our error handling inside the stack is quite lacking you never know it didn't work.

But in any case, it sounds like the PR is as good as ready!

**Comment by z3ntu** [comment]
More than 7 years since #197 was opened and work on this has started by Terri :)

Thanks for testing!

**Comment by w-j-r** [comment]
> More than 7 years since #197 was opened and work on this has started by Terri :)
> 
> Thanks for testing!

`dmesg -W` turned up nothing, only shows when the mouse is connected/disconnected. I am just going to go with it doesn't accept values higher than 25%, I think that would make sense anyway. 

Yes! This 12 year old mouse is finally getting its support for me and maybe the one other who uses it in 2024 :D! I probably could have been of help years sooner tbh. For a while I did use the first mouse with my laptop but I had never bothered to look for drivers for it on linux since it worked well enough. This time I have only just opened the second mouse...it is still brand new. I am now just getting around to using it for my desktop since my Corsair Scimitar is about to bite the dust. Thank you guys, I'll be using the drivers until this mouse is done.

**Comment by z3ntu** [comment]
> dmesg -W turned up nothing, only shows when the mouse is connected/disconnected. I am just going to go with it doesn't accept values higher than 25%, I think that would make sense anyway.

Okay yeah.. If it's bothering you you can open an issue in the RazerGenie repo about this and I can take a look later.

Also support is better late than never, I'm happy this is finally done!

**Pull request merged**
