### PR TITLE
Fix #430: Improve the plugdev group check

### LINKED ISSUE #430: Group membership ID error
Right now openrazer-daemon checks for group membership for the user running the daemon by parsing the file /etc/group. This is wrong and should not be done since there are other ways to specify group membership for a user (ldap, sssd, etc), in which case, the group membership isn't correctly identified.
(I personally use pam_sssd for group membership and I was already in the plugdev group, but the daemon kept saying that I wasn't member)

### PR DESCRIPTION
**Pull request by z3ntu**
Fixes #430

### CODE REVIEW

**Comment by terricain** [comment]
Tested on Ubunut?

**Comment by z3ntu** [comment]
No (or maybe if @r3pek uses that)

**Comment by r3pek** [comment]
@z3ntu @terrycain Arch

**Comment by terricain** [comment]
@r3pek Meh the diff looks k, feel free to merge

**Pull request merged**
