### PR TITLE
Add support rbg starlight for blade kbd and others

### PR DESCRIPTION
**Pull request by XinqiBao**
Add support for different modes' starlight for blade laptop and some other keyboard

Tested equipment: **Razer Blade Stealth Late 2017**
TODO: test for others

Ref:
`razer_attr_write_mode_static(...)` from `driver/razerkbd_driver.c`

-------------------------------------------separate line-------------------------------------------
Welcome to test these devices below, once fully tested and succeeded, please leave a comment or ping me by email, so I can update this list, thanks!
  
- [x] RAZER BLADE STEALTH LATE 2017
~~RAZER BLACKWIDOW ULTIMATE 2016
RAZER BLACKWIDOW X ULTIMATE
RAZER BLADE STEALTH
RAZER BLADE STEALTH LATE 2016
RAZER BLADE STEALTH MID 2017
RAZER BLADE QHD
RAZER BLADE PRO LATE 2016
RAZER BLADE 2018
RAZER BLADE 2018 MERCURY
RAZER BLADE 2019 ADV
RAZER BLADE MID 2019 MERCURY
RAZER BLADE LATE 2016
RAZER BLADE PRO 2017
RAZER BLADE PRO 2017 FULLHD~~

-------------------------------------------update-------------------------------------------
bladeStealthLate2017 has been fully tested for this feature.
Reset changes for untested devices, whoever want to add this feature to above devices, can reference my earlier changes on this branch.

### CODE REVIEW

**Comment by z3ntu** [comment]
Can you ping some people that contributed changes to those models in the past so this PR can be tested?

**Comment by XinqiBao** [comment]
For those device don't have a config file `dev_attr_matrix_effect_starlight`, removed implementation for this feature.

**Comment by nightsky30** [comment]
@XinqiBao I saw your note in #813.  I don't own any blades myself(I would help test if I could), but encountered issues with starlight in the past.  I think your commit will be very helpful. :)  I just wanted to add that I noticed some blade devices such as the QHD only list 'set_starlight_random_effect' while other blade devices list random, single, and dual.  An example of missing single and dual methods:

https://github.com/openrazer/openrazer/blob/8fc3f0a46916ce30d7c81393b7d6c9cd1bc0225e/daemon/openrazer_daemon/hardware/keyboards.py#L602

I'm not sure why some lack the single and dual effect methods there.  I would think they should support all three starlight effects.  You may want to ensure all three effects are added/present for each blade model to be sure they are tested fully.

**Comment by XinqiBao** [comment]
Thanks to @nightsky30 , I have added daemon access for three starlight mode to those device.

Even though I can find these options in RazerGenie with [this diff](https://github.com/nightsky30/RazerGenie/commit/0830af83a0cec485b2e01363145f7b8896fa3012?diff=unified) by @nightsky30 , no effect on keyboard by switching to starlight, neither on daemon log. Perhaps this may have to work with other diffs, didn't dig too deep yet.

But still can be tested by writing to driver file directly.

**Comment by nightsky30** [comment]
@XinqiBao You're welcome :)  Ah, yeah that's from my fork.  I think that was the only commit.  You should be able to use that, or the official Polychromatic stable also has starlight available.

**Comment by jmachen** [comment]
I will try to test this tonight and I can start by reiterating what I have said in other PRs, for both my Razer Blade Stealth (2016) and my Black Widow Chroma TE:

- All three starlight modes work properly in Windows
- All three starlight modes produce a monochrome starlight effect with openrazer

I would be very happy to see this resolved.

**Comment by XinqiBao** [comment]
Due to the lack of test devices, I have reset these changes.
Keeping changes for bladeStealthLate2017, this has been fully tested.

**Comment by z3ntu** [comment]
@jmachen Can you please file a new issue and attach a pcap of Windows doing starlight effect and another pcap of OpenRazer doing the starlight effect? Thanks!

**Review by z3ntu — APPROVED** [review]
LGTM, thanks!

**Comment by jmachen** [comment]
> 
> 
> @jmachen Can you please file a new issue and attach a pcap of Windows doing starlight effect and another pcap of OpenRazer doing the starlight effect? Thanks!

You want a packet capture?  I guess the driver and the controller communicate over local networking?  Am I being stupid?

**Comment by z3ntu** [comment]
@jmachen  A USB packet capture, as described on https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol , thanks!

**Comment by jmachen** [comment]
> 
> 
> @jmachen A USB packet capture, as described on https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol , thanks!

Right, can do.

**Pull request merged**
