### PR TITLE
Added support for Naga X

### PR DESCRIPTION
**Pull request by bourquenoud**
Added support for the Naga X based on what @daenney did in the PR #1677

Similar to Naga Left Handed for the most part. Naga X uses an URB index of 0x03 like the basilisk v3. Getting the serial number seems to require a transaction ID of 0x08, at least that's what Synapse uses

### CODE REVIEW

**Comment by bufothefrog** [comment]
Tested working on F36: all preset effects, DPI changes, brightness/color controls.

**Comment by daenney** [comment]
I built the PR and I can confirm it works with my Naga X too.

Thanks so much for taking my half-assed attempt and turning it into something properly working @bourquenoud!

**Comment by bourquenoud** [comment]
@daenney Your code had everything right except for the USB request's index. And because no other devices used an index different than zero, it was quite a struggle to figure it out. But basically what I did was just patch the current version with your PR and change the index to `0x03`. In fact you did most of the heavy lifting, so thank you :)

**Review by mikesellitto — APPROVED** [review]
confirmed working, and lgtm

**Review by reoccurcat — APPROVED** [review]
confirmed working with my naga x, lgtm

**Comment by justinnichols** [comment]
It's been about 2 months since the second confirmation of this PR working.  Any idea on when it would get merged and built into a new version?

**Review by z3ntu — APPROVED** [review]
LGTM, thanks for this patch!

**Comment by DagothUrTheFalse** [comment]
I seem to be having only one small issue with the naga x support when trying it, can't seem to set logo light but i might be misremembering if it has one, or it might be a front end issue instead of one with openrazer

**Pull request merged**
