### PR TITLE
Add support for Razer DeathAdder V3

### LINKED ISSUE #2036: Support for DeathAdder V3
### Device Info

* Name: Deathadder V3 
* Product Number: RZ01-04640100
* Model Number: RZ01-0464

### Device Information

Bus 005 Device 002: ID 1532:00b2 Razer USA, Ltd Razer DeathAdder V3
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x00b2 
  bcdDevice            1.01
  iManufacturer           1 Razer
  iProduct                2 Razer DeathAdder V3
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1

lrwxrwxrwx 1 root root  10 Mar 15 15:46 usb-Razer_Razer_DeathAdder_V3-event-if01 -> ../event18
lrwxrwxrwx 1 root root  10 Mar 15 15:46 usb-Razer_Razer_DeathAdder_V3-event-mouse -> ../event16
lrwxrwxrwx 1 root root  10 Mar 15 15:46 usb-Razer_Razer_DeathAdder_V3-if01-event-kbd -> ../event17
lrwxrwxrwx 1 root root  10 Mar 15 15:46 usb-Razer_Razer_DeathAdder_V3-if02-event-kbd -> ../event19
lrwxrwxrwx 1 root root   9 Mar 15 15:46 usb-Razer_Razer_DeathAdder_V3-mouse -> ../mouse0

005:002:002:DESCRIPTOR         1678914525.393356
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

005:002:001:DESCRIPTOR         1678914525.393729
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 0E 81 00 C0 05 0C 09 01 A1 01 85
 02 19 00 2A 3C 02 15 00 26 3C 02 95 01 75 10 81
 00 75 08 95 0D 81 01 C0 05 01 09 80 A1 01 85 03
 19 81 29 83 15 00 25 01 75 01 95 03 81 02 95 05
 81 01 75 08 95 0E 81 01 C0 05 01 09 00 A1 01 85
 04 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95
 0F 81 00 C0 05 01 09 00 A1 01 85 05 09 03 15 00
 26 FF 00 35 00 46 FF 00 75 08 95 0F 81 00 C0

005:002:000:DESCRIPTOR         1678914525.394107
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05
 01 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09
 31 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 06 00
 FF 09 02 15 00 25 01 75 08 95 5A B1 01 C0

this is not the Deathadder V3 Pro!
Deathadder V3 released recently, 8000hz polling rate

### PR DESCRIPTION
**Pull request by freundf**
Closes #2036.

Adds support for Razer DeathAdder V3.
Tested in a Ubuntuu Linux VM with Polycromatic. Setting and reading DPI works, setting and reading polling rate works.
Saving DPI preset to mouse seems to work (no error), but the hardware DPI switch button doesn't work yet, it just emits an "up" keypress.
Help regarding the DPI switch button would be appreciated.

### CODE REVIEW

**Comment by z3ntu** [comment]
@lah7 Do you know this part works on any device properly yet?

> but the hardware DPI switch button doesn't work yet, it just emits an "up" keypress.

**Comment by z3ntu** [comment]
> RGB LIGHTING | None

Well, didn't expect there to mice from Razer with no LEDs, maybe we're going to a world with less RGB again :wink: 

Anyways, diff from the PR looks good.

**Comment by lah7** [comment]
> Do you know this part works on any device properly yet?

@z3ntu Looking at the [product page](https://www.razer.com/gb-en/gaming-mice/razer-deathadder-v3/RZ01-04640100-R3M1), this mouse has a single DPI button under the mouse. I'm not aware of how one button works, since we've just had mice with both an up & down DPI button.

I think our daemon _swallows_ the hardware buttons (in driver mode?), so that might be expected.

* https://github.com/openrazer/openrazer/issues/201

**Comment by gwoob** [comment]
Any reason this isn't merged yet?

**Comment by ginzberg** [comment]
If this is helpful, I've added the capture for pressing the DPI button on this mouse: 
https://github.com/ginzberg/razer-wired-deathadder3-captures/blob/main/press_dpi_button.pcapng

I can do more captures if this is additionally helpful, as I own this mouse.

**Comment by gwoob** [comment]
> I can do more captures if this is additionally helpful, as I own this mouse.

I own this mouse too and can help get this merged, but I don't know what we are stuck on?

**Comment by lah7** [comment]
Thanks for the packet captures. It shows the device sending a "set DPI" and then "set DPI stages" command.

Since everything else works, the only outstanding _problem_ is that pressing the hardware DPI button emits a keypress "up" instead of activating the next DPI stage (1→2→3→4→5→1, etc). Presumably because this mouse expects software to handle that, and our older mice had 2 up/down buttons to handled itself at the firmware level.

I guess we need logic in the driver/daemon that catches this mouse's keypress "up" event, then set a new DPI. Though I'm not aware we can read DPI stages from hardware, so we'd need the daemon to start storing DPI stages in software, and that would allow the DPI button to know what value to set.

**Comment by z3ntu** [comment]
From my side this missing functionality is not a blocker and can be added later.

Do you'all agree on this?

**Comment by gwoob** [comment]
I agree, this missing functionality isn't worth letting this device sit completely unsupported for too much longer.

**Review by z3ntu — APPROVED** [review]
LGTM, thanks for the patch!

**Pull request merged**
