### PR TITLE
[WIP] Driver cleanup

### PR DESCRIPTION
**Pull request by tbe**
Some cleanup and optimizations for the kernel modules.

This is WIP and and open for discussions.

### CODE REVIEW

**Comment by tbe** [comment]
To fix these long standing TODO blocks https://github.com/openrazer/openrazer/blob/6c71ccfc2bbecc014bb13dd301b2b703ef75fcfa/driver/razerkbd_driver.c#L924

I see 3 ways, after persisting these ID's to the device struct:

1. make `razer_chroma_*` aware of the device struct
2. and pass the transaction id to `razer_chroma_*`
3. set the transaction ID outside of `razer_chroma_`

Whats your favorite?

**Comment by tbe** [comment]
Also, i would like to have some input on the following idea:

- store all device relevant information in a struct
  - name
  - sysfs attributes
  - transaction id's for the reports
  - ...
- initialize the struct for every device
- use function pointers instead of `switch` blocks for device specific behavior ( stored in the device struct )
- move every common code to a common module

My goal with this idea is, to make the implementation of a new device as simple as:

1. fill a new struct
2. add the USB ID's to the correct module
3. be happy

This is of course a lot of work, and is a massive change to the current codebase.
But this would follow kernel best practices, and could open the path to bring the kernel modules upstream ;)

@z3ntu what are your thoughts about this?

**Comment by z3ntu** [comment]
> I see 3 ways, after persisting these ID's to the device struct:
> 
> 1. make `razer_chroma_*` aware of the device struct
> 2. and pass the transaction id to `razer_chroma_*`
> 3. set the transaction ID outside of `razer_chroma_`
> 
> Whats your favorite?

The razer_chroma_* functions shouldn't be device-aware but stupidly prepare reports for sending. I'd say putting the setting into `razer_send_payload` would make sense.

> This is of course a lot of work, and is a massive change to the current codebase.

I hope no devices get broken in the process :wink: 

> But this would follow kernel best practices, and could open the path to bring the kernel modules upstream ;)

I don't think these kernel modules belong upstream in any resembling the current code. There's been an RFC patch posted to LKML which adds support for Razer devices in an upstreamable fashion. I believe neither the author nor I were very happy with what that code was doing so the patch was never updated (or merged).

In my opinion most of the code that's currently in the kernel module belongs into user space and the lightning things should be managed through hidraw / libusb as done in my side project https://github.com/z3ntu/razer_test . This also opens the possibility of running this on other operating systems including macOS, Windows, FreeBSD, etc (which already works with that project!). I believe that also the architecture of that project is much better than current openrazer. Unfortunately development's been really slow, especially over the last year so I'm quite sure it won't completely replace openrazer anytime soon (unfortunately).

**Comment by tbe** [comment]
I have thrown out my razer devices a while back, so i'm now longer able to work in this. Sry for that. I will close this PR.

**Pull request closed without merging**
