### PR TITLE
Add support for Razer Blade Pro (Late 2019) 1532:024C

### PR DESCRIPTION
**Pull request by cockytrumpet**
Everything in polychromatic-controller seems to work. I can't get the tray applet to run, so I can't test that.

### CODE REVIEW

**Comment by MTecknology** [comment]
Oh my... I've been having a horrible time with this device for the past 50(ish) days. The last headache I'm having is the annoying default keyboard backlight (and not quite going all the way to sleep).

Thank-you for creating this PR! :D

**Comment by MTecknology** [comment]
I have this laptop. I applied these patches to a local debianized package and can confirm that all works well. Even palm detection seems to be working! (hopefully that's not a fluke because I was trying to force it..)

Thanks again!

**Comment by cockytrumpet** [comment]
For the touchpad, the libinput driver works better than the synaptic one. 

I had trouble with sleep too. I ended up disabling it in gnome and elogind and  starting it with acpid scripts.

echo freeze >> /sys/power/state
or
echo mem >> /sys/power/state

**Comment by MTecknology** [comment]
With razercommander and razergenie, I can configure the effect/brightness of the keyboard backlight. However, I can't do anything with the logo (minor; don't really care), and I the brightness returns to one of the preset defaults if power is connected/removed. It seems like this may be a feature neither tool support.

I thought I'd check to see if chromastudio could handle the powerChange-brightness thing, but chromastudio said it couldn't connect to the daemon and spit this out:
```
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.2/0003:1532:024C.0003/logo_led_state'
```

```
root@toast:~# ls /sys/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.2/0003:1532:024C.0003/
country        firmware_version  macro_led_effect      matrix_effect_custom    matrix_effect_wave  test
device_mode    game_led_state	 macro_led_state       matrix_effect_none      modalias		   uevent
device_serial  hidraw		 matrix_brightness     matrix_effect_reactive  power		   version
device_type    input		 matrix_custom_frame   matrix_effect_spectrum  report_descriptor
driver	       kbd_layout	 matrix_effect_breath  matrix_effect_static    subsystem
```

It looks like it's just a matter of ``logo_led_state`` vs. ``game_led_state``.

**Comment by MTecknology** [comment]
BTW- Thank-you! You saved me a whole lot of time and pain on the sleep loop thing!

For anyone that winds up here and wants a few more instructions...

Edit /etc/elogind/logind.conf:
```
HandleLidSwitch=ignore
HandleLidSwitchExternalPower=ignore
# Need to restart elogind service; restarting is easiest
```

*Auto-invoked:*

Create (mode 0644) /etc/acpi/events/lid:
```
event=button[ /]lid LID close
action=/usr/local/sbin/powerpctl mem
```

*User-invoked:*

Create (mode: 0755) /usr/local/sbin/powerctl:
```
#!/bin/dash
# Simple wrapper to issue power control commands (freeze|mem|...)
# https://www.kernel.org/doc/Documentation/power/states.txt
echo "$1" >/sys/power/state
```

Create (mode: 0440) /etc/sudoers.d/powerctl:
```
ALL ALL=NOPASSWD:/usr/local/sbin/powerctl
```

From there.. ``sudo powerctl mem`` (or any other documented option)

*Regarding Palm Detection--*

I upgraded to the latest 'n greatest libinput packages and it made a huge difference. It's still not great, but at least better.

Also..
> I can't get the tray applet to run, so I can't test that.

It works great. It's not until I open the controller that I have the problem.

**Comment by cockytrumpet** [comment]
> the brightness returns to one of the preset defaults if power is connected/removed. It seems like this may be a feature neither tool 

I don't have a solution for this, unfortunately.

> I can't do anything with the logo

Changing the logo state through polychromatic 0.3.12-stable works fine for me. It is odd that my output is different than yours on the same device...

<pre><font color="#EF2929"><b>blade</b></font><font color="#729FCF"><b> ~ #</b></font> ls -l /sys/devices/pci0000\:00/0000\:00\:14.0/usb1/1-8/1-8\:1.2/0003\:1532\:024C.0009/
total 0
-r--r--r-- 1 root plugdev 4096 Mar  5 21:34 country
-rw-rw---- 1 root plugdev 4096 Mar  5 21:35 device_mode
-r--r----- 1 root plugdev 4096 Mar  5 21:34 device_serial
-r--r----- 1 root plugdev 4096 Mar  5 21:34 device_type
lrwxrwxrwx 1 root plugdev    0 Mar  5 21:34 <font color="#34E2E2"><b>driver</b></font> -&gt; <font color="#729FCF"><b>../../../../../../../bus/hid/drivers/razerkbd</b></font>
-r--r----- 1 root plugdev 4096 Mar  5 21:34 firmware_version
drwxr-xr-x 3 root plugdev    0 Mar  5 21:34 <font color="#729FCF"><b>hidraw</b></font>
drwxr-xr-x 3 root plugdev    0 Mar  5 21:34 <font color="#729FCF"><b>input</b></font>
-r--r----- 1 root plugdev 4096 Mar  5 21:34 kbd_layout
-rw-rw---- 1 root plugdev 4096 Mar  5 21:34 logo_led_state
-rw-rw---- 1 root plugdev 4096 Mar  6 15:16 matrix_brightness
--w--w---- 1 root plugdev 4096 Mar  5 21:34 matrix_custom_frame
--w--w---- 1 root plugdev 4096 Mar  5 21:34 matrix_effect_breath
--w--w---- 1 root plugdev 4096 Mar  5 21:34 matrix_effect_custom
--w--w---- 1 root plugdev 4096 Mar  5 21:34 matrix_effect_none
--w--w---- 1 root plugdev 4096 Mar  5 21:34 matrix_effect_reactive
--w--w---- 1 root plugdev 4096 Mar  5 21:34 matrix_effect_spectrum
--w--w---- 1 root plugdev 4096 Mar  5 21:34 matrix_effect_starlight
--w--w---- 1 root plugdev 4096 Mar  5 21:34 matrix_effect_static
--w--w---- 1 root plugdev 4096 Mar  5 21:34 matrix_effect_wave
-r--r--r-- 1 root plugdev 4096 Mar  5 21:34 modalias
drwxr-xr-x 2 root plugdev    0 Mar  5 21:34 <font color="#729FCF"><b>power</b></font>
-r--r--r-- 1 root plugdev 4096 Mar  5 21:34 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Mar  5 21:34 <font color="#34E2E2"><b>subsystem</b></font> -&gt; <font color="#729FCF"><b>../../../../../../../bus/hid</b></font>
-rw-rw---- 1 root plugdev 4096 Mar  5 21:34 test
-rw-r--r-- 1 root plugdev 4096 Mar  5 21:34 uevent
-r--r----- 1 root plugdev 4096 Mar  5 21:34 version
</pre>

**Comment by ColinHarrington** [comment]
I rebased the changes here by @cockytrumpet on today's master branch: 
https://github.com/ColinHarrington/openrazer/tree/feature-blade-pro-2019-0x024c

The conflict in `99-razer.rules` is trivial.

Everything I tested in Polychromatic (0.3.12-stable) and the tray applet was working for me.  The logo state on/off works.  I do see `Logo: Unknown` in the Effects section of the tray applet, but that's not a big deal.

:shipit:

**Comment by z3ntu** [comment]
Merged as #1044, thanks for your contribution @cockytrumpet !

**Pull request closed without merging**
