### PR TITLE
Add persistence storage

### PR DESCRIPTION
**Pull request by lah7**
It's https://github.com/openrazer/openrazer/pull/888 plus some [finishing touches](https://github.com/openrazer/openrazer/pull/888#issuecomment-624840406). All tasks have been completed and it's working well - ready for a final review.

There are no open issues to close on this repository - the [mentioned open issues](https://github.com/openrazer/openrazer/pull/888#issue-302242875) are for front-ends.

Worth mentioning in the release notes:

> * Lighting settings are retained across reboots. 
>      * This will cause your devices to reset to spectrum initially. 
>      * Applications will require an update to support this feature.
> * Some devices (such as Chroma HDK and Base Station Chroma) no longer report 0% brightness.

### CODE REVIEW

**Comment by chabad360** [comment]
> > A known issue is that this doesn't monitor DPI changes via hardware buttons, so this won't be persisted until the state is updated via the API.
>
> ...or until #1124 is merged (which would allow for handling the buttons in userspace))

Well, it depends on how the buttons report, I only monitor hardware events that trigger `evdev` (i.e. keypress events), so it's not that simple...

**Comment by tildearrow** [comment]
I wonder what happened to this branch?...

It's been a while since it was last updated.

**Comment by z3ntu** [comment]
Error with e.g. Kraken Ultimate: (see #1266, polychromatic/polychromatic#287)
```python
import openrazer.client as rclient
device = rclient.DeviceManager().devices[0]  # First device
device.fx.breath_single(255,255,255)
device.fx.breath_dual(255,255,255, 128,128,128)
device.fx.breath_triple(255,255,255, 128,128,128, 255,255,255)
device.fx.breath_dual(255,255,255, 128,128,128)  # Error happens
```
```
Traceback (most recent call last):
  File "a.py", line 6, in <module>
    device.fx.breath_dual(255,255,255, 128,128,128)  # Error happens
  File "/usr/lib/python3.8/site-packages/openrazer/client/fx.py", line 277, in breath_dual
    self._lighting_dbus.setBreathDual(red, green, blue, red2, green2, blue2)
  File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/home/luca/dev/razer/openrazer/daemon/openrazer_daemon/dbus_services/dbus_methods/chroma_keyboard.py", line 479, in set_breath_dual_effect
    self.zone["backlight"]["colors"][0:6] = int(red1), int(green1), int(blue1), int(red2), int(green2), int(blue2)
TypeError: 'tuple' object does not support item assignment
```

**Review by kevchu3 — COMMENTED** [review]
I pulled this commit and tested, and was successfully able to resolve #1266

**Comment by tildearrow** [comment]
I have created a package for this in the AUR, which can be found [here](https://aur.archlinux.org/packages/openrazer-fxs-daemon-git/). I hope this is fine...

**Comment by z3ntu** [comment]
> I have created a package for this in the AUR, which can be found [here](https://aur.archlinux.org/packages/openrazer-fxs-daemon-git/). I hope this is fine...

Please don't...? This is literally a one-line change that definitely doesn't need an extra package... 


> Make sure the package you want to upload is useful. Will anyone else want to use this package? Is it extremely specialized? If more than a few people would find this package useful, it is appropriate for submission.

https://wiki.archlinux.org/index.php/AUR_submission_guidelines#Rules_of_submission

**Comment by tildearrow** [comment]
Package removed from AUR. I did read the guidelines prior to submission, especially regaeding usefulness.

I doubted on the point for a moment but then I thought it would be useful... (considering this is not a small changeset)

**Comment by tildearrow** [comment]
@z3ntu completely forgot about this branch, which could have been merged...
I don't want to wait another year...

**Comment by kevchu3** [comment]
Would we be able to get this PR merged into master?

**Pull request merged**
