### PR TITLE
DeathAdder 2000 image loads through https

### PR DESCRIPTION
**Pull request by ninjamar**
This corresponds with https://github.com/openrazer/openrazer.github.io/pull/18

### CODE REVIEW

**Comment by z3ntu** [comment]
Same comment as in the other PR, does the picture to load for you via https? I get a big security warning in Chrome

**Comment by ninjamar** [comment]
> Same comment as in the other PR, does the picture to load for you via https? I get a big security warning in Chrome

I changed the image

**Review by z3ntu — APPROVED** [review]
looks similar enough, thanks!

**Comment by ninjamar** [comment]
> looks similar enough, thanks!

Thanks
Can you merge?

**Pull request merged**
