### PR TITLE
Raptor 27 Support

### LINKED ISSUE #1217: Support for Razer Raptor 27 (Monitor)
### Razor Raptor 27

Connects via HDMI/DisplayPort/USB C

Controlled via Razer Synapse via USB C.

Initially I tried setting the RGB values and profile via a friend's borrowed Windows 10 laptop, however, the effects only remain as long as the computer is plugged in via USB C.  Otherwise it switches back to the default of cycling through all colors.

* Name: Razor Raptor 27
* Product Number: <See under device>
* Model Number: RZ39-0276

### Device Information
```
Please post the output of
    lsusb -d 1532: -v

No output information could be seen related to the Raptor 27.
```

```
Please post the output of
    ls -lah /dev/input/by-id/

No output information could be seen related to the Raptor 27.
```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>

### PR DESCRIPTION
**Pull request by psykher**
#1541 merge conflicts solved and tested. It works pretty nice for me:

image

Closes #1217

### CODE REVIEW

**Comment by psykher** [comment]
Thanks for your effort on this @jedimasterjonny

**Comment by nightsky30** [comment]
@psykher I'm curious if you are you able to grab a proper serial number off this device? See https://github.com/openrazer/openrazer/pull/1541#issuecomment-941778929

**Comment by psykher** [comment]
> @psykher I'm curious if you are you able to grab a proper serial number off this device? See [#1541 (comment)](https://github.com/openrazer/openrazer/pull/1541#issuecomment-941778929)

Yeah I think so, you mean this?

image

image

**Comment by nightsky30** [comment]
> > @psykher I'm curious if you are you able to grab a proper serial number off this device? See [#1541 (comment)](https://github.com/openrazer/openrazer/pull/1541#issuecomment-941778929)
> 
> Yeah I think so, you mean this?
> 
> image
> 
> image

Yeah, that looks like a valid serial. :+1: Wonder what the issue was then in the previous PR. :thinking:

**Comment by psykher** [comment]
Do we need anything else to merge this? @lah7

**Review by z3ntu — APPROVED** [review]
Fixed up some minor stuff, LGTM now!

Thanks @jedimasterjonny and @psykher !

**Pull request merged**
