### PR TITLE
Add USB_DEVICE_ID_RAZER_NAGA_CHROMA to list of devices supporting horizontal scrolling

### LINKED ISSUE #2093: Add USB_DEVICE_ID_RAZER_NAGA_CHROMA to list of devices supporting horizontal scrolling
I'm just coming back to this [libinput bug](https://bugs.freedesktop.org/show_bug.cgi?id=104960) again years later, and I see that in the meantime horizontal scrolling (#201) has been implemented for many devices. Using #1597 as an example I tried adding the USB ID for my mouse to the driver and recompiling, and now after setting the mouse to driver mode horizontal scrolling works! I don't know that I did everything correctly or if there's some other considerations to be made since the configuration for several devices is mixed together so I am creating an issue instead of a PR. Here's the changes I made to test it tho:
```
--- /usr/src/openrazer-driver-3.6.1/driver/razermouse_driver.c	2023-05-13 08:12:42.000000000 -0700
+++ razermouse_driver.c	2023-07-15 21:25:28.503230846 -0700
@@ -4942,6 +4942,7 @@
     switch (hdev->product) {
     case USB_DEVICE_ID_RAZER_MAMBA_ELITE:
     case USB_DEVICE_ID_RAZER_NAGA_2014:
+    case USB_DEVICE_ID_RAZER_NAGA_CHROMA:
     case USB_DEVICE_ID_RAZER_BASILISK_V2:
     case USB_DEVICE_ID_RAZER_BASILISK_V3:
     case USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_WIRED:
@@ -5079,6 +5080,7 @@
             fallthrough;
         case USB_DEVICE_ID_RAZER_MAMBA_ELITE:
         case USB_DEVICE_ID_RAZER_NAGA_2014:
+        case USB_DEVICE_ID_RAZER_NAGA_CHROMA:
             input_set_capability(hidinput->input, EV_REL, REL_HWHEEL);
             input_set_capability(hidinput->input, EV_REL, REL_HWHEEL_HI_RES);
             input_set_capability(hidinput->input, EV_KEY, BTN_FORWARD);
@@ -5402,6 +5404,9 @@
 
         case USB_DEVICE_ID_RAZER_NAGA_HEX_V2:
         case USB_DEVICE_ID_RAZER_NAGA_CHROMA:
+            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_tilt_hwheel);
+            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_tilt_repeat_delay);
+            CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_tilt_repeat);
             CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_poll_rate);
             CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_dpi);
             CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_brightness);
@@ -6207,6 +6212,9 @@
 
         case USB_DEVICE_ID_RAZER_NAGA_HEX_V2:
         case USB_DEVICE_ID_RAZER_NAGA_CHROMA:
+            device_remove_file(&hdev->dev, &dev_attr_tilt_hwheel);
+            device_remove_file(&hdev->dev, &dev_attr_tilt_repeat_delay);
+            device_remove_file(&hdev->dev, &dev_attr_tilt_repeat);
             device_remove_file(&hdev->dev, &dev_attr_poll_rate);
             device_remove_file(&hdev->dev, &dev_attr_dpi);
             device_remove_file(&hdev->dev, &dev_attr_matrix_brightness);
```

### PR DESCRIPTION
**Pull request by computator**
Creating a PR for my patch 

Fixes #2093.

### CODE REVIEW

**Comment by computator** [comment]
Well it won't let me add it as a code comment since it's not on a line I edited, but since I am unfamiliar with how the codebase works, my main concern is that it will now use this block for handling keyboard protocol instead of the block in the `default` case:
https://github.com/openrazer/openrazer/blob/9bcaf54640132b8f4795f3c4dc8744641490aaad/driver/razermouse_driver.c#L4451-L4469

That seems to be quite different from this, which just converts things to the F13-F16 keys:
https://github.com/openrazer/openrazer/blob/9bcaf54640132b8f4795f3c4dc8744641490aaad/driver/razermouse_driver.c#L4472-L4506

**Comment by z3ntu** [comment]
Did the `default:` branch there trigger correctly when you use the DPI buttons on the mouse? What happens now with the patched code?

**Comment by computator** [comment]
IIRC with the original nonpatched code the DPI buttons and the wheel don't do anything in driver mode because they are triggering F13-F16. With the patched code the wheel left and right works for scrolling in the appropriate direction, and the DPI buttons are mapped to forward and back navigation (like in a browser) which is pretty standard for a generic mouse.

In the default non-driver mode everything seems to be identical pre and post patch, meaning that wheel left and right are mapped to vertical scrolling and the DPI buttons control DPI.

**Comment by computator** [comment]
I can go back and do more detailed testing if needed or to verify the above (I'm on a different PC atm), but I was more just concerned about the intended action of the code since my mouse seemed to be acting fine.

**Comment by z3ntu** [comment]
If the new behavior is correct/expected, then this patch is fine with me.

I was just a bit confused by your comment

> my main concern is that it will now use this block for handling keyboard protocol instead of the block in the default case:

**Comment by computator** [comment]
Yeah if the code looks right, the behavior seems to be fine so far with my limited testing!

**Review by z3ntu — APPROVED** [review]
😅

**Pull request merged**
