### PR TITLE
Add support for Razer Laptop Stand Chroma V2

### LINKED ISSUE #1730: Support for Laptop Stand Chroma V2
### Device Info

* Name: Laptop Stand Chroma V2
* Product Number: <See under device>
* Model Number: RC21-0168

### Device Information
```
1439   │ Bus 003 Device 005: ID 1532:0f2b Razer USA, Ltd Razer Laptop Stand Chroma V2
1440   │ Device Descriptor:
1441   │   bLength                18
1442   │   bDescriptorType         1
1443   │   bcdUSB               2.00
1444   │   bDeviceClass            0 
1445   │   bDeviceSubClass         0 
1446   │   bDeviceProtocol         0 
1447   │   bMaxPacketSize0        64
1448   │   idVendor           0x1532 Razer USA, Ltd
1449   │   idProduct          0x0f2b 
1450   │   bcdDevice            2.00
1451   │   iManufacturer           1 Razer
1452   │   iProduct                2 Razer Laptop Stand Chroma V2
1453   │   iSerial                 0 
1454   │   bNumConfigurations      1
1455   │   Configuration Descriptor:
1456   │     bLength                 9
1457   │     bDescriptorType         2
1458   │     wTotalLength       0x0054
1459   │     bNumInterfaces          3
1460   │     bConfigurationValue     1
1461   │     iConfiguration          0 
1462   │     bmAttributes         0xa0
1463   │       (Bus Powered)
1464   │       Remote Wakeup
1465   │     MaxPower              500mA
1466   │     Interface Descriptor:
1467   │       bLength                 9
1468   │       bDescriptorType         4
1469   │       bInterfaceNumber        0
1470   │       bAlternateSetting       0
1471   │       bNumEndpoints           1
1472   │       bInterfaceClass         3 Human Interface Device
1473   │       bInterfaceSubClass      1 Boot Interface Subclass
1474   │       bInterfaceProtocol      2 Mouse
1475   │       iInterface              0 
1476   │         HID Device Descriptor:
1477   │           bLength                 9
1478   │           bDescriptorType        33
1479   │           bcdHID               1.11
1480   │           bCountryCode            0 Not supported
1481   │           bNumDescriptors         1
1482   │           bDescriptorType        34 Report
1483   │           wDescriptorLength      94
1484   │          Report Descriptors: 
1485   │            ** UNAVAILABLE **
1486   │       Endpoint Descriptor:
1487   │         bLength                 7
1488   │         bDescriptorType         5
1489   │         bEndpointAddress     0x81  EP 1 IN
1490   │         bmAttributes            3
1491   │           Transfer Type            Interrupt
1492   │           Synch Type               None
1493   │           Usage Type               Data
1494   │         wMaxPacketSize     0x0008  1x 8 bytes
1495   │         bInterval               1
1496   │     Interface Descriptor:
1497   │       bLength                 9
1498   │       bDescriptorType         4
1499   │       bInterfaceNumber        1
1500   │       bAlternateSetting       0
1501   │       bNumEndpoints           1
1502   │       bInterfaceClass         3 Human Interface Device
1503   │       bInterfaceSubClass      0
1504   │       bInterfaceProtocol      1 Keyboard
1505   │       iInterface              0 
1506   │         HID Device Descriptor:
1507   │           bLength                 9
1508   │           bDescriptorType        33
1509   │           bcdHID               1.11
1510   │           bCountryCode            0 Not supported
1511   │           bNumDescriptors         1
1512   │           bDescriptorType        34 Report
1513   │           wDescriptorLength     159
1514   │          Report Descriptors: 
1515   │            ** UNAVAILABLE **
1516   │       Endpoint Descriptor:
1517   │         bLength                 7
1518   │         bDescriptorType         5
1519   │         bEndpointAddress     0x82  EP 2 IN
1520   │         bmAttributes            3
1521   │           Transfer Type            Interrupt
1522   │           Synch Type               None
1523   │           Usage Type               Data
1524   │         wMaxPacketSize     0x0010  1x 16 bytes
1525   │         bInterval               1
1526   │     Interface Descriptor:
1527   │       bLength                 9
1528   │       bDescriptorType         4
1529   │       bInterfaceNumber        2
1530   │       bAlternateSetting       0
1531   │       bNumEndpoints           1
1532   │       bInterfaceClass         3 Human Interface Device
1533   │       bInterfaceSubClass      0 
1534   │       bInterfaceProtocol      1 Keyboard
1535   │       iInterface              0 
1536   │         HID Device Descriptor:
1537   │           bLength                 9
1538   │           bDescriptorType        33
1539   │           bcdHID               1.11
1540   │           bCountryCode            0 Not supported
1541   │           bNumDescriptors         1
1542   │           bDescriptorType        34 Report
1543   │           wDescriptorLength      61
1544   │          Report Descriptors: 
1545   │            ** UNAVAILABLE **
1546   │       Endpoint Descriptor:
1547   │         bLength                 7
1548   │         bDescriptorType         5
1549   │         bEndpointAddress     0x83  EP 3 IN
1550   │         bmAttributes            3
1551   │           Transfer Type            Interrupt
1552   │           Synch Type               None
1553   │           Usage Type               Data
1554   │         wMaxPacketSize     0x0008  1x 8 bytes
1555   │         bInterval               1
```

```
❯ ls -lah /dev/input/by-id/
drwxr-xr-x root root 440 B  Wed Jan 12 23:05:06 2022  .
drwxr-xr-x root root 1.1 KB Wed Jan 12 23:05:06 2022  ..
lrwxrwxrwx root root  10 B  Wed Jan 12 22:59:05 2022  usb-Azurewave_Integrated_RGB_Camera_01.00.00-event-if00 ⇒ ../event11
lrwxrwxrwx root root  10 B  Wed Jan 12 22:59:05 2022  usb-Azurewave_Integrated_RGB_Camera_01.00.00-event-if02 ⇒ ../event31
lrwxrwxrwx root root  11 B  Wed Jan 12 22:59:05 2022  usb-ELAN_Touchscreen-event-if00 ⇒ ../event265
lrwxrwxrwx root root  10 B  Wed Jan 12 22:59:04 2022  usb-Generic_USB_Audio-event-if03 ⇒ ../event28
lrwxrwxrwx root root   9 B  Wed Jan 12 22:59:05 2022  usb-Razer_Inc_Razer_Kiyo_Pro-event-if00 ⇒ ../event9
lrwxrwxrwx root root  10 B  Wed Jan 12 22:59:04 2022  usb-Razer_Razer_BlackWidow_V3_Pro_000000000000-event-if01 ⇒ ../event23
lrwxrwxrwx root root  10 B  Wed Jan 12 22:59:04 2022  usb-Razer_Razer_BlackWidow_V3_Pro_000000000000-event-if03 ⇒ ../event25
lrwxrwxrwx root root  10 B  Wed Jan 12 22:59:04 2022  usb-Razer_Razer_BlackWidow_V3_Pro_000000000000-event-kbd ⇒ ../event20
lrwxrwxrwx root root  10 B  Wed Jan 12 22:59:04 2022  usb-Razer_Razer_BlackWidow_V3_Pro_000000000000-if01-event-kbd ⇒ ../event21
lrwxrwxrwx root root  10 B  Wed Jan 12 22:59:04 2022  usb-Razer_Razer_BlackWidow_V3_Pro_000000000000-if01-event-mouse ⇒ ../event22
lrwxrwxrwx root root   9 B  Wed Jan 12 22:59:04 2022  usb-Razer_Razer_BlackWidow_V3_Pro_000000000000-if01-mouse ⇒ ../mouse5
lrwxrwxrwx root root  10 B  Wed Jan 12 22:59:04 2022  usb-Razer_Razer_BlackWidow_V3_Pro_000000000000-if02-event-mouse ⇒ ../event24
lrwxrwxrwx root root   9 B  Wed Jan 12 22:59:04 2022  usb-Razer_Razer_BlackWidow_V3_Pro_000000000000-if02-mouse ⇒ ../mouse6
lrwxrwxrwx root root   9 B  Wed Jan 12 22:59:05 2022  usb-Razer_Razer_Blade-event-kbd ⇒ ../event4
lrwxrwxrwx root root  10 B  Wed Jan 12 22:59:05 2022  usb-Razer_Razer_Blade-if01-event-kbd ⇒ ../event30
lrwxrwxrwx root root  11 B  Wed Jan 12 22:59:05 2022  usb-Razer_Razer_Blade-if02-event-mouse ⇒ ../event259
lrwxrwxrwx root root   9 B  Wed Jan 12 22:59:05 2022  usb-Razer_Razer_Blade-if02-mouse ⇒ ../mouse2
lrwxrwxrwx root root  11 B  Wed Jan 12 22:59:32 2022  usb-Razer_Razer_Kraken_Kitty_Chroma_Control-event-if00 ⇒ ../event268
lrwxrwxrwx root root  11 B  Wed Jan 12 22:59:32 2022  usb-Razer_Razer_Kraken_Kitty_Edition_00000000-event-if03 ⇒ ../event269
lrwxrwxrwx root root  10 B  Wed Jan 12 22:59:06 2022  usb-Yubico_YubiKey_OTP+FIDO+CCID-event-kbd ⇒ ../event26
```

### Packet Captures

I'll try to grab these when I have more time.

### Synapse Screenshots
Synase-Laptop-Dock-V2

### PR DESCRIPTION
**Pull request by Chr1sNo**
Fixes https://github.com/openrazer/openrazer/issues/1730

### CODE REVIEW

**Comment by z3ntu** [comment]
Hi, does all the added functionality work properly? Diff looks good

**Comment by RafaelZasas** [comment]
Hi, will this allow HDMI pass through from the Stand V2? Will this me merged soon?

**Comment by RafaelZasas** [comment]
I have a razer blade 15 2022 model running Ubuntu 22.04 and Kernel 5.19. I also have the Stand V2 and can test if needed. I just need instructions on how to get the updates from this PR to my system.

**Comment by z3ntu** [comment]
@RafaelZasas We have a brief guide at https://github.com/openrazer/openrazer/wiki/Building-a-package , if you need any help let me know!

And no, this shouldn't change anything regarding HDMI functionality, this is mainly for adjusting the lighting and any other settings this might have.

**Comment by hlriffel** [comment]
Hi,

I'm using Fedora 36 and I've built the package from source, as mentioned in the guide above, and the DKMS module has been installed successfully. However, after restarting the OpenRazer backend and rebooting, it's still listing device as unrecognized, as it can be seen in the image below:

image

Below is the log of the second time I tried to install the driver with the changes, just to make sure everything was installed correctly. The third line of the log says: `Downloading: https://github.com/Chr1sNo/openrazer/archive/75aaaf9bac0ee8dd686a9ca3aa65296e62450e84.tar.gz`, which I believe is the correct version.

[installation.log](https://github.com/openrazer/openrazer/files/10004068/installation.log)

**Comment by z3ntu** [comment]
@hlriffel Check that you actually have the rpms you built installed and not the ones from the repo.
```
Package openrazer-daemon-3.4.0-1.fc36.noarch is already installed.
Package openrazer-kernel-modules-dkms-3.4.0-1.fc36.noarch is already installed.
Package openrazer-meta-3.4.0-1.fc36.noarch is already installed.
Package python3-openrazer-3.4.0-1.fc36.noarch is already installed.
```

**Comment by hlriffel** [comment]
Yes, I think `3.4.0` was the version I had in the `Version:` line in the `openrazer.spec` file. This time I downgraded the version to `3.3.0` and ran the installation again. You can check the first 49 lines of the `.spec` file and the full `.log` file below.

### openrazer.spec
```
# This spec file should work on Fedora, openSUSE and Mageia

%define dkms_name openrazer-driver
%define dkms_version 3.3.0

%define gitcommit 75aaaf9bac0ee8dd686a9ca3aa65296e62450e84

Name: openrazer-meta
Version: 3.3.0
Release: 1%{?dist}
Summary: Open source driver and user-space daemon for managing Razer devices

License: GPL-2.0
URL: https://github.com/openrazer/openrazer

%if 0%{?gitcommit:1}
Source0: https://github.com/Chr1sNo/openrazer/archive/%{gitcommit}.tar.gz
%else
Source0: https://github.com/openrazer/openrazer/releases/download/v%{version}/openrazer-%{version}.tar.xz
%endif

BuildArch: noarch

Requires: openrazer-kernel-modules-dkms
Requires: openrazer-daemon
Requires: python3-openrazer

%description
Meta package for installing all required openrazer packages.


%package -n openrazer-kernel-modules-dkms
Summary: OpenRazer Driver DKMS package
Group: System Environment/Kernel
Obsoletes: razer-kernel-modules-dkms
Provides: razer-kernel-modules-dkms
Requires: dkms
Requires: make
Requires: udev
# OBS fails without that
%if 0%{?suse_version}
Requires(pre): shadow
Requires(post): dkms
%else
Requires(pre): shadow-utils
%endif

%description -n openrazer-kernel-modules-dkms
Kernel driver for Razer devices (DKMS-variant)
```

### installation.log
[installation.log](https://github.com/openrazer/openrazer/files/10055033/installation.log)

Still, after reinstalling and restarting the `openrazer` daemon, I get the `Unrecognised Device`, as you can see in the image below:
image

EDIT: The results didn't change after a reboot either.

**Comment by hlriffel** [comment]
I noticed that the output of `ls -lah /dev/input/by-id/` in the Device Support issue did not contain the event IDs of the device. I'm posting mine here in the hope that it helps.

```
total 0
drwxr-xr-x. 2 root root  580 Dec 12 13:18 .
drwxr-xr-x. 4 root root 1.2K Dec 12 13:18 ..
lrwxrwxrwx. 1 root root   10 Dec 12 13:18 usb-CN0VGCNH8LG0097EA61CA00_Integrated_Webcam_HD-event-if00 -> ../event19
lrwxrwxrwx. 1 root root   10 Dec 12 13:18 usb-Generic_Razer_Base_Station_V2_Chroma-event-if00 -> ../event26
lrwxrwxrwx. 1 root root    9 Dec 12 13:18 usb-NXP_SEMICONDUCTORS_Razer_Kraken_V3_Pro-event-if03 -> ../event5
lrwxrwxrwx. 1 root root   11 Dec 12 13:18 usb-RAZER_Razer_Base_Station_V2_Chroma-event-mouse -> ../event258
lrwxrwxrwx. 1 root root   10 Dec 12 13:18 usb-RAZER_Razer_Base_Station_V2_Chroma-mouse -> ../mouse10
lrwxrwxrwx. 1 root root   10 Dec 12 13:18 usb-Razer_Razer_Basilisk_Ultimate_Dongle-event-mouse -> ../event25
lrwxrwxrwx. 1 root root   10 Dec 12 13:18 usb-Razer_Razer_Basilisk_Ultimate_Dongle-if01-event-kbd -> ../event29
lrwxrwxrwx. 1 root root   10 Dec 12 13:18 usb-Razer_Razer_Basilisk_Ultimate_Dongle-if02-event-kbd -> ../event31
lrwxrwxrwx. 1 root root    9 Dec 12 13:18 usb-Razer_Razer_Basilisk_Ultimate_Dongle-mouse -> ../mouse8
lrwxrwxrwx. 1 root root   11 Dec 12 13:18 usb-Razer_Razer_BlackWidow_V3_Pro-event-if03 -> ../event265
lrwxrwxrwx. 1 root root   10 Dec 12 13:18 usb-Razer_Razer_BlackWidow_V3_Pro-event-kbd -> ../event15
lrwxrwxrwx. 1 root root   10 Dec 12 13:18 usb-Razer_Razer_BlackWidow_V3_Pro-if01-event-kbd -> ../event21
lrwxrwxrwx. 1 root root   10 Dec 12 13:18 usb-Razer_Razer_BlackWidow_V3_Pro-if02-event-mouse -> ../event18
lrwxrwxrwx. 1 root root    9 Dec 12 13:18 usb-Razer_Razer_BlackWidow_V3_Pro-if02-mouse -> ../mouse4
lrwxrwxrwx. 1 root root   11 Dec 12 13:18 usb-Razer_Razer_Goliathus_Extended_Chroma-event-mouse -> ../event267
lrwxrwxrwx. 1 root root   11 Dec 12 13:18 usb-Razer_Razer_Goliathus_Extended_Chroma-if01-event-kbd -> ../event259
lrwxrwxrwx. 1 root root   11 Dec 12 13:18 usb-Razer_Razer_Goliathus_Extended_Chroma-if02-event-kbd -> ../event257
lrwxrwxrwx. 1 root root    9 Dec 12 13:18 usb-Razer_Razer_Goliathus_Extended_Chroma-mouse -> ../mouse9
lrwxrwxrwx. 1 root root    9 Dec 12 13:18 usb-Razer_Razer_Laptop_Stand_Chroma_V2-event-if01 -> ../event9
lrwxrwxrwx. 1 root root    9 Dec 12 13:18 usb-Razer_Razer_Laptop_Stand_Chroma_V2-event-mouse -> ../event7
lrwxrwxrwx. 1 root root    9 Dec 12 13:18 usb-Razer_Razer_Laptop_Stand_Chroma_V2-if01-event-kbd -> ../event8
lrwxrwxrwx. 1 root root   10 Dec 12 13:18 usb-Razer_Razer_Laptop_Stand_Chroma_V2-if02-event-kbd -> ../event10
lrwxrwxrwx. 1 root root    9 Dec 12 13:18 usb-Razer_Razer_Laptop_Stand_Chroma_V2-mouse -> ../mouse1
lrwxrwxrwx. 1 root root   11 Dec 12 13:18 usb-Razer_Razer_Mouse_Dock-event-mouse -> ../event264
lrwxrwxrwx. 1 root root   10 Dec 12 13:18 usb-Razer_Razer_Mouse_Dock-if01-event-kbd -> ../event27
lrwxrwxrwx. 1 root root   10 Dec 12 13:18 usb-Razer_Razer_Mouse_Dock-if02-event-kbd -> ../event23
lrwxrwxrwx. 1 root root    9 Dec 12 13:18 usb-Razer_Razer_Mouse_Dock-mouse -> ../mouse5
```

**Comment by z3ntu** [comment]
@hlriffel Any progress on getting it running for you?

**Comment by hlriffel** [comment]
Hi, I did manage to get it running, but I got the "Unrecognised device", as I mentioned in my previous comment.

I did feel a change after installing the package, though. After the installation and a reboot, the USB ports from a hub connected to the Laptop Stand worked better. This leads me to believe that the Laptop Stand's USB ports were hijacked by the openrazer daemon, instead of the system's default USB driver. Does that make any sense for you?

**Comment by z3ntu** [comment]
There should be no change in USB behavior really, we're only taking over from hid-generic driver in some instances (which handles input) but even then normal input is still handled by the same kernel components as before.

**Comment by z3ntu** [comment]
What's the status on this PR?

**Comment by hlriffel** [comment]
Hi, I tested these changes in my recent EndeavourOS installation and the results are the same, so it is indeed nothing related to the method of installation.

**Comment by z3ntu** [comment]
@hlriffel So you're saying with openrazer built from this PR that the daemon (or polychromatic) doesn't detect the device?

**Comment by hlriffel** [comment]
@z3ntu yes, exactly.

**Comment by z3ntu** [comment]
@hlriffel Could you join our chatroom maybe? https://github.com/openrazer/openrazer/wiki/Community-chat

Then I could more easily help to debug this since based on the PR contents there is nothing obviously wrong that would prohibit that.

**Comment by hlriffel** [comment]
After the latest changes, which made the accessory driver for the device to use the mouse interface (2) instead of 0, I can confirm that the daemon now recognizes the Laptop Stand V2 and all the color options are working.

image

**Pull request merged**
