### PR TITLE
[WIP] Add support for Razer Chroma ARGB Controller

### LINKED ISSUE #1357: Support for Razer Chroma Addressable (ARGB) LED Controller
### Device Info

* Name: Razer Chroma Addressable LED controller
* Product Number: RZ34-021406
* Model Number: 
* Razer Website: https://www.razer.com/gaming-pc-accessories/razer-chroma-addressable-rgb-controller/RZ34-02140600-R3M1

### Device Information

USB ID: 1532:0F1F (interfaces 0, 1, 2)

### Packet Captures

[ChromaAddressableController_SynapseStartup.zip](https://github.com/openrazer/openrazer/files/5624610/ChromaAddressableController_SynapseStartup.zip)

At around 12 seconds I click the reset button and it rescans the number of attached LEDs.  This appears to use standard 90-byte reports:
[ChromaAddressable_ResetLEDSizeAuto.zip](https://github.com/openrazer/openrazer/files/5625872/ChromaAddressable_ResetLEDSizeAuto.zip)

### HID Descriptor

```
adam@adam-linux-desktop:~/Downloads$ sudo usbhid-dump -d 1532:0f1f
001:005:002:DESCRIPTOR         1606852527.819101
 05 0C 09 01 A1 01 06 00 FF 09 02 15 00 25 01 75
 08 95 10 81 00 C0

001:005:001:DESCRIPTOR         1606852527.822074
 05 0C 09 01 A1 01 06 00 FF 09 02 15 00 25 01 75
 08 96 40 01 B1 01 C0

001:005:000:DESCRIPTOR         1606852527.825013
 05 0C 09 01 A1 01 06 00 FF 09 02 15 00 25 01 75
 08 95 5A B1 01 C0
```

Interface 0 - 90 bytes (standard Razer report, existing control seems to work here, usage page 0x0C and usage 0x01)

Interface 1 - 320 bytes (looks to be direct mode packets that can hold the full 80 LEDs per channel RGB data, also 0x0C 0x01)

Interface 2 - 16 bytes (not sure what this is for, also 0x0C 0x01)

### Synapse Screenshots

Supports auto-detection of LED count and enabled ports, but also supports manual LED sizing.  Looks to cap out at a maximum of 80 LEDs per channel.

image

Individual channel brightness options

image

I just ordered this controller and would like to get it added to OpenRazer/OpenRGB.  My guess is that it's going to have a command to resize each channel in addition to the modes/direct control messages.

### PR DESCRIPTION
**Pull request by CalcProgrammer1**
Implements control for Razer Chroma ARGB controller (#1357), which also requires adding support for the 320-byte custom frame packet used for direct control of channels on this controller.

Not yet implemented:

* Resizing output
* Auto-detect size

Tested:

* Brightness control (all outputs linked)
* None mode
* Static mode
* Breathing mode (only seems to support single color, random and 2 color modes aren't working properly)
* Spectrum Cycle mode
* Wave mode
* Custom mode + Custom frame
* Device information (name, serial, version)

### CODE REVIEW

**Comment by CalcProgrammer1** [comment]
Forgot I had the win32 patch in this branch, ignore it for now, I will remove it later.

**Comment by paxos** [comment]
Thats great 👍  how do we get this merged?

**Comment by CalcProgrammer1** [comment]
Here's a function for setting the channel sizes (0 disables the channel, valid sizes 1-80).

I captured the packet from Synapse 3 when changing the LED count manually to figure this one out.  The code is from my RazerController in OpenRGB that is heavily based on OpenRazer but uses hidapi for communication.  I renamed some functions slightly but it should be very easy to port into OpenRazer.

```
razer_report RazerController::razer_create_addressable_size_report
    (
    unsigned char zone_1_size,
    unsigned char zone_2_size,
    unsigned char zone_3_size,
    unsigned char zone_4_size,
    unsigned char zone_5_size,
    unsigned char zone_6_size
    )
{
    razer_report report         = razer_create_report(0x0F, 0x08, 0x0D);

    report.arguments[0]         = 0x06;
    report.arguments[1]         = (zone_1_size == 0) ? 0x01 : 0x19;
    report.arguments[2]         = zone_1_size;
    report.arguments[3]         = (zone_2_size == 0) ? 0x02 : 0x19;
    report.arguments[4]         = zone_2_size;
    report.arguments[5]         = (zone_3_size == 0) ? 0x03 : 0x19;
    report.arguments[6]         = zone_3_size;
    report.arguments[7]         = (zone_4_size == 0) ? 0x04 : 0x19;
    report.arguments[8]         = zone_4_size;
    report.arguments[9]         = (zone_5_size == 0) ? 0x05 : 0x19;
    report.arguments[10]        = zone_5_size;
    report.arguments[11]        = (zone_6_size == 0) ? 0x06 : 0x19;
    report.arguments[12]        = zone_6_size;

    return report;
}
```

**Comment by z3ntu** [comment]
@paxos Somebody will have to write the daemon support for this device

**Comment by gregghz** [comment]
Is there a development guide somewhere for openrazer? I'd love to build/test/otherwise help with this PR in an effort to get it merged. I'm a bit unclear on what work remains though or where it should go.

**Comment by z3ntu** [comment]
@gregghz You can build this branch with https://github.com/openrazer/openrazer/wiki/Building-a-package , for writing daemon support you can check recent commits for references. You can also launch the daemon without rebuilding the package with
```
env PYTHONPATH="pylib:daemon" python3 ./daemon/run_openrazer_daemon.py -Fv --config=(pwd)/daemon/resources/razer.conf
```
You can also join the [Matrix/Telegram chat](https://github.com/openrazer/openrazer/wiki/Community-chat) if you have more questions.

**Comment by gregghz** [comment]
So I tried to use this branch with Polychromatic but it just says no devices detected. Can you perhaps provide more info on how to test this? @z3ntu

**Comment by z3ntu** [comment]
@gregghz That's because of this https://github.com/openrazer/openrazer/pull/1391#issuecomment-835259639 . Check recent device support commits, someone needs to add the Python class describing the device for GUI applications to be able to interact with the device.

**Comment by Naitrate** [comment]
Are there any updates on this? I'd like to run my ARGB Controller and Tartarus Pro inside of Linux, but neither of those are seemingly compatible at the moment.

**Comment by z3ntu** [comment]
@KingKrouch Please read my last comment

**Comment by diffficult** [comment]
@z3ntu If I understood what  I read it means that adding the ARGB controller support would solve at least the RGB settings for stuff like the Tartarus Pro, right?

**Comment by z3ntu** [comment]
@diffficult Yes, you'd be able to control the lights, change effects and whatever

**Comment by paxos** [comment]
How can I help with this?

**Comment by brett-smith** [comment]
I've been messing around with this PR to get support into Snake. I have resolved the conflicts and filled in some gaps, enough to get it to work with Snake and Polychromatic (maybe others?). 

I haven't yet created a PR for this, but have a patch available at https://gist.github.com/brett-smith/346cda0a420f8afef8c5431770564681

It has everything in the original PR, plus ..

 * Driver - Working device get brightness (average of all channels)
 * Driver - Working channel get/set brightness
 * Driver - Working channel get/set channel size
 * Driver - WIP. An attempt at initiating an auto detection scan.
 * Daemon - Basic DBus methods. This is enough for it to work with current unmodified clients. Hardware effects / matrix can be set and overall device brightness can be changed.
 * Daemon - Extended DBus methods. Each Channel has an endpoint `razer.device.lighting.channel1` through to `razer.device.lighting.channel6`. These interfaces provide the channel specific `getChannelXBrightness()` and `getChannelXSize()` and the corresponding setters. Clients will of course have to add specific support for this.

Two things remain to be fixed as far as I can tell.

Firstly as mentioned in the points above, the auto detect doesn't work yet. I have tried to replicate what Synapse was doing, but there must be more too it, or my implementation is just wrong.  It's not strictly required, it seems to auto configure by default after a boot, you just call get size on each channel. Those with zero have nothing plugged in or otherwise not responding.

The second remaining issue may be specific to my hardware. I'm just putting this out there in case anyone has any idea what is happening, or sees the same thing.

After a reboot, the device is only detected if it is the ONLY one using `razeraccessory`.   If I attempt to boot with any or all of a Kraken Headset, a Firefly V2, Nommo Chroma or Base Stand plugged in, then only those devices will be found, the ARGB controller will not be.  It appears `hid-generic` keeps the device,.

Removing and re-adding the module doesn't work. The plugdev permissions aren't applied for a start, so it's like the udev rules aren't right.  For now, I have worked around this, but running the little script below as root. 

```#!/bin/bash
rmmod razeraccessory
sleep 3
modprobe razeraccessory

for i in $(find /sys -name device_type) ; do
	d=$(dirname $i)
	b=$(basename $d)
	/lib/udev/razer_mount razeraccessory $b
done
```

**Comment by z3ntu** [comment]
@brett-smith If you're interested in finishing up this PR to get it into a mergeable state feel free to open a new PR with your changes on top.

**Comment by brett-smith** [comment]
Sure thing.

I've been holding back on this due to the issue of it not finding the device at boot unless its the only one using `razeraccessory`. Will put a bit more time into this today. If I don't get anywhere, will make a PR anyway, perhaps someone else will have an idea.

**Comment by z3ntu** [comment]
This is obsoleted by #1762 which in turn is now superseded by #1929

**Pull request closed without merging**
