### PR TITLE
Add starlight effect to Blade Stealth models

### PR DESCRIPTION
**Pull request by mgruppi**
Add starlight effect to Blade Stealth keyboards as addressed in #809 
Add device files to keyboard driver and added effect to list in the keyboard daemon.
**Affected models:** 
- Blade Stealth (early) 2016
- Blade Stealth Late 2016
- Blade Stealth Mid 2017
- Blade Stealth Late 2017

It seems the Blade Stealth 2019 does not support per-key chroma so I did not add the effect to this model.

**Razer Blade 2019 Advanced:**
I'm also correcting a mistake I made on a previous pull request where I set MATRIX_DIMS to [6,15]. The matrix really has only 15 columns but it seems to use a base index of 1 so it has to be [6,16].

### CODE REVIEW

**Comment by z3ntu** [comment]
If you say, "all" Blades support the starlight effect, then there are several devices where it isn't added in this PR.

**Comment by mgruppi** [comment]
Sorry, I didn't mean that all Blades support it. I've only added to Blade Stealth editions that are known to have per-key lighting. I suspect that the 2019 model does not support starlight since it seems to have single-zone lighting instead of per-key lighting.

**Comment by z3ntu** [comment]
Could you please rebase on master?

**Comment by mgruppi** [comment]
I made the changes but it hasn't showed up. It could be because I accidentaly deleted the repo. Should I open a new PR with the same changes instead?

**Comment by mgruppi** [comment]
I made the changes but it hasn't showed up. It could be because I accidentaly deleted the repo. Should I open a new PR with the same changes instead?

**Comment by nightsky30** [comment]
I own a Blackwidow Chroma V2 that supports the starlight effects as well.  The other day I took a look at why it was not available despite having the effects listed for the hardware in the openrazer daemon.

I found and added the missing parts within my RazerGenie [branch](https://github.com/nightsky30/RazerGenie/tree/add-starlight), and that enabled selection of starlight on my keyboard.

I also identified a few issues in the openrazer daemon that I fixed in this [branch](https://github.com/nightsky30/openrazer/tree/fix-starlight) that were causing starlight single and dual effects to render as only red starlights due to parameter order and lack of secondary rgb values.

Because I wasn't sure which parameter order in the openrazer daemon or RazerGenie was correct I cross tested my changes on Polychromatic.  Starlight is working for me with RazerGenie and Polychromatic now with the above test branches.  I've not created pull requests yet, but plan on it.

I mention all of this because I thought my changes might help you test your Blade additions.

**Comment by jmachen** [comment]
I'm eager to test this out :)
Thanks to @mgruppi @z3ntu and @nightsky30 for their contributions.

**Comment by z3ntu** [comment]
`set_starlight_single_effect` and `set_starlight_dual_effect` are not available on those devices?

**Comment by jmachen** [comment]
> `set_starlight_single_effect` and `set_starlight_dual_effect` are not available on those devices?

For neither my 2016 (OG) razerblade stealth nor my black widow chroma v2.  Both support starlight and fire in Windows.  Neither seem to support it in any of the three OpenRazer aware configuration apps I have tried:  (Genie, Commander, Polychromatic)

**Comment by z3ntu** [comment]
> `set_starlight_single_effect` and `set_starlight_dual_effect` are not available on those devices?

@mgruppi ?

**Comment by mgruppi** [comment]
> > `set_starlight_single_effect` and `set_starlight_dual_effect` are not available on those devices?
> 
> @mgruppi ?

@z3ntu Sorry for the belated response. I was completely oblivious to startlight_single and startlight_dual effects. I have added such effects (in addition to starlight_random) to Blade Stealth models 2016 and 2017, as well as the Razer Blade Advanced 2019. It's all in [this branch](https://github.com/mgruppi/openrazer). I think I have addressed all the issues so far, let me know otherwise.

@jmachen The Blade Stealth 2016 was missing driver files for starlight effects, which have been added in the above repo.

**Comment by z3ntu** [comment]
For some reason this PR is broken, I'll just push that commit directly. Thanks!

**Comment by XinqiBao** [comment]
I recently have a PR related kbd chroma starlight, and need some help with testing on several devices, it would be nice you can do that. Thanks, #978

**Comment by jmachen** [comment]
> I recently have a PR related kbd chroma starlight, and need some help with testing on several devices, it would be nice you can do that. Thanks, #978

Sure, I will try to do this tonight.

**Pull request closed without merging**
