### PR TITLE
Add layout 0x0f (Swiss-german, de_CH)

### PR DESCRIPTION
**Pull request by maugier**
It's technically almost the same as the swiss-french layout (fr_CH), with 3 keys having their plain and shifted symbol swapped. Both are printed on the keys, so I'm not sure how this should be handled.

### CODE REVIEW

**Review by z3ntu — APPROVED** [review]
Thanks! Regarding your comment, the daemon doesn't really care about what labels are printed on the keys, it's just providing a lookup for different GUIs to interpret and display the correct layout (if available).

**Comment by z3ntu** [comment]
Hi, could you please check whether the `Allow edits by maintainers` option is enabled for this pull request? I'd need that for merging so that GitHub realizes that this pull request has been merged when I merge it manually.

**Comment by maugier** [comment]
Hi, 

  Looks enabled on my side, is it that one?

image

**Comment by z3ntu** [comment]
Weird, I would have thought so but github won't let me push to your repo. GitHub support doesn't really know either what's going on. Can you give me explicit permissions to your repo by adding me as collaborator in the settings of your fork? The url is probably https://github.com/maugier/openrazer/settings/access for you

**Comment by maugier** [comment]
Ah, I think it's my fault. I accidentally forked from another public fork of your repo, and I just rebased against your master branch when I realized. I didn't suspect this could cause a permission problem.

**Comment by z3ntu** [comment]
Nah, just some github bugs I presume, thanks again for the PR!

**Pull request merged**
