### PR TITLE
Add support for Razer Blade 15 Advanced (Late 2019)

### LINKED ISSUE #1041: Support for Razer Blade Advanced 2019 model with optical keyboard
Hello to all,

Thank you for your hard work and for making the drivers for razer available in linux.

I'm running kubuntu 19.10

I would like to ask whether the model 1532:024b (2019 advanced 15 inch model with optical keyboard) is supported, or whether there are plans ( if it would be possible ) to support it in the future. It doesnt appear on the list of the homepage of the github project.

For reference I am currently  using the drivers version 2.7.0 and loaded them using `sudo modprobe razerkbd`

I tried to follow https://github.com/openrazer/openrazer/wiki/Setting-up-the-keyboard-driver, but I'm stuck at the binding stage with the following message

```
root:/sys/bus/hid/drivers/razerkbd# echo -n "0003:1532:024B.0004" > bind      
-bash: echo: write error: No such device
```

For information, I have 
```
user:/sys/bus/hid/drivers/hid-generic$ ls -l
total 0
lrwxrwxrwx 1 root root    0 mar  8 12:47 0003:0461:0010.0005 -> ../../../../devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/0003:0461:0010.0005
lrwxrwxrwx 1 root root    0 mar  8 12:47 0003:0461:0010.0006 -> ../../../../devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1/0003:0461:0010.0006
lrwxrwxrwx 1 root root    0 mar  8 12:47 0003:1532:024B.0002 -> ../../../../devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.0/0003:1532:024B.0002
lrwxrwxrwx 1 root root    0 mar  8 12:47 0003:1532:024B.0003 -> ../../../../devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.1/0003:1532:024B.0003
lrwxrwxrwx 1 root root    0 mar  8 13:02 0003:1532:024B.0004 -> ../../../../devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.2/0003:1532:024B.0004
--w------- 1 root root 4096 mar  8 13:02 bind
lrwxrwxrwx 1 root root    0 mar  8 12:47 module -> ../../../../module/hid_generic
--w------- 1 root root 4096 mar  8 12:47 new_id
--w------- 1 root root 4096 mar  8 12:23 uevent
--w------- 1 root root 4096 mar  8 12:57 unbind
```

with the device ending in 004 being the mouse device.

Thank you for the help and for your time

Edit : here is the output of ` lsusb -v -d 1532:024b`

```


Bus 001 Device 004: ID 1532:024b Razer USA, Ltd Razer Blade
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x024b 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1

```

### LINKED ISSUE #1727: Support for [Razer Blade 15 Advanced late 2019]
Please incorporate device support changes for dev id 24B   of Razer Blade 15 Advanced Late 2019  from the link

https://github.com/napsterred/openrazer.github.io

### PR DESCRIPTION
**Pull request by lah7**
Changes extracted from #1727. Credit goes to @napsterred.

I don't own this device, so can't confirm 100% working, but the changes look good to me.

Closes #1727.
Fixes #1041 (under the assumption the optical keyboard already works or is out of scope for OpenRazer?)

### CODE REVIEW

**Review by napsterred — APPROVED** [review]

**Review by napsterred — APPROVED** [review]

**Comment by napsterred** [comment]
hey guys, is there a merge button i should be clicking on ?

**Review by napsterred — APPROVED** [review]

**Comment by LinuxDonald** [comment]
This should be merged by an developer of this project.

**Comment by lah7** [comment]
No further action is necessary on your part, @napsterred. Thanks for putting this together. 

It needs at least a second review. The automated CI system looks broken ❌  which would catch any errors. Ideally any one who owns this device should comment here that it works for them too.

**Comment by z3ntu** [comment]
@advl Could you please test this PR and see if it works for you? https://github.com/openrazer/openrazer/wiki/Building-a-package

**Comment by z3ntu** [comment]
@napsterred Someone needs to build this branch and confirms it works.

**Comment by napsterred** [comment]
It worked for me. I think not a lot of people ever bought this model of laptop and even few like to use linux on it.

**Comment by z3ntu** [comment]
@advl @LinuxDonald Could you please test this PR? Build instructions are here: https://github.com/openrazer/openrazer/wiki/Building-a-package

**Comment by napsterred** [comment]
Hey guys, was the device id updated in the new openrazer kernal, if not i can provide an updated kbrddriver.c file ? If not, what additional data is required to get it to work.   Thanks, much appreciate your efforts.

**Comment by z3ntu** [comment]
@napsterred Please build this branch using the instructions at https://github.com/openrazer/openrazer/wiki/Building-a-package and send a screenshot of e.g. polychromatic or RazerGenie please.

**Comment by HaiderAli998** [comment]
Can confirm this to be working on arch linux
Screenshot_20240331_135939

**Comment by HaiderAli998** [comment]
Can confirm this to be working 
Screenshot_20240331_135939-1

**Pull request merged**
