### PR TITLE
Add support for Razer Core X Chroma

### LINKED ISSUE #929: Support for [Razer Core X Chroma]
### Device Info

* Name: CORE X CHROMA - External graphics enclosure
* Product Number: NO NUMBER
* Model Number: RC21-0143

### Device Information
```
lsusb -d 1532: -v

Bus 001 Device 003: ID 1532:0f1a Razer USA, Ltd 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0f1a 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           84
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1

```

```
Please post the output of
    lrwxrwxrwx 1 root root  10 oct.  15 13:32 usb-Razer_Razer_Core_X_Chroma-event-if01 -> ../event11
lrwxrwxrwx 1 root root   9 oct.  15 13:32 usb-Razer_Razer_Core_X_Chroma-event-kbd -> ../event7
lrwxrwxrwx 1 root root   9 oct.  15 13:32 usb-Razer_Razer_Core_X_Chroma-if01-event-kbd -> ../event8
lrwxrwxrwx 1 root root  10 oct.  15 13:32 usb-Razer_Razer_Core_X_Chroma-if02-event-mouse -> ../event12
lrwxrwxrwx 1 root root   9 oct.  15 13:32 usb-Razer_Razer_Core_X_Chroma-if02-mouse -> ../mouse2

```

### Synapse Screenshots
I don't have a windows computer :/

### PR DESCRIPTION
**Pull request by rosterloh**
Still doing some testing but feedback welcome

Fixes #929

### CODE REVIEW

**Comment by rosterloh** [comment]
resolves #929

**Comment by SethGower** [comment]
I am trying to run your branch of this, but it is still not recognizing the Core X Chroma. I installed via the AUR and modified the `PKGBUILD` per the instructions [here](https://github.com/openrazer/openrazer/wiki/Building-a-package#install-from-aur). Here is the output from the "Troubleshoot" menu on Polychromatic
image

**Comment by rosterloh** [comment]
You're right. Everything looks fine when I try to debug but DeviceManager does not detect the device.

image

**Comment by rosterloh** [comment]
@z3ntu do you have any suggestions for how to debug this issue? _fake_driver/razercorexchroma.cfg has 0003:1532:0F1A.0001 in the path field but it looks like 6/8/A are the input paths. Could this be it?

**Comment by z3ntu** [comment]
@rosterloh The fake driver is completely irrelevant to normal usage, it's just for emulating the device for testing the daemon and stuff.

**Comment by turbos-and-tacos** [comment]
@rosterloh This works for me!

EDIT:
This worked for me exactly one time. I haven't been able to get it to work again since taking the screenshot.
image

**Comment by turbos-and-tacos** [comment]
@rosterloh I think this device needs a different transaction id number than what you are using. I have the changes locally that are working. Do you want me to push those changes into this branch or make a new one?

**Comment by rosterloh** [comment]
Whatevers easiest for you really. Thanks for testing.

**Comment by turbos-and-tacos** [comment]
> Whatevers easiest for you really. Thanks for testing.

Seems like I can't push into your fork. I'll have to create a new one.

**Comment by rosterloh** [comment]
@turbos-and-tacos am I missing something or is your branch exactly the same as mine? Compare https://github.com/turbos-and-tacos/openrazer/compare/core-x-support...rosterloh:openrazer:core-x-support

**Comment by turbos-and-tacos** [comment]
@rosterloh I'm not quite sure what happened with my last push. My commit history has some differences that I meant to commit. Namingly I had the starlight effect setup and tested for the core. I did pull then push because git was claiming my branch was out of date. I'll get it sorted today. Sorry for the confusion.

**Comment by z3ntu** [comment]
Let's close this in favor of #1998 then, okay?

**Pull request closed without merging**
