### PR TITLE
AsyncIO and Blade Pro fixes

### PR DESCRIPTION
**Pull request by hyperb1iss**
This does add a few dependencies, notably the evdev module. Ubuntu 16.10 is carrying an old version- we need 0.6.4 which has the async event loop. Also requires Python 3.5, not sure if that will fly or not?

### CODE REVIEW

**Comment by terricain** [comment]
Is looking good. Have a feeling the last udev change will have temporarily broke the mice but its a good improvement none the less. Will test this weekend.

**Comment by hyperb1iss** [comment]
Will clean up the Codacy comments tomorrow.

**Comment by hyperb1iss** [comment]
I'll try and pick up one of their mice too since I'll need it to test uchroma.

**Comment by terricain** [comment]
Last udev broke firefly and mice, but then again its an easy fix as I can just tell it to only use the mouse interface. Also udev script needs a delay inbetween the mount/unmount as it takes some time. Have put in an entry to log to syslog. Will commit that along with driver changes.

**Comment by terricain** [comment]
Then will test this branch ;)

**Comment by hyperb1iss** [comment]
Is it safe to assume that all keyboards use interface number 2 (the "mouse" interface)? I know Firefly is hardcoded for interface number 1. What about mice? Do they enumerate with multiple interfaces?  Any chance you could send me the report descriptors (hidrd-convert -o spec < /sys/xxx/report_descriptor) for a couple of the esoteric ones?

**Comment by terricain** [comment]
Have fixed all devices currently to bind on all interfaces but only present actual options on the mouse interface so we can just bind all

**Comment by terricain** [comment]
From my mamba
```
$ hidrd-convert -o spec < /sys/bus/hid/drivers/razermouse/0003:1532:0044.0008/report_descriptor
Usage Page (Desktop),               ; Generic desktop controls (01h)
Usage (Mouse),                      ; Mouse (02h, application collection)
Collection (Application),
    Usage (Pointer),                ; Pointer (01h, physical collection)
    Collection (Physical),
        Usage Page (Button),        ; Button (09h)
        Usage Minimum (01h),
        Usage Maximum (05h),
        Logical Minimum (0),
        Logical Maximum (1),
        Report Size (1),
        Report Count (5),
        Input (Variable),
        Report Size (1),
        Report Count (3),
        Input (Constant, Variable),
        Usage Page (FF00h),         ; FF00h, vendor-defined
        Usage (40h),
        Report Size (8),
        Report Count (2),
        Logical Minimum (-127),
        Logical Maximum (127),
        Input (Variable),
        Usage Page (Desktop),       ; Generic desktop controls (01h)
        Usage (Wheel),              ; Wheel (38h, dynamic value)
        Logical Minimum (-127),
        Logical Maximum (127),
        Report Size (8),
        Report Count (1),
        Input (Variable, Relative),
        Usage (X),                  ; X (30h, dynamic value)
        Usage (Y),                  ; Y (31h, dynamic value)
        Logical Minimum (-32768),
        Logical Maximum (32767),
        Report Size (16),
        Report Count (2),
        Input (Variable, Relative),
    End Collection,
    Usage Page (FF00h),             ; FF00h, vendor-defined
    Usage (02h),
    Logical Minimum (0),
    Logical Maximum (1),
    Report Size (8),
    Report Count (90),
    Feature (Constant),
End Collection
```

**Comment by hyperb1iss** [comment]
Thanks..   So it looks like commands are only accepted on the endpoint with that vendor-defined usage page then..  I want to do the "right" thing in uchroma when enumerating devices instead of hard-coding a convention.

**Comment by terricain** [comment]
Still havent got round to testing, but i do intend to :wink: is a good excuse to learn #async

**Comment by terricain** [comment]
Will close this PR at some point as have merged it into `cyanogen-async` branch (so pr against that if you want). It looks good, will need a few modifications to be functionally equivalent to the normal daemon (test mode and normal keyboard FN+Keys, M1-M5 was broken but looking at it, its an easy fix).

The bigger issue comes down to `python3.5`, `python3-evdev` and `gbulb`.
- Python 3.5, I think (if I'm not mistaken) if we just change `async def` to the decorated form and change `await` to `yield from` then it _should_ be functionally equivalent and work for Python 3.4
- gbulb, That should be a very simple case of making a package for it and adding it to my PPA / RPMs
- python3-evdev, Again in theory I should be able to just grab the `./debian` directory from the source tarball and recreate it for 0.6.4.

Any thoughts on the Python 3.4 stuff?

**Comment by hyperb1iss** [comment]
Can give the 3.4 syntax a shot, I think it's functionally equivalent but hideous to mentally parse :)  This was my first adventure into asyncio (but not this style of programming) and the 3.5 syntax seems really well done, I'm impressed!  Just noticed that Ubuntu LTS is on 3.4, so yeah probably a good idea.

**Comment by terricain** [comment]
> I think it's functionally equivalent but hideous to mentally parse :)

Definitely agree :wink:. I personally want to go to 3.5 but we got some old fedora/opensuse on 3.4.

> This was my first adventure into asyncio

Same, looked at what was done and it looks real nice so far. I'd say close this and PR against branch `cyanogen-async` as I merged the current changes there as this set of changes will take some doing.

Did a bit of work towards this last night though. Now have python3-evdev (and python2 equivlent for some reason) and python3-gbulb .deb's in my testing PPA so thats sorted :smile:

**Comment by terricain** [comment]
Made a issue for this

**Comment by hyperb1iss** [comment]
Check my master branch for the 3.4 patch.

**Pull request closed without merging**
