### PR TITLE
Add Razer Blade Pro FullHD

### PR DESCRIPTION
**Pull request by ghost**
Adds support for Razer Blade Pro FullHD variant.  Static and Reactive modes do not respond to settings.

### CODE REVIEW

**Comment by ghost** [comment]
Correction on this, static and reactive do work, ripple does not.  It seems only illuminate the right side of the trackpad.

**Comment by terricain** [comment]
Yeah ripple issue is known. Have to ask, you've tested everything else right?

**Comment by ghost** [comment]
Tested with polychromatic, all seems to be in order.  All the effects work with the exception of the ripple effects.  Colors change, brightness changes.  If there is anything specific you would like me to test I wouldn't be opposed to it.  This is essentially the same device as the 4k version, just without the mechanical bits.

**Comment by terricain** [comment]
Meh, that should be enough, 90% of the stuff is copy/paste, even at the firmware level so normally things just work. Good work man, :-) I like it when people do the work for me.

**Comment by ghost** [comment]
Ha, thanks for doing it in the first place.

**Comment by terricain** [comment]
Np :smile:

**Pull request merged**
