### PR TITLE
add lighting_pulsate/static methods

### PR DESCRIPTION
**Pull request by meeuw**
Fixes (partially?) #1575

Haven't tried this with the actual hardware but it doesn't crash using razer-emulator.

### CODE REVIEW

**Review by lah7 — COMMENTED** [review]
Thanks for looking into this. I noticed a few things while working on #1673:

* With fake driver, it seems to work via D-Bus endpoint.
* `getStatic` is missing.
* With fake driver, doesn't look like it works via pylib.

I do wonder on the pylib side if we need to split this capability/function for BW2013's static/pulsate? (Boolean only, does not take RGB parameters like others)

Also spotted an edge case: Effect sync throws an exception if another device supporting pulsate (the RGB kind) is present.
```
2022-11-05 15:43:08 | razer.device172.effect_sync    | ERROR    | Caught exception trying to sync effects.
Traceback (most recent call last):
  File "/ramdisk/openrazer-meeuw/daemon/openrazer_daemon/misc/effect_sync.py", line 166, in run_effect
    effect_func(*args)
TypeError: set_logo_static_naga_hex_v2() missing 3 required positional arguments: 'red', 'green', and 'blue'
```

**Comment by meeuw** [comment]
> With fake driver, it seems to work via D-Bus endpoint.

Great!

> getStatic is missing

The kernel module only supports writing this value (razer_attr_write_matrix_effect_static), no reading.

> With fake driver, doesn't look like it works via pylib.

These are new APIs in pylib, not sure how you're testing this but the application actually need to implement these APIs.

Could you please tell me how to reproduce the "Effect sync" ? I'm a bit puzzled how this relates to razer mice.

**Comment by lah7** [comment]
> The kernel module only supports writing this value (razer_attr_write_matrix_effect_static), no reading.

Ah, sorry. I didn't check the driver. My bad, I remember from https://github.com/polychromatic/polychromatic/issues/443 that a user mentioned there are two types of pulsate (`1` or `2`), so I just got confused thinking the device **might** of had the ability to say "`1`, I am static!". 

> These are new APIs in pylib, not sure how you're testing this but the application actually need to implement these APIs.

I couldn't find them. I use the Python interpreter:
```python
import openrazer.client
a = openrazer.client.DeviceManager()
b = a.devices[0]
b. [tab key to autocomplete and poke around]
```

I used "Razer Orbweaver" under the fake driver, as that supports both BW2013 pulsate and BW2013 static. To launch that:
```bash
openrazer-daemon -s
cd /path/to/openrazer/repo
./scripts/ci/setup-fakedriver.sh
./scripts/ci/launch-daemon.sh
```

So, I'm assigning `b = a.devices[<int for the orbweaver>]`, but there is no `b.fx.pulsate()`, and `b.fx.static(r,g,b)` returns `False`. Those are probably for the RGB one anyway, but I have a feeling it's been too intertwined (broken) all these years for the Python API.

The effect sync exception happens to the daemon process when setting a different RGB device (e.g. BlackWidow Chroma) with `.fx.static(r,g,b)`. Effect sync is the default, but it can be explicitly set via `DeviceManager()`:
```
a.sync_effects = True
```
The exception doesn't happen on `master`, as I just (accidentally) checked that again just now. It would be worth rebasing this PR as a whole bunch of device inconsistencies were addressed yesterday.

Also in `b.capabilities`, there's a mismatch:
```python
"lighting_pulsate": False,
"lighting_static": True,
```

Compared to `master`:
```python
"lighting_pulsate": True,
"lighting_static": False,
```

^^ So I think that may also be why the "sync effect" throws an exception. I think the RGB and "BW2013" versions of pulsate/static are too interlinked.

I think it's worth a separate function for pulsate (taking parameters 0,1 or 2) and a static with no parameters. Maybe with a `bw2013_` prefix? Possibly adding a `lighting_bw2013_{pulsate,static}` capability? This Python API is already clunky, what's 2 more? 😁 

The last catch might be the daemon's software persistence.

**Comment by z3ntu** [comment]
I think this is getting obsoleted by #2086. If you think otherwise please let me know!

**Pull request closed without merging**
