### PR TITLE
Initial support for Razer DeathAdder V2

### PR DESCRIPTION
**Pull request by lsiudut**
Adds initial support for Razer DeathAdder V2. One big caveat involved though.

This is my first Razer device, I have no other to compare what USB interfaces
are being exposed by them. By looking at https://github.com/openrazer/openrazer/pull/1028
I figured that other mouses expose only one Mouse HID device. This one though
exposes two - one with suclass of Boot Interface, one without it. Both of them
can be used to control the mouse, but exposing both of them results in daemon
crashes as they have the same serial. So I reworked the driver to expose only
one - without Boot Interface subclass.

Now, as I said, I don't know if this doesn't break other devices (if they expose
only HID with BP for example). I'm happy to rework the daemon to ignore devices
with serial that was already handled.

Let me know what you think.

Of course the diff is tested, I have full control over the mouse of mine.

### CODE REVIEW

**Comment by lobziik** [comment]
@lsiudut thanks a lot! I built it and all works well!

Small observation - settings that I made are persistent. Mouse stored it in onboard memory.
Probably, the appearance of the second HID connected with this memory somehow.

p.s. I have only one razer device, and can not check how it works with multiple ones.
Or with a different mouse. Might [this](https://github.com/openrazer/openrazer/pull/1093/files#diff-72915fff8b7f6a43f6fa4934e0b9e302R70) line cause problems with other mouses?

**Comment by nightsky30** [comment]
I tested the change and verified this breaks functionality using the interface with no subclass on my Lancehead Wireless and Lancehead TE.  They both use:
```
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
```
Also not sure if this is the same for all mice.

If the DeathAdder V2 can use both, then the Boot Interface Subclass might be preferred (assuming that is the standard).  I also verified my mice were recognized properly after modifying the subclass value from 0 to 1 in the check:
```
if(dev->usb_interface_protocol == USB_INTERFACE_PROTOCOL_MOUSE && dev->usb_interface_subclass == 1)
```
Output of lsusb -v for my mice:
```
Bus 001 Device 009: ID 1532:0060 Razer USA, Ltd Razer Lancehead Tournament Edition
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0060 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1

Bus 001 Device 010: ID 1532:0070 Razer USA, Ltd Razer Lancehead Wireless
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0070 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
```

**Comment by lsiudut** [comment]
Lovely, thanks for checking @nightsky30 . I'll amend the diff in a sec.

Still I'd love someone more experienced to tell whether this approach is fine or shall I rather make the daemon ignore devices with serial that was already processed. Both approaches seems feasible to me.

**Comment by lsiudut** [comment]
@lobziik what you suggested is interesting. Can you check it now, when we actually prefer the other device (with Boot Interface subclass set)?

**Comment by zeroepoch** [comment]
@lsiudut which settings were persistent? Was it the colors (which Synapse can't even do) or just DPI and other settings? The mouse has a hybrid mode (profile 1) which sort of does that same thing in Synapse.

**Comment by lobziik** [comment]
> @lobziik what you suggested is interesting. Can you check it now, when we actually prefer the other device (with Boot Interface subclass set)?

Works well. Behavior seems not changed.

@zeroepoch colors and DPI.

**Comment by dobsonaron** [comment]
I don't know if you need it, but I'm giving you a feedback :) . I didn't know how to install stuff, so did it by hand (patching, compiling, and replacing the kernel modules and the daemon) but at the end it is working without any visible errors. Thank you very much for the time and effort you put into this! (I have only this one mouse as Razer product, so I can't test what happens with multiple devices...)

**Comment by lsiudut** [comment]
@z3ntu kind ping, it seems that you're actively maintaining this repository. Pretty much call for advice.

This change modifies the driver, I don't feel overly comfortable with this approach (unless proven safe and proper). I'm happy to actually leave the driver as is and make userspace just use one of two exposed, seemingly identical, interfaces.

That said, I'm not 100% sure if those interfaces are identical - not after what @lobziik called few comments above. I'll experiment with it a bit more tomorrow (UTC timezone).

**Comment by z3ntu** [comment]
@lsiudut Thanks for the PR!

I'd rather not modify any behavior for existing devices, but I'm guessing something like this could work:
```c
unsigned char expected_subclass = 0xFF;
...
switch(usb_dev->descriptor.idProduct) {
case USB_DEVICE_ID_RAZER_DEATHADDER_V2:
    expected_subclass = 0x01;
    break;
}
...
if(dev->usb_interface_protocol == USB_INTERFACE_PROTOCOL_MOUSE
    && (expected_subclass == 0xFF || dev->usb_interface_subclass == expected_subclass)) {

```
This checks for the subclass if needed (not 0xFF) and ignores it otherwise.
Neither compile tested nor runtime tested ;)

**Comment by lsiudut** [comment]
Perfect, I'm ok with this approach. Will update this PR later today.

**Comment by lsiudut** [comment]
Rebased to upstream master

**Comment by lsiudut** [comment]
Ok, rebased to upstream master, modified per suggestion and tested. Works for me ;-).

**Comment by sandsmark** [comment]
@lsiudut needs another rebase, it seems (conflict in 99-razer.rules)

edit: trying to launch the daemon I seem to get an error that seems semi-related at least (it discovers two devices, but seems to try to register the same dbus object path for both):

image

**Comment by sandsmark** [comment]
quick hack to make it work + make it work with the gui frontends (saw that it implemented all the same as the basilisk in the driver, so just copied the METHODS from that): http://ix.io/2jmB

fwiw, the lsusb -v output: http://ix.io/2jmK

**Comment by lsiudut** [comment]
It shouldn't detect two devices, that's the whole hassle with this diff. Are you sure you built the driver with this patch applied?

I'll rebase it later today.

**Comment by lsiudut** [comment]
This is the code that is suppose to add only one of two exposed HID mouse devices: https://github.com/openrazer/openrazer/pull/1093/files#diff-5ed59dfc81d91d7e54d03bde5888dd10R3005-R3015

**Comment by sandsmark** [comment]
> It shouldn't detect two devices, that's the whole hassle with this diff. Are you sure you built the driver with this patch applied?

Yeah, I built everything from your repo/branch (`git+https://github.com/lsiudut/openrazer.git#branch=deathadder-v2-support`, package version is `89f1be7` which is the last commit unless I'm mistaken). But if you look at the lsusb output, unless I'm missing something there's actually four devices. One mouse with boot, one mouse without boot, and then one keyboard with boot and one without. But I'm as confused as you are why the code isn't handling it correctly.

**Comment by lsiudut** [comment]
Yes it does. At least should, as we filter devices by `usb_pid` first anyway. Plus it works for me and others too, that's really puzzling.

Far stretched, but do you happen to own other razer devices?

**Comment by sandsmark** [comment]
> Yes it does. At least should, as we filter devices by `usb_pid` first anyway. Plus it works for me and others too, that's really puzzling.

Yeah, that's what confused me the most, I assumed it would have been noticed sooner if it was a common problem.

FWIW the mouse was straight out of the box, so never touched by the Windows software, there isn't something that's changed by the official software that affects this?


> Far stretched, but do you happen to own other razer devices?

Nope, just the mouse (I have a boring unicomp keyboard).

**Comment by lsiudut** [comment]
One last thing - one of revisions was wrong and it was actually registering both of the mouse HID devices. Can you verify visually if this code matches your checkout?

https://github.com/openrazer/openrazer/pull/1093/files#diff-5ed59dfc81d91d7e54d03bde5888dd10R3005-R3015

Once again, if you look at it this is where the filtering should happen. If the device is DAv2, then we set expected subclass to 0x01. In that case the DAv2 device with subclass equal 0x00 is not being processed / registered by the driver.

**Comment by lsiudut** [comment]
Stop! I found the bug. It's fixed locally but I forgot to `commit -a` (I use mercurial on daily basis, it doesn't require `-a`, huge trap).

Fix incoming.

**Comment by sandsmark** [comment]
Awesome, thanks! I was starting to wade through the driver, but I do enough kernel stuff at work so wasn't looking forward to it. :-P

**Comment by lsiudut** [comment]
Nah, sorry for the hassle. Code heavy day, week, month ;-).

**Comment by sandsmark** [comment]
Just rebooted, and can confirm that the driver fix works. Still need to add the dbus methods to get the GUI frontends to work, though:

```
  diff --git daemon/openrazer_daemon/hardware/mouse.py daemon/openrazer_daemon/hardware/mouse.py
  index a36a575..c8b68fd 100644
  --- daemon/openrazer_daemon/hardware/mouse.py
  +++ daemon/openrazer_daemon/hardware/mouse.py
  @@ -1768,6 +1768,14 @@ class RazerDeathAdderV2(__RazerDeviceSpecialBrightnessSuspend):
       Class for the Razer DeathAdder V2
       """
       EVENT_FILE_REGEX = re.compile(r'.*Razer_DeathAdder_V2-if0(1|2)-event-kbd')
  +    METHODS = ['get_device_type_mouse', 'max_dpi', 'get_dpi_xy', 'set_dpi_xy', 'get_poll_rate', 'set_poll_rate',
  +               'get_logo_brightness', 'set_logo_brightness', 'get_scroll_brightness', 'set_scroll_brightness',
  +               # Logo
  +               'set_logo_static_naga_hex_v2', 'set_logo_spectrum_naga_hex_v2', 'set_logo_none_naga_hex_v2', 'set_logo_reactive_naga_hex_v2', 'set_logo_breath_random_naga_hex_v2', 'set_logo_breath_single_naga_hex_v2', 'set_logo_breath_dual_naga_hex_v2',
  +               # Scroll wheel
  +               'set_scroll_static_naga_hex_v2', 'set_scroll_spectrum_naga_hex_v2', 'set_scroll_none_naga_hex_v2', 'set_scroll_reactive_naga_hex_v2', 'set_scroll_breath_random_naga_hex_v2', 'set_scroll_breath_single_naga_hex_v2', 'set_scroll_breath_dual_naga_hex_v2',
  +               # Can set LOGO and Scroll with custom
  +               'set_custom_effect', 'set_key_row']

       USB_VID = 0x1532
       USB_PID = 0x0084
```

**Comment by lsiudut** [comment]
Ha, curious. Mine worked with polychromatic, I didn't even realize it is missing :-).

Adding now, thanks!

**Comment by z3ntu** [comment]
Generally looks fine, is this ready to go from your side?

**Comment by lsiudut** [comment]
Yes, fine by me!

**Review by z3ntu — APPROVED** [review]
LGTM, thanks!

**Comment by zeroepoch** [comment]
I know this change is already merged, but I wanted to say thank you for the work! You've accomplished a number things Synapse 3 couldn't do. See https://www.reddit.com/r/MouseReview/comments/en1gw5/deathadder_v2_i_like_it_short_review/ where a few people complained that they couldn't set a static persistent color. You also couldn't set two different color zones, which I can do now with RazerGenie! I've read reviews in other places like Amazon basically complaining about the same thing. You've just added value to this Razer product that I was previously disappointed in.

**Pull request merged**
