### PR TITLE
Added support for BlackWidow V3 Pro (Wireless)

### LINKED ISSUE #1279: Support for BlackWidow V3 Pro [1532:025c]
### Device Info

* Name: BlackWidow V3 Pro
* Product Number: RZ03-03530200-R3U1
* Model Number: RZ03-0353

### Device Information

<details>
  <summary> lsusb -d 1532: -v </summary>

  ```
Bus 001 Device 003: ID 1532:025c Razer USA, Ltd Razer BlackWidow V3 Pro
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x025c 
  bcdDevice            1.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 3 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0086
    bNumInterfaces          5
    bConfigurationValue     1
    iConfiguration          4 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     179
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        4
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     325
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     348
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
  ```
</details>
    
<details>
  <summary>ls -lah /dev/input/by-id/</summary>

  ```
total 0
drwxr-xr-x 2 root root 240 Oct  3 20:34 .
drwxr-xr-x 4 root root 800 Oct  3 20:34 ..
lrwxrwxrwx 1 root root   9 Oct  1 17:28 usb-Logitech_USB_Receiver-if02-event-kbd -> ../event6
lrwxrwxrwx 1 root root   9 Oct  1 17:28 usb-Logitech_USB_Receiver-if02-event-mouse -> ../event4
lrwxrwxrwx 1 root root   9 Oct  1 17:28 usb-Logitech_USB_Receiver-if02-mouse -> ../mouse2
lrwxrwxrwx 1 root root  10 Oct  3 20:34 usb-Razer_Razer_BlackWidow_V3_Pro_000000000000-event-if01 -> ../event27
lrwxrwxrwx 1 root root  10 Oct  3 20:34 usb-Razer_Razer_BlackWidow_V3_Pro_000000000000-event-if03 -> ../event29
lrwxrwxrwx 1 root root  10 Oct  3 20:34 usb-Razer_Razer_BlackWidow_V3_Pro_000000000000-event-kbd -> ../event23
lrwxrwxrwx 1 root root  10 Oct  3 20:34 usb-Razer_Razer_BlackWidow_V3_Pro_000000000000-if01-event-kbd -> ../event24
lrwxrwxrwx 1 root root  10 Oct  3 20:34 usb-Razer_Razer_BlackWidow_V3_Pro_000000000000-if02-event-mouse -> ../event28
lrwxrwxrwx 1 root root   9 Oct  3 20:34 usb-Razer_Razer_BlackWidow_V3_Pro_000000000000-if02-mouse -> ../mouse4
lrwxrwxrwx 1 root root   9 Oct  1 17:28 usb-SteelSeries_Arctis_Pro_Wireless-event-if05 -> ../event7
  ```
</details>

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>
(Coming soon)

### PR DESCRIPTION
**Pull request by geodox**
Depends on #1622 

Special thanks to @IvanVojtko

To build and test
https://github.com/openrazer/openrazer/wiki/Building-a-package

Fixes #1279

### CODE REVIEW

**Comment by IvanVojtko** [comment]
You also need to change max wait because every command is going to time out. See here: https://github.com/openrazer/openrazer/blob/983a089391e3b822ebce69e942e473f871993219/driver/razerkbd_driver.h#L125

**Comment by z3ntu** [comment]
I'm going to wait reviewing this until #1622 is merged

**Comment by geodox** [comment]
@IvanVojtko Most transaction ids indeed are 0x9F, however I can't seem to get spectrum and ripple working. I've tried both 0x1F which is what wired uses, and I've tried 0x9F which works with all other modes.

Some modes also require a couple clicks to successfully change the effect, which leads me back to your above comment. So I've defined used your WAIT_MIN/MAX however that hasn't seemed to affect it whatsoever.

Also I've noticed the effects don't remember the colors they were set to when switching around between effects, where as wired mode does.

Any insight from your endeavours adding V3 MINI Wireless?

**Comment by geodox** [comment]
Once #1622 gets merged, I’ll fix this up. If anyone has any pointers to get spectrum and ripple working, I’ll put some work into it before then

**Comment by nightsky30** [comment]
> @IvanVojtko Most transaction ids indeed are 0x9F, however I can't seem to get spectrum and ripple working. I've tried both 0x1F which is what wired uses, and I've tried 0x9F which works with all other modes.
> 
> Some modes also require a couple clicks to successfully change the effect, which leads me back to your above comment. So I've defined used your WAIT_MIN/MAX however that hasn't seemed to affect it whatsoever.
> 
> Also I've noticed the effects don't remember the colors they were set to when switching around between effects, where as wired mode does.
> 
> Any insight from your endeavours adding V3 MINI Wireless?

- Have you tried transaction ID `0x3F` ?
- The Razer Charging Pad Chroma's (newer accessory) static effect required being set twice with an intermediate packet. You could try a similar approach for the spectrum and other effects that seem to require being set twice here.
- The Razer Charging Pad Chroma also required a different mode `0x03` be set for custom effects (like starlight and ripple). You might want to try switching the mode between `0x00` and `0x03` before sending the ripple effect. Other effects may or may not care what mode the device is in. With the Charging Pad Chroma, it required the mode to be set back to `0x00` before the other non-custom frame (hardware) effects commands were sent.

**Comment by erincar** [comment]
> Once #1622 gets merged, I’ll fix this up. If anyone has any pointers to get spectrum and ripple working, I’ll put some work into it before then

Hey! Looks like that PR is merged... :D Would you happen to have time soon? I'm not experienced in the device support realm at all but I could help if necessary and possible.

**Comment by andriinuts** [comment]
> > Once #1622 gets merged, I’ll fix this up. If anyone has any pointers to get spectrum and ripple working, I’ll put some work into it before then
> 
> Hey! Looks like that PR is merged... :D Would you happen to have time soon? I'm not experienced in the device support realm at all but I could help if necessary and possible.

The author added a comment to the issue: https://github.com/openrazer/openrazer/issues/1279#issuecomment-929603641
He needs USB HID Interface over Bluetooth to have a possibility to continue development

**Comment by z3ntu** [comment]
@GeoDoX What's the state of this PR? Basic functionality working?

**Comment by geodox** [comment]
> 

Can’t get spectrum and ripple working, however everything else that I’ve tested does.

**Comment by z3ntu** [comment]
Do you want to remove spectrum and ripple then, so it can be merged?

**Comment by andriinuts** [comment]
@GeoDoX thx for your work, I think it would be cool to have this device support even without spectrum and ripple

**Comment by z3ntu** [comment]
@GeoDoX ping?

**Comment by nstdio** [comment]
@GeoDoX thanks for work! any chance that you could finalize this?

**Comment by geodox** [comment]
> @GeoDoX ping?

My bad, completely missed your previous comment. I can remove the code for the effects that I couldn’t get working, however I can no longer continue to work on support. After multiple RMAs for this keyboard, I decided to move away from Razer. I’ll look into it later today or tomorrow

**Comment by z3ntu** [comment]
@GeoDoX Any update on this one?

**Comment by z3ntu** [comment]
Actually, closing this in favor of #1901, thanks!

**Pull request closed without merging**
