### PR TITLE
Submit Chroma Feedback

### PR DESCRIPTION
**Pull request by henryruhs**
Add if you like it :-)

### CODE REVIEW

**Comment by terricain** [comment]
:-D

**Comment by henryruhs** [comment]
Off-topic: Is it possible to have OpenRazer as a PyPI dependency one day?

**Comment by z3ntu** [comment]
I don't think so because we'll always require our daemon so just depending on python-openrazer doesn't give you much...

@terrycain Good to merge?

**Comment by henryruhs** [comment]
Yes, I think the library is robust enough now.

I added some [error handling](https://github.com/redaxmedia/chroma-feedback/blob/master/src/core.py#L9-L20) today.

1. _Driver not found_ is needed if you install via `pip install` + no supported device is present
1. _Daemon not found_ is need if you install via `./setup.py install` + no supported device is present

Sorry, for hijacking this pull request but can you explain the difference?

**Comment by terricain** [comment]
Ahh sorry thought I merged this yesterday.

**Comment by terricain** [comment]
First one is an import error, thats down to python not me, will happen if the python library package isnt installed.
Second one will happen if the python daemon isnt running or something messed up with DBus

**Comment by henryruhs** [comment]
Thank you!

**Pull request merged**
