### PR TITLE
Add in logging for custom effects

### PR DESCRIPTION
**Pull request by chabad360**
Just uncommented some lines...

### CODE REVIEW

**Comment by z3ntu** [comment]
I guess those were commented because clients implementing custom effects would spam those methods which would mean the log would be full of those lines. Do you have good reasoning why those prints should be enabled for all users?

**Comment by chabad360** [comment]
I'd be inclined to believe that, but unfortunately custom effects don't seem to be well implemented in GUI clients, and the comment above literally said to uncomment it.

And if we're logging everything else, shouldn't we log this too?

**Comment by lah7** [comment]
I agree that this'll end up spamming the log/stdout, but could be okay for debugging purposes (`-v` or maybe a very verbose flag `-vv`/`-d`).

This might have revealed a bug with how the logger is set up since I see `DEBUG` entries for a `openrazer-daemon` process (started by DBUS)  with `verbose_logging = False`. Logging doesn't currently have any retention practices (e.g. split files / compression) so my `razer.log` already grows to many megabytes over time.

Eventually the GUIs will catch up with their custom effect implementations, but since `verbose_logging` is `True` by default, uncommenting this will give everyone unnecessarily large logs.

**Comment by chabad360** [comment]
That leads to another question, why is verbose logging enabled by default?

**Comment by chabad360** [comment]
> uncommenting this will give everyone unnecessarily large logs.

Only if they use the ripple effect...

**Comment by lah7** [comment]
I would have left this one open for discussion, but I've opened an issue about these points (#1122).

>  why is verbose logging enabled by default?

Git history suggests the code hasn't been touched since the daemon was in its early days:

https://github.com/openrazer/openrazer/blame/b714bc404b549c723c8b25b86feb1066dc56be94/daemon/openrazer_daemon/daemon.py#L257-L261

**Pull request closed without merging**
