### PR TITLE
High-resolution event support

### PR DESCRIPTION
**Pull request by G-M0N3Y-2503**
Added high-resolution event support, to match the output of the default hid driver.

> 	/*
	 * Windows reports one wheel click as value 120. Where a high-res
	 * scroll wheel is present, a fraction of 120 is reported instead.
	 * Our REL_WHEEL_HI_RES axis does the same because all HW must
	 * adhere to the 120 expectation.
	 */
	hi_res = value * 120/usage->resolution_multiplier;

https://github.com/torvalds/linux/blob/master/drivers/hid/hid-input.c#L1302

[Kernel Documentation for `REL_WHEEL_HI_RES`](https://www.kernel.org/doc/html/latest/input/event-codes.html#ev-rel)

### CODE REVIEW

**Comment by G-M0N3Y-2503** [comment]
Dependent on https://github.com/openrazer/openrazer/pull/1597 first

**Comment by z3ntu** [comment]
I've fixed a bug with your PR and tested on Mamba Elite, works fine now. Is this ready to get merged?

**Comment by G-M0N3Y-2503** [comment]
> I've fixed a bug with your PR and tested on Mamba Elite, works fine now. Is this ready to get merged?

Yeah, I just hadn't double-checked running it after rebasing. but it sounds like you have so should be fine.

**Review by z3ntu — APPROVED** [review]
Ok, LGTM

**Pull request merged**
