### PR TITLE
Support for Orbweaver Chroma (1532:0207)

### PR DESCRIPTION
**Pull request by ivanm**

### CODE REVIEW

**Comment by terricain** [comment]
Looks good man, looks good. Have to ask, have you tested every option, at the driver and daemon level?

**Comment by z3ntu** [comment]
@ivanm Did you test everything?

**Comment by gunpinyo** [comment]
Thank you for your PR, I  just bought Orbweaver Chroma and spend an entire night troubleshoot the driver. Looking forward to see this  PR merged. :+1:

**Comment by z3ntu** [comment]
@gunpinyo Did you test everything in this PR? We are just waiting for this to be confirmed to work.

**Comment by z3ntu** [comment]
I rebased this PR on master. Pre-rebase state is at : https://github.com/z3ntu/razer-drivers/tree/orbweaver-chroma-pre-rebase

**Pull request merged**
