### PR TITLE
Update battery_notifier.py

### PR DESCRIPTION
**Pull request by LazyOtto**
I noticed that my comments in the thread "https://github.com/openrazer/openrazer/issues/1662" were incomplete if someone else wanted this behavior.

If I have submitted this inappropriately, I apologize and ask your indulgence and assistance. This is my first contribution to GitHub.

### CODE REVIEW

**Comment by z3ntu** [comment]
@lah7 Could you take a look at this one, at least functionality wise? You've done more with battery notifier in the past

**Review by lah7 — CHANGES_REQUESTED** [review]
I don't really understand the benefits. Logging to file seems unnecessary.

Currently, the user gets to choose the desired % before notifications start to appear (e.g.  🔋  below 20%) and the interval between each reminder (every 5 minutes = 300 seconds). Calling `self.notify_battery()` (line 177) is going to ignore this and regress to the unwanted "spam" behaviour that #1662 was discussing.

Seems like a solution to a problem that doesn't exist. Can't really let the user choose the frequency while also trying to influence how often notifications appear based on %. For that reason, I wouldn't merge, sorry.

**Comment by z3ntu** [comment]
@LazyOtto Any update on this PR?

**Comment by z3ntu** [comment]
Closing because of no response.

**Pull request closed without merging**
