### PR TITLE
Add support for Razer DeathAdder 2013 (#195)

### PR DESCRIPTION
**Pull request by ghost**
## What is working

Pretty much everything! :-)

- [x] Can see serial number, firmware version.
- [x] Can set logo/scroll lighting effects: pulsate, static, blinking.
- [x] Can On/Off logo/scroll light.
- [x] Can adjust DPI between 200-6400.
- [x] Can adjust polling rate between 125Hz-1000Hz.

## Issues

I am very new to the ``openrazer`` project, I have found it today.
So I am not sure if the following issues are real issues (using ``polychromatic-controller`` GUI):

- [ ] For some reason when I am setting the DPI, it does not precisely sets
it to 800, instead it picks some value near to that, e.g. 794. (write or read issue?)  **Upd1** and the value ``900`` isn't getting reduced.

- [x] When I toggle logo/scroll brightness keys, it isn't always working for some reason.
Or sometimes the logo key toggles the scroll key and vice-versa.

- [ ] When changing DPI settings, I can see the following lines in the dmesg:

```
razermouse: Command failed. Start Marker: 03 id: ff Num Params: 03 Reserved: 04 Command: 01 Params: 3c3c0000000000000000000000000000 .
razermouse: Command failed. Start Marker: 03 id: ff Num Params: 03 Reserved: 04 Command: 01 Params: 25250000000000000000000000000000 .
razermouse: Command failed. Start Marker: 03 id: ff Num Params: 03 Reserved: 04 Command: 01 Params: 1e1e0000000000000000000000000000 .
```

I would like the developers to review this PR, see whether everything is Ok..

I've also found there is a razercfg project that has some info related to the Razer DeathAdder 2013 mouse https://github.com/mbuesch/razer/blob/1723b31/librazer/hw_deathadder2013.c

## Update

Mouse specifications https://dl.razerzone.com/master-guides/DA2013/DA2013OMG-ENG.pdf

### CODE REVIEW

**Comment by ghost** [comment]
@terrycain @z3ntu cc

**Comment by lah7** [comment]
> * For some reason when I am setting the DPI, it does not precisely sets it to 800, instead it picks some value near to that
> * When I toggle logo/scroll brightness keys, it isn't always working for some reason.
Or sometimes the logo key toggles the scroll key and vice-versa.

Developer of said GUI here -- they do _sound_ like they could be GUI quirks but can't confirm for sure. 

One way to check if they're "real issues" is to install a tool called **D-Feet** to inspect **`org.razer`** on the **Session Bus**:

image

Or use `python3` and test the Python library directly:

```
import openrazer.client
a = openrazer.client.DeviceManager()
a.dpi
[800,800]
a.dpi = [1600,1600]
[1600,1600]
```

> When changing DPI settings, I can see the following lines in the dmesg:

Hmm, snippet missing - what does it say?

**Comment by ghost** [comment]
Hi, @lah7 . Thanks, I'll take a look at the D-Feet. I've added the missing snipped.

**Comment by ghost** [comment]
@lah7 it returns ``[794, 794]``. So, for some reason it does not fix at ``800``.

The good looking numbers I get when I set DPI to these values: ``900, 1800, 2700, 3600, 4500, 5400, 6300``

Here is a complete table:

```
DPI=200;
while [[ ${DPI} -lt 6400 ]]; do
  let DPI+=100;
  gdbus call --session --dest org.razer --object-path /org/razer/device/PMSNREDACTED --method razer.device.dpi.setDPI "uint16 ${DPI}" "uint16 ${DPI}" > /dev/null;
  echo "${DPI} | \
    $(gdbus call --session --dest org.razer --object-path /org/razer/device/PMSNREDACTED --method razer.device.dpi.getDPI | \
    awk '{print $1}' | \
    tr -dc '[:alnum:]')";
done

gdbus call --session --dest org.razer --object-path /org/razer/device/PMSNREDACTED --method razer.device.dpi.setDPI "uint16 900" "uint16 900"
```

DPI | turns into
--- | ---
300 | 291
400 | 397
500 | 476
600 | 582
700 | 688
800 | 794
900 | 900
1000 | 979
1100 | 1085
1200 | 1191
1300 | 1297
1400 | 1376
1500 | 1482
1600 | 1588
1700 | 1694
1800 | 1800
1900 | 1879
2000 | 1985
2100 | 2091
2200 | 2197
2300 | 2276
2400 | 2382
2500 | 2488
2600 | 2594
2700 | 2700
2800 | 2779
2900 | 2885
3000 | 2991
3100 | 3097
3200 | 3176
3300 | 3282
3400 | 3388
3500 | 3494
3600 | 3600
3700 | 3679
3800 | 3785
3900 | 3891
4000 | 3997
4100 | 4076
4200 | 4182
4300 | 4288
4400 | 4394
4500 | 4500
4600 | 4579
4700 | 4685
4800 | 4791
4900 | 4897
5000 | 4976
5100 | 5082
5200 | 5188
5300 | 5294
5400 | 5400
5500 | 5479
5600 | 5585
5700 | 5691
5800 | 5797
5900 | 5876
6000 | 5982
6100 | 6088
6200 | 6194
6300 | 6300
6400 | 6379

**Comment by ghost** [comment]
@lah7 regarding the other one:

> - When I toggle logo/scroll brightness keys, it isn't always working for some reason.
>   Or sometimes the logo key toggles the scroll key and vice-versa.

When I use the following commands for manual switching, it works without any issue.
It looks like this is the GUI's issue or maybe the openrazer daemon's issue?

The GUI I am using based on the latest master https://github.com/polychromatic/polychromatic/commit/730bdb19fdae3d0e3c6b8d179de9d702362e19d0

```
gdbus call \
  --session \
  --dest org.razer \
  --object-path /org/razer/device/PMSNREDACTED \
  --method razer.device.lighting.logo.setLogoActive 'false'

gdbus call \
  --session \
  --dest org.razer \
  --object-path /org/razer/device/PMSNREDACTED \
  --method razer.device.lighting.scroll.setScrollActive 'false'
```

> I've tried setting each to 'false', then 'true', few times, one-by-one.

**Upd1** One more thing is that the GUI offers changing the logo/scroll RGB colours whilst the mouse does not support anything but the green. Is this hardcoded in the GUI or can be adjusted elsewhere (driver, openrazer)?

**Comment by ghost** [comment]
@lah7 I've added the video (190KB) https://my.nixaid.com/s/oDEpmLotGcGXJcJ

**Comment by lah7** [comment]
> It looks like this is the GUI's issue or maybe the openrazer daemon's issue?
>
> I've added the video (190KB)

Thanks, that's definitely a GUI issue. Polychromatic is undergoing some major changes (WIP in **[dev-0.4.0](https://github.com/polychromatic/polychromatic/tree/dev-0.4.0)** branch) so the *new* toggles are already _fixed_ for the next release. It's a bit in limbo hence no daily builds yet.

> One more thing is that the GUI offers changing the logo/scroll RGB colours whilst the mouse does not support anything but the green.

Does the device support "RGB" in the sense different shades of green can be applied? Or is this device a strictly on/off green light?

AFAIK, there's nothing (currently) in OpenRazer that defines devices that are "RGB" but only output green (like the BlackWidow Ultimate keyboards). That'll be one for [GUIs to determine](https://github.com/polychromatic/polychromatic/blob/dev-0.4.0/pylib/common.py#L609). I'll note to exempt this device for Polychromatic, should this device be one of those "green RGB" devices.

> The good looking numbers I get when I set DPI to these values: 900, 1800, 2700, 3600, 4500, 5400, 6300

I think this should be OK, but you could cross-check with Razer Synapse (if you have a PC or VM) to see which ones are factory presets. Or, see if a value of `800` in Razer Synapse is correctly reported as `800` in OpenRazer.

**Comment by ghost** [comment]
> Does the device support "RGB" in the sense different shades of green can be applied? Or is this device a strictly on/off green light?

The device has only on/off green light. And pulsating of course which by definition is making (50) shades of green :-)

Great to know that the rest is *almost* covered.

I think this PR could be verified by @terrycain / @z3ntu

**Comment by z3ntu** [comment]
PR generally looks good.
The reason for the DPIs being slightly off is that the device squeezes a value of up to 6400 into a single byte, so some precision is lost (which you correctly observed :slightly_smiling_face:), see the lines under https://github.com/openrazer/openrazer/blob/c07a7aae53699d5ce3bb969304c80a89dbe8f479/driver/razermouse_driver.c#L777

**Review by terricain — APPROVED** [review]

**Comment by ghost** [comment]
@z3ntu oh, thanks, that explains! I have just tried setting DPI to 800 in Windows VM using Razer Synapse. Went back to Linux, it shows 741 which is less than 794 according to [my table above](https://github.com/openrazer/openrazer/pull/756#issuecomment-453879046).

Setting the value using the driver ``gdbus call --session --dest org.razer --object-path /org/razer/device/PMREDACTED --method razer.device.dpi.setDPI "uint16 750" "uint16 750"`` shows the same value ``741``.

That's quiet strange -- why Windows sets the DPI to 750 instead of 800? Or, could that be a Linux driver issue?

**Comment by z3ntu** [comment]
I'd rather think that the Windows driver does something weird ;)

**Pull request merged**
