### PR TITLE
Update list of inverted LED state on Blade laptops

### PR DESCRIPTION
**Pull request by lezed1**
* Invert logo state for Razer Blade Stealth Late 2016
* Uninvert Razer Blade Stealth
* Uninvert Razer Blade Stealth Mid 2017

This relates to #479.

### CODE REVIEW

**Comment by z3ntu** [comment]
Rebase on master to fix the CI test please.

**Comment by z3ntu** [comment]
@joonatoona Can you please test this if this fixes it?

**Comment by notjuliee** [comment]
Do you have build instructions anywhere?

**Comment by lezed1** [comment]
What distro are you on?

**Comment by notjuliee** [comment]
My laptop is currently running Solus.

**Comment by z3ntu** [comment]
@joonatoona Clone the git project and run `make` in the top level folder of the repo. Then run `sudo rmmod razerkbd; sudo insmod driver/razerkbd.ko; sudo /lib/udev/razer_mount razerkbd 0003:1532:0205.0001; sudo /lib/udev/razer_mount razerkbd 0003:1532:0205.0002; sudo /lib/udev/razer_mount razerkbd 0003:1532:0205.0003` should do the trick.
Note, that it's possible that your keyboard won't work after this so have an external USB keyboard or so prepared. It might be that the `0001`, `0002` and `0003` are different on your machine. You can check in advance by running `ls -ald /sys/bus/hid/drivers/razerkbd/0003:1532:0205.0*`

**Comment by z3ntu** [comment]
@samr28 Please follow the instructions posted in the previous comment. They should mostly match up (you will have to replace 0205 with 022d at least)

**Comment by z3ntu** [comment]
I'm just gonna merge this as seemingly nobody wants to test this. We can change it back if the updates were wrong.

**Comment by notjuliee** [comment]
Oh, I thought I already commented. These changes fixed it for me.

**Pull request merged**
