### PR TITLE
Support for Razer Naga (1532:0015)

### LINKED ISSUE #139: Razer Naga Support (1532:0015)
Just support for the plain Naga mouse. :)
Bus 003 Device 005: ID 1532:0015 Razer USA, Ltd Naga Mouse

### PR DESCRIPTION
**Pull request by thorsb**
Initial implementation for Razer Naga (1532:0015).
Fixes #139
As far as I can tell, the Naga and the Naga Molten Edition has the same pid.
I have only tested this on the Molten edition (which has a pid of 0015), as I don't have an original Naga.
I used an image of the molten edition in the daemon because I couldn't find a transparent image of the original.
Setting the Scroll light also turns the side buttons to the same state, I have no idea how to fix this.

Features :
- Set Lighting Logo state
- Set Lighting Scroll state
- Set Lighting Backlight state
- Set DPI
- Set Polling rate

### CODE REVIEW

**Comment by z3ntu** [comment]
Awesome to see support for such an old device! I've just asked in https://github.com/openrazer/openrazer/issues/139#issuecomment-2389671719 if somebody wants to test - let's see if anybody subscribed there is still using this mouse since it's nearly 8 years since opening that issue!

Apart from that, the code looks fine! If there's nothing I'll probably just merge it before the doing the next release - hopefully sometime in the next weeks.

**Review by z3ntu — APPROVED** [review]
LGTM, thanks!

**Comment by 0xFADDAD** [comment]
Good to see this finally got pulled, updated to 3.9.0 and now the Daemon is failing to load on startup.
It seems to be choking on initialization `openrazer-daemon -Fv` results in the following:
```
2024-10-09 20:23:31 | razer                          | INFO     | Found device.0: 0003:1532:0015.000A
2024-10-09 20:23:31 | razer.device0                  | INFO     | Initialising device.0 RazerNaga
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/daemonize.py", line 248, in start
    self.action(*privileged_action_result)
  File "/usr/bin/openrazer-daemon", line 141, in run_daemon
    daemon = RazerDaemon(verbose=args.verbose,
  File "/usr/lib/python3/dist-packages/openrazer_daemon/daemon.py", line 117, in __init__
    self._load_devices(first_run=True)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/daemon.py", line 492, in _load_devices
    razer_device = device_class(device_path=sys_path, device_number=device_number, config=self._config,
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/device_base.py", line 136, in __init__
    super().__init__(object_path)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/dbus_services/service.py", line 57, in __init__
    self.add_to_connection(bus, object_path)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 582, in add_to_connection
    connection._register_object_path(path, self._message_cb,
ValueError: Invalid object path '/org/razer/device/



': contains invalid character ''

Stopping daemon.
Exception ignored in atexit callback: <bound method Daemonize.exit of <daemonize.Daemonize object at 0x7e2bc96af280>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/daemonize.py", line 72, in exit
    sys.exit(0)
SystemExit: 0
```
Relevant additional info, I have a BlackWidow Ultimate 2012 (1532:010D) attached as well.

Unpluging and starting the daemon without the Naga works, but plugging the Naga in results in no additional initialization.
[razer.log](https://github.com/user-attachments/files/17320618/razer.log)

**Comment by 0xFADDAD** [comment]
Forgot to mention, I have an original Naga, not the Molten variant.

**Comment by z3ntu** [comment]
@0xFADDAD Please open a new issue for this, happy to help there.

**Pull request merged**
