### PR TITLE
Support for DeathAdder V2 Lite

### LINKED ISSUE #1912: Support for Razer Deathadder v2 lite
### Device Info

* Name: Razer Deathadder v2 lite
* Product Number: RZ01-03340100
* Model Number: v2 lite

### Device Information
```
[mario@Asus-Arch ~]$ lsusb -d 1532: -v

Bus 003 Device 002: ID 1532:00a1 Razer USA, Ltd Razer DeathAdder V2 Lite
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x00a1 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer DeathAdder V2 Lite
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
[mario@Asus-Arch ~]$ 
```

```
[mario@Asus-Arch ~]$ ls -lah /dev/input/by-id/
total 0
drwxr-xr-x 2 root root 200 set 20 22:35 .
drwxr-xr-x 4 root root 540 set 20 22:35 ..
lrwxrwxrwx 1 root root  10 set 20 22:35 usb-Logitech_Wireless_Gamepad_F710_55EA975C-event-joystick -> ../event17
lrwxrwxrwx 1 root root   6 set 20 22:35 usb-Logitech_Wireless_Gamepad_F710_55EA975C-joystick -> ../js0
lrwxrwxrwx 1 root root  10 set 20 22:35 usb-Razer_Razer_DeathAdder_V2_Lite-event-if01 -> ../event13
lrwxrwxrwx 1 root root   9 set 20 22:35 usb-Razer_Razer_DeathAdder_V2_Lite-event-mouse -> ../event9
lrwxrwxrwx 1 root root  10 set 20 22:35 usb-Razer_Razer_DeathAdder_V2_Lite-if01-event-kbd -> ../event10
lrwxrwxrwx 1 root root  10 set 20 22:35 usb-Razer_Razer_DeathAdder_V2_Lite-if02-event-kbd -> ../event14
lrwxrwxrwx 1 root root   9 set 20 22:35 usb-Razer_Razer_DeathAdder_V2_Lite-mouse -> ../mouse2
lrwxrwxrwx 1 root root  10 set 20 22:35 usb-Sonix_Technology_Co.__Ltd._USB2.0_HD_UVC_WebCam-event-if00 -> ../event12
```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>
1)
imagen
2)
imagen
3)
imagen
4)
imagen

### PR DESCRIPTION
**Pull request by Ariel-MX**
Adds support for DeathAdder V2 Lite.

Based on information of DeathAdder V2 Mini, and data from #1912 and existing code for DeathAdder V2 Mini, but with transaction id 0x1f and idProduct  0x00a1. 

Tested locally with Polychromatic against lighting effects including brightness controls, DPI range, and standard polling rates.

It should resolve #1912

### CODE REVIEW

**Comment by z3ntu** [comment]
Diff looks good, very clean PR :)

**Review by z3ntu — APPROVED** [review]
LGTM, thanks again!

**Comment by Mario156090** [comment]
Hello, in this momment I installed open razer, I choose the git package from aur Archlinux and check with a lot of GUI interfaces but does not work yet.

image
image


I checked the trouble wiki and the difference is razerkbd is not load by default, but after load manually the result is same.

image

**Comment by z3ntu** [comment]
@Mario156090 `pacman -Q openrazer-meta-git openrazer-daemon-git openrazer-driver-dkms-git python-openrazer-git` ?

**Comment by Mario156090** [comment]
> @Mario156090 `pacman -Q openrazer-meta-git openrazer-daemon-git openrazer-driver-dkms-git python-openrazer-git` ?

Well, after check the suggested packages, some are not installed. I installed all packages from AUR and my device works perfectly.

Thank's a lot for the job and the support.


image

**Comment by Ariel-MX** [comment]
> > @Mario156090 `pacman -Q openrazer-meta-git openrazer-daemon-git openrazer-driver-dkms-git python-openrazer-git` ?
> 
> Well, after check the suggested packages, some are not installed. I installed all packages from AUR and my device works perfectly.
> 
> Thank's a lot for the job and the support.
> 
> image

Great !!! :)

**Pull request merged**
