### PR TITLE
driver: create power_supply for battery information (fixes #87)

### LINKED ISSUE #87: upower support
> UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.

https://upower.freedesktop.org/

(for mice (or other devices) with a built-in battery)

### PR DESCRIPTION
**Pull request by babbaj**
Only implemented for mice because I only have a viper v2. Still need to fix formatting and only register a power_supply for mice that have batteries.
One weird thing I noticed is charge_status seems to be the same as charge_level, is that normal?

### CODE REVIEW

**Comment by babbaj** [comment]
closing because this was supposed to be a draft

**Comment by z3ntu** [comment]
Fwiw you could've marked it as draft retroactively

**Comment by babbaj** [comment]
ive tried to before but never saw a way

**Comment by z3ntu** [comment]
There's a button somewhere, a bit hidden ;)

**Pull request closed without merging**
