### PR TITLE
Added support for Razer Blade Advanced (Early 2021)

### PR DESCRIPTION
**Pull request by EtienneMueller**
Added support for Razer Blade Advanced (Early 2021)

### CODE REVIEW

**Comment by LDMFD** [comment]
@EtienneMueller I understand this PR is specifically for LED support. Other than that, are Bluetooth and Suspend (lid closure) working for you out of the box? Which distribution are you using?

**Comment by EtienneMueller** [comment]
@cachvico actually the WiFi is only natively supported from kernel version 5.10, so I directly installed 21.04 (which is on kernel 5.11). WiFi and bluetooth are working out of the box, but it still had the suspend boot loop bug. Luckiliy it can be fixed in the grub config. I explained my whole installation process here:
https://etiennemueller.github.io/razer-blade-data-science/

**Comment by michaelbenayoun** [comment]
Hi Etienne, 
I checked your small guide (https://etiennemueller.github.io/razer-blade-data-science/), that's really neat!
I have an issue with screen glitches after sleep (a bit like screen interference) that I am not able to solve, have you run into the same thing? 
I am under Ubuntu 20.04 LTS but updated the kernel to 5.11.0-051100-generic. I think of switching to Ubuntu 21.04 but just wanted to know if you had any idea on what might cause this.

**Comment by LDMFD** [comment]
Hi folks,

I have a similar setup guide here, https://gist.github.com/cachvico/03b6e37c8907e277dafc6c6183a732d5

@EtienneMueller my lid work-around (simply disabling "suspend on close") is inferior to your fix. Also Bluetooth simply wasn't working for me. I will spend some more time on these issues when I have energy!

@michaelbenayoun do the screen glitches manifest themselves as an occasional "jumping" of the display, like the whole thing seems to jump up and down by a pixel. For me, this can happen a few times a minute or not happen for a while. Does this sound like what you're experiencing also?

**Comment by michaelbenayoun** [comment]
@cachvico I get that sometimes, but most of the time it is vertical or horizontal interference lines (a bit like you would get on old tv screens with no signal) , it only happens after sleep. And it happens randomly after waking up the computer from sleep mode.

**Comment by EtienneMueller** [comment]
@michaelbenayoun no, I have not had any issues with the screen. Which display do you have? 

@cachvico Bluetooth also works perfectly fine for me, I only get sometimes some cracks when switching between sources (e.g. Spotify to YouTube). But there are different chips for Wifi+BT build into the base and advanced model (Intel AX201 and AX210), could probably be a driver issue.

For both of you I would simply suggest trying Ubuntu 21.04, as it should support all the hardware that is built into the Blade 2021, otherwise it can get too hacky.

Does any of you have the base model? Could you try my fork of OpenRazer: https://github.com/EtienneMueller/openrazer/tree/razer_blade_base_early_2021. I added the PID of the base model as described here: https://github.com/openrazer/openrazer/issues/1442 and I am relatively sure that it works, but I am not able to test it so I didn't do a pull request so far.

**Comment by michaelbenayoun** [comment]
I have the advanced model with the 365Hz screen. 
I updated to Ubuntu 21.04 and installed openrazer from your fork (it works, thank you!!), and still have the issue for screen, which kernel version are you using?

**Comment by EtienneMueller** [comment]
@michaelbenayoun I am on kernel 5.11.0. As I don't have the problem and we both have the advanced model, it could only be the display panel. Could adjusting the refresh rate help? Or possibly looking for a newer driver of the display?

**Comment by z3ntu** [comment]
Have you tested all the lighting effects and do they work properly? You can check either with a frontend (polychromatic/RazerGenie) or via d-feet (Session Bus -> org.razer -> /org/razer/device/$something -> razer.device.lighting.*)

**Comment by therealphatmike** [comment]
I built and tested this branch, it works perfectly with RazerGenie. I noticed that Polychromatic had issues related to layout, but it seems more like a polychromatic issue than a driver issue as I could edit lighting effects they just may not show up in the right place.

Good work, and thanks for doing this.

**Review by z3ntu — APPROVED** [review]
LGTM, thank you for the patch and thanks for testing!

**Comment by LDMFD** [comment]
> For both of you I would simply suggest trying Ubuntu 21.04, as it should support all the hardware that is built into the Blade 2021, otherwise it can get too hacky.

Unfortunately the worst problem for me - the display glitching periodically - is lower level than Ubuntu - for example it happens in the grub bootloader prompt.

It may be only this specific model - Early 2021 Blade Adv, 15" (RTX 3070, FHD) - however I don't have any other leads on it and the problem is bad enough (a glitch every few seconds at times) that its making me think to sell the machine while its still hot.

**Pull request merged**
