### PR TITLE
Add support for Razer Blade Stealth (2019)

### PR DESCRIPTION
**Pull request by christat**
Sadly, I didn't manage to get exactly the exact same kind of pictures used for other laptop models. Perhaps someone with better browsing skills can fix that eventually :D

### CODE REVIEW

**Comment by z3ntu** [comment]
Does everything work properly?

**Comment by christat** [comment]
Afaik yep! I just noticed @MartinPaulEve posted a PR for the same machine (same device id, but Razer markets it as the Blade Stealth 2019) Which is pretty similar, but his PR mixed the lighting entries with older stealth laptop models with per-key effects, which is no longer available in this model. Case and point, if you need more testers maybe he (or some other volunteer) can test it too?

**Comment by braydenhouston** [comment]
Just picked up a 2019 Stealth and would be happy to help test. Would love to see this merged go through.

**Comment by christat** [comment]
Great! Feel free to follow the [build guide](https://github.com/openrazer/openrazer/wiki/Building-a-package) (I tested it on ubuntu at least) and report back.

**Comment by terricain** [comment]
Once its been tested and conflicts resolved merge away.

**Comment by braydenhouston** [comment]
Tested the branch from @christat. Driver installed without issue and then did a reboot.

 When interacting with the driver using Polychromatic the only change I could make was to adjust the LED brightness. When selecting any lighting effect a message `Failed to set effect "breath" for Razer Stealth (2019)` in red near the bottom of the window. The same message is shown for "static", "none", and "spectrum". 

Maybe there is some change that Polychromatic needs to make to take advantage of this suggested merge? Maybe there some additional changes needed for this driver before merging?

If there is anything else I can test to help out please let me know!

**Comment by christat** [comment]
huh, let me take another look before anything; slightly busy atm. EDIT: Ok, I just noticed the derp in this commit (never refactor without testing...). I'll anyways re-test it locally first and patch afterwards :+1:.

**Comment by braydenhouston** [comment]
Yeah been there a time or two, @christat. Just let me know when you're ready and I can do another test drive.

**Comment by christat** [comment]
@braydenhouston the follow-up commit fixes the issue. I tested it on ubuntu, also using Polychromatic. I will rebase this PR tomorrow to fix those conflicts and then it can get merged.

**Comment by christat** [comment]
@braydenhouston Feel free to test again. With that said, I don't have write access to the repo, so can @z3ntu or @terrycain merge it once CI passes?

**Comment by braydenhouston** [comment]
@christat Everything is working perfectly as far as I can tell!

EDIT: Only thing I can find that doesn't work is that Application Profiles don't seem to trigger, manually or automatically. That might be an issue to take over to Polychromatic though, but I figured I would mention it.

**Comment by christat** [comment]
:fireworks: About the profiles, you can bring up the issue in their repo :)

**Comment by christat** [comment]
Any chances of this getting merged? @z3ntu @terrycain

**Review by z3ntu — APPROVED** [review]
LGTM

**Pull request merged**
