### PR TITLE
Add support for Razer Orochi V2

### LINKED ISSUE #1553: Support for Razer Orochi V2
### Device Info

* Name: Orochi v2  
*Razer Synapse shows this as Razer Orochi v2 White Edition*
* Product Number: RZ01-03730400
* Model Number: RZ01-0373

### Device Information
Please post the output of
    `lsusb -d 1532: -v`  

```
Bus 001 Device 012: ID 1532:0094 Razer USA, Ltd Orochi V2
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0094 
  bcdDevice            1.00
  iManufacturer           1 Razer
  iProduct                2 Orochi V2
  iSerial                 3 000000000000
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0086
    bNumInterfaces          5
    bConfigurationValue     1
    iConfiguration          4 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     314
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        4
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     325
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     348
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1  
```

Please post the output of
    `ls -lah /dev/input/by-id/`  

```
lrwxrwxrwx    10 root  8 Jul 17:51  usb-Razer_Orochi_V2_000000000000-event-if01 -> ../event24
lrwxrwxrwx    10 root  8 Jul 17:51  usb-Razer_Orochi_V2_000000000000-event-if03 -> ../event26
lrwxrwxrwx    10 root  8 Jul 17:51  usb-Razer_Orochi_V2_000000000000-event-mouse -> ../event21
lrwxrwxrwx    10 root  8 Jul 17:51  usb-Razer_Orochi_V2_000000000000-if01-event-kbd -> ../event22
lrwxrwxrwx    10 root  8 Jul 17:51  usb-Razer_Orochi_V2_000000000000-if01-event-mouse -> ../event23
lrwxrwxrwx     9 root  8 Jul 17:51  usb-Razer_Orochi_V2_000000000000-if01-mouse -> ../mouse5
lrwxrwxrwx    10 root  8 Jul 17:51  usb-Razer_Orochi_V2_000000000000-if02-event-kbd -> ../event25
lrwxrwxrwx     9 root  8 Jul 17:51  usb-Razer_Orochi_V2_000000000000-mouse -> ../mouse4
```

### Packet Captures
I am unsure about how I should do it on a non-RGB mouse, but [here](https://drive.google.com/drive/folders/1Wyp4oh7uGKeWJxqleWIrSJSlTdyD7NYX?usp=sharing) is a gdrive folder with pcapng for each click. Let me know if anything is missing.  
https://drive.google.com/drive/folders/1Wyp4oh7uGKeWJxqleWIrSJSlTdyD7NYX?usp=sharing

### Synapse Screenshots
Screenshot_win10_2021-07-08_18:47:45
Screenshot_win10_2021-07-08_19:18:44
Screenshot_win10_2021-07-08_19:19:30
Screenshot_win10_2021-07-08_19:19:44

### PR DESCRIPTION
**Pull request by z3ntu**
Fixes #1553

---

Building from this PR: https://github.com/openrazer/openrazer/wiki/Building-a-package

### CODE REVIEW

**Comment by nulm** [comment]
How to test?

**Comment by z3ntu** [comment]
@nulm You can install openrazer from this branch by following https://github.com/openrazer/openrazer/wiki/Building-a-package for your distro.
Then you can use an openrazer frontend of your choice (polychromatic/RazerGenie) and see if all the options there work and then report back your findings.

**Comment by z3ntu** [comment]
@luiszimmermann Next try with latest commit 8eeba86, hopefully DPI works now :)

**Comment by coding-cucumber** [comment]
How do I test this on macOS?

**Comment by luiszimmermann** [comment]
> @luiszimmermann Next try with latest commit [8eeba86](https://github.com/openrazer/openrazer/commit/8eeba86adfb9733f4ccfef7966a4b965f6b35774), hopefully DPI works now :)

Works like a charm, Thanks!

**Comment by notsukamto** [comment]
> @luiszimmermann Next try with latest commit [8eeba86](https://github.com/openrazer/openrazer/commit/8eeba86adfb9733f4ccfef7966a4b965f6b35774), hopefully DPI works now :)

Just got my Orochi V2 to test this with. Tested on RazerGenie, RazerCommander and Polychromatic. The DPI settings works perfectly for all of them. As a bonus, Polychromatic shows how much battery is left although I'm not sure how accurate it is. Side buttons options doesn't exist, but I assume that's just not available on openrazer?

Anyway, thank you very much for this!

**Comment by z3ntu** [comment]
Thanks for testing! Is there anything else that's maybe not working or missing completely of the stuff openrazer supports? Otherwise I think this should be ready.

> Side buttons options doesn't exist, but I assume that's just not available on openrazer?

If you mean to map something onto the side buttons, this is not handled by openrazer but e.g. by https://github.com/sezanzeb/key-mapper

**Comment by notsukamto** [comment]
> 



> Thanks for testing! Is there anything else that's maybe not working or missing completely of the stuff openrazer supports? Otherwise I think this should be ready.
> 
> > Side buttons options doesn't exist, but I assume that's just not available on openrazer?
> 
> If you mean to map something onto the side buttons, this is not handled by openrazer but e.g. by https://github.com/sezanzeb/key-mapper

Thanks, I always used key-mapper for my previous mouses, so I'm glad that it works with this one too.

About other support, maybe something that's missing is the option to have fewer DPI settings on the DPI cycle. By default it has 5 and I'm trying to lower it to only 3 on Polychromatic by having the highest two settings set to 0 DPI, but it didn't disable the last 2 layers, instead having them on the same DPI settings as the current highest one.

Also, cycling DPI settings isn't directly refreshed on all the client front-end I tested with. All of them have to be restarted to read and enable edit on the other DPI settings. Polychromatic does enable you to edit all of the DPI settings at once and sync it, but the per DPI setting behaves the same. I was wondering whether or not this is intended.

That's about all I can think of. Hopefully this helps.

**Comment by z3ntu** [comment]
Let's say this has been tested enough, merging...

**Comment by nulm** [comment]
This was merged into the main branch right? Still showing as a unrecognized device.  PID = 1532:0094.

Pretty sure I'm just doing something incorrectly.

**Comment by jinlinux** [comment]
> This was merged into the main branch right? Still showing as a unrecognized device. PID = 1532:0094.
> 
> Pretty sure I'm just doing something incorrectly.

I am waiting for this too but there hasn't been a release since Dec last year.

**Comment by luiszimmermann** [comment]
> This was merged into the main branch right? Still showing as a unrecognized device. PID = 1532:0094.
> 
> Pretty sure I'm just doing something incorrectly.



> > This was merged into the main branch right? Still showing as a unrecognized device. PID = 1532:0094.
> > Pretty sure I'm just doing something incorrectly.
> 
> I am waiting for this too but there hasn't been a release since Dec last year.

I think you guys could use the daily build to get the orochi v2 support.

**Pull request merged**
