### PR TITLE
Add Razer Core support

### PR DESCRIPTION
**Pull request by CalcProgrammer1**
This pull request adds driver support for the Razer Core.  It has all the standard effects including custom, which is one row with 9 LEDs, LED 0 being the internal single-zone strip that lights up the GPU.

### CODE REVIEW

**Comment by terricain** [comment]
Looks good, I'll probably bring it into a branch and move it to how the kraken works (it looks a little nicer, less variables to mess with etc...) and update some other files, then should be all good.

**Comment by CalcProgrammer1** [comment]
I would advise to keep it the same as the Firefly and Razer Mug personally.  Consistency is nice to have between similar devices.  Having a single variable to write to makes sense but having the Core match other linear LED devices makes more sense IMO.  Otherwise you have two/three linear LED devices (Core, Mug, Deathstalker) that work one way and another that works a different way, making it more difficult if you want to code for all of them.

**Comment by terricain** [comment]
Functionally its the same, code is just a bit tidier/safer is all,

**Comment by terricain** [comment]
\+ firefly and mug will be updated soonish too

**Comment by terricain** [comment]
Mind trying out driver on branch `CalcProgrammer1-razer-core`, should work exactly as it did. Also added daemon support, no need to test that (unless you want to), nothing new really in it so have enough confidence that it works.

**Comment by CalcProgrammer1** [comment]
Ok, I'll do that in a bit.  As long as Firefly, mug, and Core are all updated together I'd say it's a good change.  I know the kernel drivers aren't meant to have a finalized interface so if need be I'll update my visualizer code.  I'm not really a Python programmer which is why I avoided the daemon.

**Comment by terricain** [comment]
I probably wont do the firefly and mug today but their interface wont change, plus i can test both the mug and firefly ha

**Comment by CalcProgrammer1** [comment]
Looking through your changes I noticed you forgot to change razermug to razercore when you copy pasted this line:

https://github.com/terrycain/razer-drivers/commit/54cd63cae9943326c4006f94df7a9691315dd49e

Edit:  I misread your comment about the changing to match Kraken, I thought you meant making it so the custom effect format changed.  You meant adding mutexes and such.  I get what you mean now after looking at the changes lol.

**Comment by terricain** [comment]
Ahh good spot. And yeah I don't like to change the interface to things as there's a fair amount of stuff to modify after. If interfaces do need to be changed I'll normally do one set of big changes.

**Comment by CalcProgrammer1** [comment]
The code changes you made are fine, it works as expected for all the basic effects and custom effect as well.

**Comment by terricain** [comment]
Nice :) Will merge

**Comment by terricain** [comment]
Ahh and will fix dkms :wink:

**Pull request merged**
