### PR TITLE
Add support for Razer Naga 2012

### PR DESCRIPTION
**Pull request by kust2708**
Initial implementation for Razer Naga 2012.

Features :
- Set Lighting Logo state
- Set Lighting Scroll state
- Set Lighting Backlight state
- Set DPI
- Set Polling rate

### CODE REVIEW

**Comment by kust2708** [comment]
Related to https://github.com/openrazer/openrazer/issues/377

**Comment by z3ntu** [comment]
Hi, this generally looks fine.

Did you test all effects and do they work properly?

**Comment by kust2708** [comment]
Hi, I tried on razergenie and it works well, I use my implementation since this PR without any problem. 
I can't try on Polychromatic since it show only black background.
Screenshot_20191214_133252

The only one effect I can't determine if this is a bug or not, is the DPI hose going systematically on 5585dpi when I set on 5600dpi (max possible value on the naga 2012).

**Comment by kust2708** [comment]
Okay, I forgot to reboot after updating kde plasma 
Screenshot_20191214_135042
Same behavior on polychromatic with DPI, when I set to 5600dpi and I move my mouse the dpi cursor automatically switch to 5585.
Another thing I noticed, logo lightning switch are a bit crazy on polychromatic (work well on razergenie).

**Comment by z3ntu** [comment]
The DPI behavior is because this and a few other devices have the DPI (0-5600) stored in a single byte per direction (x/y), which means that some precision is lost compared to the original value, which you see by the value changing slightly.

**Review by z3ntu — APPROVED** [review]
LGTM, thanks a lot for the patch!

**Comment by kust2708** [comment]
You're welcome, I hope it will be useful.

**Pull request merged**
