### PR TITLE
Support for BlackWidow V3 Tenkeyless

### LINKED ISSUE #1318: Support for BlackWidow V3 Tenkeyless
### Device Info

* Name: `BlackWidow V3 Tenkeyless`
* Product Number: `RZ03-03490100-R3M1`
* Model Number: `RZ03-0349`

### Device Information
```
$ lsusb -d 1532: -v
```
```
Bus 003 Device 008: ID 1532:0a24 Razer USA, Ltd 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0a24 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x006d
    bNumInterfaces          4
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     179
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0016  1x 22 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              2 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     348
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0002  1x 2 bytes
        bInterval               1
```
```
$ ls -lah /dev/input/by-id/
```
```
total 0
drwxr-xr-x 2 root root 260 Oct 31 13:00 .
drwxr-xr-x 4 root root 860 Oct 31 13:00 ..
lrwxrwxrwx 1 root root  10 Oct 31 13:00 usb-046d_HD_Pro_Webcam_C920_AB8FBA2F-event-if00 -> ../event25
lrwxrwxrwx 1 root root  10 Oct 31 12:59 usb-CKFGH10F442030026752_Integrated_Webcam_HD_200901010001-event-if00 -> ../event21
lrwxrwxrwx 1 root root   9 Oct 31 12:59 usb-ELAN_Touchscreen-event-if00 -> ../event8
lrwxrwxrwx 1 root root  10 Oct 31 13:00 usb-Logitech_USB_Receiver-if02-event-mouse -> ../event24
lrwxrwxrwx 1 root root   9 Oct 31 13:00 usb-Logitech_USB_Receiver-if02-mouse -> ../mouse3
lrwxrwxrwx 1 root root  10 Oct 31 13:00 usb-Razer_Razer_BlackWidow_V3_Tenkeyless-event-if01 -> ../event27
lrwxrwxrwx 1 root root  10 Oct 31 13:00 usb-Razer_Razer_BlackWidow_V3_Tenkeyless-event-if03 -> ../event31
lrwxrwxrwx 1 root root  10 Oct 31 13:00 usb-Razer_Razer_BlackWidow_V3_Tenkeyless-event-kbd -> ../event22
lrwxrwxrwx 1 root root  10 Oct 31 13:00 usb-Razer_Razer_BlackWidow_V3_Tenkeyless-if01-event-kbd -> ../event26
lrwxrwxrwx 1 root root  10 Oct 31 13:00 usb-Razer_Razer_BlackWidow_V3_Tenkeyless-if02-event-mouse -> ../event30
lrwxrwxrwx 1 root root   9 Oct 31 13:00 usb-Razer_Razer_BlackWidow_V3_Tenkeyless-if02-mouse -> ../mouse4
```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>

### PR DESCRIPTION
**Pull request by sophec**
Given there has been no progress on #1318 in quite some time and one of my friends has this board, she asked me to take a crack at it. I've done the best I can without the hardware in front of me, so this is WIP until it is confirmed working on her machine.

Fixes #1318

### CODE REVIEW

**Comment by slugcat-dev** [comment]
As I have the same keyboard, I could also test this, just tell me how

**Review by slugcat-dev — APPROVED** [review]
Looks fine

**Comment by sophec** [comment]
> 
> 
> As I have the same keyboard, I could also test this, just tell me how

Clone my repository, checkout the `blackwidow-v3-tk` branch, then follow the instructions to build and install the driver and libraries associated with it. If you reboot your machine, the examples should work with your keyboard, ideally.

**Comment by slugcat-dev** [comment]
`| DEBUG    | Loaded device specification: RazerBlackWidowV3TK --------------------- (1532:0A24)`
OpenRazer does load the device specification, but Polychromatic still says that my keyboard is unrecognized. Does Polychromatic have it's own list of devices?

**Comment by sophec** [comment]
Hm, I don't think they should, but they might. As I understand it, it appears that OpenRazer is supposed to maintain the list and everything using the python library then inherits from that list. You can look into that and see what you find here: https://github.com/polychromatic/polychromatic

**Comment by sophec** [comment]
I would appreciate if some of the maintainers of OpenRazer would check through my PR and review it. I want to make sure I didn't miss anything, as I am not a user of this software and likely won't notice it myself.

**Comment by slugcat-dev** [comment]
@z3ntu please have a look at this

**Comment by ariklevin** [comment]
Sorry for the lame question :)
I'm on Ubuntu - How do I install your branch?

10x

**Comment by sophec** [comment]
@ariklevin Make sure that you do not have openrazer installed by your package manager (so we avoid stepping on any toes). You'll need the `build-essential` package installed. I think you'll also need the `linux-headers` package for your kernel version (`apt install "linux-headers-$(uname -r)"`, I think). Make sure you also have `git` installed, of course, and you'll need Python, though presumably you already have it.

```
git clone https://github.com/willeccles/openrazer -b blackwidow-v3-tk --depth 1
cd openrazer
sudo make install_i_know_what_i_am_doing
```

Note that to uninstall, you can use `sudo make uninstall`. You'll need to do this before you reinstall from your package manager at a later date, most likely.

**Comment by ariklevin** [comment]
> @ariklevin Make sure that you do not have openrazer installed by your package manager (so we avoid stepping on any toes). You'll need the `build-essential` package installed. I think you'll also need the `linux-headers` package for your kernel version (`apt install "linux-headers-$(uname -r)"`, I think). Make sure you also have `git` installed, of course, and you'll need Python, though presumably you already have it.
> 
> ```
> git clone https://github.com/willeccles/openrazer -b blackwidow-v3-tk --depth 1
> cd openrazer
> sudo make install_i_know_what_i_am_doing
> ```
> 
> Note that to uninstall, you can use `sudo make uninstall`. You'll need to do this before you reinstall from your package manager at a later date, most likely.

@willeccles Thank you very much for the quick response - I'll try it out

**Comment by z3ntu** [comment]
Please don't use this makefile target unless you want to break your machine.. The wiki page https://github.com/openrazer/openrazer/wiki/Building-a-package exists for a purpose.

**Review by z3ntu — APPROVED** [review]
Diff looks sane.
I'll wait for a second person to test this though (so far tested by @XECortex)

**Comment by slugcat-dev** [comment]
> Please don't use this makefile target unless you want to break your machine.. The wiki page https://github.com/openrazer/openrazer/wiki/Building-a-package exists for a purpose.

I installed it this way now, the device is recognized, everything works fine, _except custom effects and ripple_.

**Comment by sophec** [comment]
Sounds like the device's configuration might not be quite right; I don't know enough about this to fix that. @z3ntu any chance you could give it a look (and maybe see if someone in the original issue has more info on that)?

**Comment by z3ntu** [comment]
Try putting the case statement here (basically one `case` down):
```c
case USB_DEVICE_ID_RAZER_ORNATA_CHROMA_V2:
            report = razer_chroma_extended_matrix_set_custom_frame(row_id, start_col, stop_col, (unsigned char*)&buf[offset]);
            report.transaction_id.id = 0x1F;
```

**Comment by sophec** [comment]
> 
> 
> Try putting the case statement here (basically one `case` down):
> 
> ```c
> case USB_DEVICE_ID_RAZER_ORNATA_CHROMA_V2:
>             report = razer_chroma_extended_matrix_set_custom_frame(row_id, start_col, stop_col, (unsigned char*)&buf[offset]);
>             report.transaction_id.id = 0x1F;
> ```

Is this for the one specific case, or do you think many need to be changed?

**Comment by sophec** [comment]
I see now that you made [a comment](https://github.com/openrazer/openrazer/issues/1318#issuecomment-787085409) explaining to use `ZERO_LED` instead of `BACKLIGHT_LED`. Should I go ahead and move every situation where it's using `BACKLIGHT_LED` to `ZERO_LED`? I am not sure what the difference between these two are. Happy to change them, however.

**Comment by sophec** [comment]
Actually what I'm seeing in the change you suggested is that the only difference appears to be the transaction ID being set to `0x1F`. On just about every other case statement in the driver, there is an option with the `0x1F` as well, and my patch does not use that option for any of them. Should this change? I'm not sure what that ID is used for here.

**Comment by z3ntu** [comment]
I think 0x3f is the "default" transaction id (the highest 3 bits (those that actually change) are actually something else, but we have it under transaction id in the driver)

If backlight led works, then I think you can continue using it. zero_led is I think a kind of virtual id that addresses all leds on the device instead of just a specific one, so I actually think that using backlight_led is better if that works.

Generally just doing trial&error with the different possibilities should be good enough for fixing up the remaining parts.

**Comment by sophec** [comment]
Well, I made the suggested change as well as fixed the `MATRIX_DIMS`, which I had done wrong before by accident (copy and pasted and then forgot to update). Having updated `MATRIX_DIMS`, do I have to run any of the scripts to generate stuff?

**Comment by z3ntu** [comment]
MATRIX_DIMS is a daemon configuration, we just have this "fake driver" generated from the driver parts (.c files) so nothing to do there (if the CI doesn't complain)

**Comment by sophec** [comment]
@XECortex would you mind testing the latest revision?

**Comment by slugcat-dev** [comment]
Okay, one second... or two

**Comment by slugcat-dev** [comment]
Looks good. Some things I noticed:
- The keyboard doesn't change the direction of the wave effect, it's always left-to-right
- Custom effects don't work with razerCommander, but do with Polychromatic. (RazerGenie doesn't support my keyboard layout yet)

**Comment by sophec** [comment]
> 
> 
> Looks good. Some things I noticed:
> 
>     * The keyboard doesn't change the direction of the wave effect, it's always left-to-right
> 
>     * Custom effects don't work with razerCommander, but do with Polychromatic. (RazerGenie doesn't support my keyboard layout yet)

@z3ntu Any thoughts on the first one? The second sounds more like it's related to razerCommander, since it works with Polychromatic. Not sure if the first is something else I need to change.

**Comment by faridgh1991** [comment]
> > Looks good. Some things I noticed:
> > ```
> > * The keyboard doesn't change the direction of the wave effect, it's always left-to-right
> > 
> > * Custom effects don't work with razerCommander, but do with Polychromatic. (RazerGenie doesn't support my keyboard layout yet)
> > ```
> 
> @z3ntu Any thoughts on the first one? The second sounds more like it's related to razerCommander, since it works with Polychromatic. Not sure if the first is something else I need to change.

for direction of the wave effect use 'WAVE_DIRS = (1, 2)' instead of (0, 1). it's ok on blackwidow v3 pro.

**Comment by sophec** [comment]
@XECortex sorry to bother you again, but do you think you could give this another test?

**Comment by AdarshGrewal** [comment]
Just tested with Polychromatic changing wave directions seems to be working fine.

**Comment by slugcat-dev** [comment]
Wave direction does work now, the custom effects don't work because they aren't supported by the frontends yet

**Comment by sophec** [comment]
I'm going to squash commits and assume that at this point no further edits will be made.

**Comment by slugcat-dev** [comment]
I guess we can merge now. @z3ntu what do you think?

**Comment by z3ntu** [comment]
LGTM, thanks for the contribution!

**Comment by sophec** [comment]
Glad I could help :)

**Comment by sgofferj** [comment]
Works here, except the app/daemon doesn't recognize when game mode is activated on the keyboad with Fn+F10.

**Pull request merged**
